plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'com.tankua.telegramlogin'
version = '1.0.0'

android {
  namespace 'com.tankua.telegramlogin'
  defaultConfig {
    versionCode 1
    versionName "1.0.0"
  }
}

repositories {
  google()
  mavenCentral()
  maven {
    url = uri("https://maven.pkg.github.com/TelegramMessenger/telegram-login-android")
    credentials {
      username = project.findProperty("gpr.user") ?: System.getenv("GITHUB_USERNAME") ?: ""
      password = project.findProperty("gpr.key") ?: System.getenv("GITHUB_TOKEN") ?: ""
    }
  }
}

dependencies {
  implementation 'org.telegram:login-sdk:1.0.0'
}
