-- Production metadata, review workflow, and run tracking for destination images.
BEGIN;

CREATE TABLE IF NOT EXISTS public.destination_image_runs (
  id UUID PRIMARY KEY,
  status TEXT NOT NULL CHECK (status IN ('running','completed','failed','cancelled')),
  configuration JSONB NOT NULL DEFAULT '{}'::jsonb,
  statistics JSONB NOT NULL DEFAULT '{}'::jsonb,
  started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS public.destination_image_assets (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  destination_id UUID NOT NULL UNIQUE REFERENCES public.destinations(id) ON DELETE CASCADE,
  image_url TEXT NOT NULL,
  medium_url TEXT NOT NULL,
  thumbnail_url TEXT NOT NULL,
  source TEXT NOT NULL,
  photographer TEXT,
  license TEXT NOT NULL,
  width INTEGER NOT NULL CHECK (width > 0),
  height INTEGER NOT NULL CHECK (height > 0),
  confidence NUMERIC(5,4) NOT NULL CHECK (confidence BETWEEN 0 AND 1),
  original_source_url TEXT NOT NULL,
  phash TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','superseded','rejected')),
  last_verified_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS destination_image_assets_phash_idx ON public.destination_image_assets(phash);
CREATE INDEX IF NOT EXISTS destination_image_assets_source_idx ON public.destination_image_assets(source);

CREATE TABLE IF NOT EXISTS public.destination_image_candidates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  destination_id UUID NOT NULL REFERENCES public.destinations(id) ON DELETE CASCADE,
  run_id UUID REFERENCES public.destination_image_runs(id) ON DELETE SET NULL,
  source TEXT NOT NULL,
  source_id TEXT,
  title TEXT NOT NULL DEFAULT '',
  image_url TEXT NOT NULL,
  original_source_url TEXT NOT NULL DEFAULT '',
  photographer TEXT,
  license TEXT NOT NULL DEFAULT 'unknown',
  width INTEGER,
  height INTEGER,
  confidence NUMERIC(5,4) NOT NULL CHECK (confidence BETWEEN 0 AND 1),
  score_breakdown JSONB NOT NULL DEFAULT '{}'::jsonb,
  rejection_reasons TEXT[] NOT NULL DEFAULT '{}',
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected','duplicate')),
  reviewed_by UUID REFERENCES public.users(id) ON DELETE SET NULL,
  reviewed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS destination_image_candidates_review_idx
  ON public.destination_image_candidates(status, confidence DESC);
CREATE INDEX IF NOT EXISTS destination_image_candidates_destination_idx
  ON public.destination_image_candidates(destination_id, created_at DESC);

ALTER TABLE public.destination_image_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.destination_image_assets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.destination_image_candidates ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public reads active destination images" ON public.destination_image_assets;
CREATE POLICY "Public reads active destination images" ON public.destination_image_assets
  FOR SELECT USING (status = 'active');

-- Candidate and run tables deliberately have no public policies. The service role
-- and Supabase dashboard retain access; review UI policies can be added for admins.

COMMIT;
