-- Generated by scripts/enrich_destinations.py
-- Review destinations_enrichment_report.csv before applying.
BEGIN;

UPDATE public.destinations
SET region = 'Sidama', city = 'Hawassa', location = '{"lat":7.0529428,"lng":38.4995556}'
WHERE id = '2257b419-eede-4d13-add6-894b60809442'::uuid;

UPDATE public.destinations
SET region = 'Amhara', location = '{"lat":13.2458802,"lng":38.0999456}'
WHERE id = '23226a89-46e7-4984-99ee-5cc67e1cc906'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole', location = '{"lat":8.9791887,"lng":38.7965793}'
WHERE id = '234d14a7-595c-4f26-9ad8-ef4b5ba5a0bc'::uuid;

UPDATE public.destinations
SET region = 'Sidama', location = '{"lat":6.5630695,"lng":38.2292849}'
WHERE id = '24028b03-8409-4402-9702-50e66d44c031'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Chencha', location = '{"lat":6.251095,"lng":37.572946}'
WHERE id = '241dedbc-9143-4421-ba80-241851d589b3'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Tekeze', location = '{"lat":11.8756797,"lng":38.9503039}'
WHERE id = '242deb2a-15b7-4f49-95d3-ca4a5481bc8a'::uuid;

UPDATE public.destinations
SET region = 'Oromia', location = '{"lat":8.78333,"lng":38.71667}'
WHERE id = '24d6e6ee-90b9-49d3-9b43-ac8fa2d59587'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ketema', location = '{"lat":9.0296278,"lng":38.7396038}'
WHERE id = '24e52fd3-2b96-40f6-9ebf-1660d26f9fce'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Bahir Dar Special Zone', location = '{"lat":11.5949663,"lng":37.3882251}'
WHERE id = '25181baa-dd2e-4d26-a931-94ea498aabf5'::uuid;

UPDATE public.destinations
SET region = 'Dire Dawa', city = 'Dire Dawa', location = '{"lat":9.6288408,"lng":41.772516}'
WHERE id = '2541fa9d-3410-4ed4-a12f-106b87467960'::uuid;

UPDATE public.destinations
SET region = 'Sidama', city = 'Hawassa', location = '{"lat":7.0481029,"lng":38.47861}'
WHERE id = '25638c60-8a42-4859-962e-f570460df897'::uuid;

UPDATE public.destinations
SET region = 'Central Ethiopia Regional State', city = 'Durame', location = '{"lat":7.2438769,"lng":37.9049922}'
WHERE id = '2648c575-a2d2-4212-8668-16e9a5427911'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Lalibela', location = '{"lat":12.0226731,"lng":39.0389138}'
WHERE id = '2739a16a-891a-4f82-b042-dd752c80e99f'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Gulale', location = '{"lat":9.076097,"lng":38.7555656}'
WHERE id = '27a4cc0d-f108-482f-a29a-acebdb0019dc'::uuid;

UPDATE public.destinations
SET region = 'Somali', city = 'Jijiga', location = '{"lat":9.3508526,"lng":42.8003788}'
WHERE id = '28e87272-22cd-4185-b48f-b41045b57ce4'::uuid;

UPDATE public.destinations
SET region = 'Sidama', city = 'Hawassa', location = '{"lat":7.0481029,"lng":38.47861}'
WHERE id = '29e13269-fe95-4f8f-b377-e847cb275aa7'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Yirga Cheffe', location = '{"lat":6.1529383,"lng":38.2023167}'
WHERE id = '29fccaf1-be65-461b-90ae-c117133207d8'::uuid;

UPDATE public.destinations
SET region = 'Harar', city = 'Harar', location = '{"lat":9.3118304,"lng":42.1284009}'
WHERE id = '2aa948ce-3a4c-4503-b12d-7f5b82672ddd'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole', location = '{"lat":9.0002179,"lng":38.7833921}'
WHERE id = '2af6619d-f9f3-4eb8-a216-d05bdf9a16c1'::uuid;

UPDATE public.destinations
SET region = 'Amhara', location = '{"lat":10.7117887,"lng":37.8435035}'
WHERE id = '2b3cc33e-44bc-40f6-91a3-2b03e30b882b'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Sodere', location = '{"lat":8.4034494,"lng":39.3869748}'
WHERE id = '2b457328-e348-48cb-a3e2-abb51a7e161b'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ketema', location = '{"lat":9.0296278,"lng":38.7396038}'
WHERE id = '2b5884fb-6727-4c9f-84a5-a3383847f64d'::uuid;

UPDATE public.destinations
SET region = 'Harar', city = 'Harar', location = '{"lat":9.3118304,"lng":42.1284009}'
WHERE id = '2b5f377f-8d99-4993-b8e8-ccf8da4ce3ea'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Yeha', location = '{"lat":14.2859622,"lng":39.0179108}'
WHERE id = '2b9b6a29-6af6-4143-8476-c6640fa48689'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos', location = '{"lat":9.0211333,"lng":38.7622597}'
WHERE id = '2bb21cce-0463-4b4b-b67e-8a8aa16ec61b'::uuid;

UPDATE public.destinations
SET region = 'Gambela', city = 'Gambela', location = '{"lat":8.2503656,"lng":34.5877344}'
WHERE id = '2ca45248-7ec8-48f4-a9e0-7f1124edb90c'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Yeka', location = '{"lat":9.0205677,"lng":38.8002333}'
WHERE id = '2d2bfb20-6c88-413f-8fb4-95bb1e6f6e73'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ababa', location = '{"lat":9.0225621,"lng":38.7527167}'
WHERE id = '2d556d96-3289-4ce5-a184-282e055aa16e'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole', location = '{"lat":8.9924284,"lng":38.7887069}'
WHERE id = '2d60b921-5b3e-483e-9f91-4f5d30b86446'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Enferaz', location = '{"lat":12.2344189,"lng":37.6350175}'
WHERE id = '2e7db422-9fbc-4614-ad3a-f0dc3ba34130'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Waliso', location = '{"lat":8.5506266,"lng":37.978662}'
WHERE id = '2f041d9d-1e5e-45d5-a023-659c918b4cb8'::uuid;

UPDATE public.destinations
SET region = 'Sidama', city = 'Hawassa', location = '{"lat":7.0481029,"lng":38.47861}'
WHERE id = '2f10f5f5-db7c-4bcf-b459-76e9e262a07d'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Adama', location = '{"lat":8.5440099,"lng":39.2704532}'
WHERE id = '2fdd3b3b-1d57-4b22-abc7-0f17a133d020'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bishoftu', location = '{"lat":8.750004,"lng":38.981734}'
WHERE id = '2fdf0d0b-031d-4baa-9c68-8134aefb00d4'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Arba Minch', location = '{"lat":6.02604,"lng":37.56775}'
WHERE id = '30f7ccf6-0605-40f8-94e6-618b65f34410'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Sodere', location = '{"lat":8.4034494,"lng":39.3869748}'
WHERE id = '313cc0ef-37cb-4731-a89b-e437266f5abf'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Tis Abay', location = '{"lat":11.4878798,"lng":37.5875677}'
WHERE id = '31bd91e7-3957-48be-bcf9-95cdc479f8b2'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Menagesha', location = '{"lat":9.0543794,"lng":38.5707238}'
WHERE id = '32d0bf58-9506-487a-b207-0088d94d8bb8'::uuid;

UPDATE public.destinations
SET region = 'South West Ethiopia Peoples', city = 'Bonga', location = '{"lat":7.2645383,"lng":36.2460526}'
WHERE id = '33055c2d-3d3b-4ae6-ae3e-f0c2b2f70dcc'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Jimma', location = '{"lat":7.6756152,"lng":36.8478779}'
WHERE id = '332e2d86-9556-4895-ad43-b03c6a2a12c4'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Boneya', location = '{"lat":8.9123243,"lng":38.6592492}'
WHERE id = '346a51ed-8ebd-4ff6-ae94-7cf36b5b4560'::uuid;

UPDATE public.destinations
SET region = 'Dire Dawa', city = 'Dire Dawa', location = '{"lat":9.593829,"lng":41.862174}'
WHERE id = '34e22fdc-8fef-4e15-a13a-eb49f3986f0a'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Axum', location = '{"lat":14.1220982,"lng":38.7321749}'
WHERE id = '35319a8a-17e8-41b6-a8ae-eef550687a6d'::uuid;

UPDATE public.destinations
SET region = 'Sidama', city = 'Aleta Wendo', location = '{"lat":6.6046692,"lng":38.4247871}'
WHERE id = '357344f1-a5d8-4245-8f07-4540bb128467'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos', location = '{"lat":9.0204847,"lng":38.7595978}'
WHERE id = '35751b88-1994-4139-8b74-5539bf191154'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Waliso', location = '{"lat":8.5506266,"lng":37.978662}'
WHERE id = '35d6397b-a20b-4d7d-a6b4-10c90d44e769'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos', location = '{"lat":9.0102293,"lng":38.7606309}'
WHERE id = '36a6ad45-50c4-466e-8ded-a3c27b7140fa'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Walmara', location = '{"lat":8.96667,"lng":38.53333}'
WHERE id = '36d9e225-9741-48cd-9297-67e71f81fbda'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Arba Minch', location = '{"lat":6.0045363,"lng":37.5474553}'
WHERE id = '37f0b7c8-cc54-4f9e-a14a-104b9913b643'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos', location = '{"lat":9.0204847,"lng":38.7595978}'
WHERE id = '37f5b36a-b595-47fb-aa80-7e11c394677e'::uuid;

UPDATE public.destinations
SET region = 'Sidama', city = 'Cheffe', location = '{"lat":7.0529428,"lng":38.4995556}'
WHERE id = '3848e64d-2027-4c8f-85d6-87e8923a8ba6'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Debre Libanos', location = '{"lat":9.7120303,"lng":38.8475576}'
WHERE id = '388bf0c9-d060-400a-a311-2ca890a0e551'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Sululta', location = '{"lat":9.2893858,"lng":38.8135595}'
WHERE id = '388d8855-33eb-4032-b2ee-c9423102da5f'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Hana - Margo Mursi Bodie', location = '{"lat":6.2235574,"lng":36.1284585}'
WHERE id = '38c4066a-3b3c-48f7-8cc8-7c0b8033368a'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Gorgora', location = '{"lat":12.2382669,"lng":37.2971393}'
WHERE id = '38d56cfc-3ef3-414a-808c-9e68afc91394'::uuid;

UPDATE public.destinations
SET region = 'Central Ethiopia Regional State', city = 'Worabe', location = '{"lat":7.8534494,"lng":38.1872959}'
WHERE id = '3909a227-bd0a-43c1-a3ef-0610a4ca8572'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Ankober', location = '{"lat":9.5911547,"lng":39.7338213}'
WHERE id = '3967a6e1-0954-4972-b367-d7451ba824e6'::uuid;

UPDATE public.destinations
SET region = 'Afar', city = 'Asaita', location = '{"lat":11.5653325,"lng":41.4385892}'
WHERE id = '39f197e2-df52-4eee-8b5f-027d6becda3f'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole', location = '{"lat":9.0060961,"lng":38.8111966}'
WHERE id = '3b022814-100e-4a00-90f7-e2c03c479a33'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Ambo', location = '{"lat":8.982104,"lng":37.8554406}'
WHERE id = '3beee300-5790-4506-8b26-a9dbab07ac0c'::uuid;

COMMIT;
