-- Generated by scripts/enrich_destinations.py
-- Review destinations_enrichment_report.csv before applying.
BEGIN;

UPDATE public.destinations
SET region = 'Amhara', city = 'Ankober', location = '{"lat":9.5911547,"lng":39.7338213}'
WHERE id = '3bf629e5-d66a-44bc-beb4-19511eba4f01'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Yeka', location = '{"lat":9.0264604,"lng":38.7994481}'
WHERE id = '3bf8b3a4-8540-4eee-a1ce-50689836fe40'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bishoftu', location = '{"lat":8.7436854,"lng":38.9894021}'
WHERE id = '3c12660a-3d5d-462a-8b7d-cb23536e6d70'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole', location = '{"lat":9.0135725,"lng":38.7800846}'
WHERE id = '3ca7df6d-9ac5-45df-8134-a3696ec1c1c1'::uuid;

UPDATE public.destinations
SET region = 'Harar', city = 'Harar', location = '{"lat":9.3118304,"lng":42.1284009}'
WHERE id = '3cd274f9-95e9-4579-af27-7690e88184a8'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole', location = '{"lat":8.9968941,"lng":38.7859708}'
WHERE id = '3d580e54-b4d4-47d7-9b95-2893ae128832'::uuid;

UPDATE public.destinations
SET location = '{"lat":8.7948903,"lng":37.8910436}'
WHERE id = '3d7f1f98-a03c-465a-9e6d-acae80b5b970'::uuid;

UPDATE public.destinations
SET region = 'Amhara', location = '{"lat":13.2458802,"lng":38.0999456}'
WHERE id = '3d816d2c-3881-4ed4-a503-4601492b0a6a'::uuid;

UPDATE public.destinations
SET region = 'Amhara', location = '{"lat":11.9507719,"lng":37.294878}'
WHERE id = '3da4a265-b1fa-4350-84ef-ecc140ceece6'::uuid;

UPDATE public.destinations
SET region = 'Harar', city = 'Harar', location = '{"lat":9.3118304,"lng":42.1284009}'
WHERE id = '3db23fee-2dbc-404a-9022-3b48dbf83d9d'::uuid;

UPDATE public.destinations
SET location = '{"lat":6.9013463,"lng":40.8438263}'
WHERE id = '3de67ef9-3e68-4d65-9dfc-6c757f954f7b'::uuid;

UPDATE public.destinations
SET region = 'Sidama', city = 'Hawassa', location = '{"lat":7.0481029,"lng":38.47861}'
WHERE id = '3e0ed29f-df5d-402a-b21b-2df8b4cdfb74'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ababa', location = '{"lat":9.0391779,"lng":38.7625197}'
WHERE id = '3e9e006b-5a18-41d9-8cd3-606530b111f8'::uuid;

UPDATE public.destinations
SET region = 'Oromia', location = '{"lat":7.5198392,"lng":38.7715145}'
WHERE id = '3effdf2c-3399-434c-9c27-142f0e4b0899'::uuid;

UPDATE public.destinations
SET region = 'Dire Dawa', city = 'Dire Dawa', location = '{"lat":9.5913368,"lng":41.8566126}'
WHERE id = '3f2e278b-63af-4d8d-ba99-e0b6f9aa4098'::uuid;

UPDATE public.destinations
SET region = 'Afar', location = '{"lat":13.2972405,"lng":40.7809115}'
WHERE id = '3f8bde2a-5b1f-46a6-a08b-638ce57b9af3'::uuid;

UPDATE public.destinations
SET region = 'South West Ethiopia Peoples', city = 'Aman', location = '{"lat":6.9568642,"lng":35.5544431}'
WHERE id = '3fa89afb-9b36-44ac-a84f-e0b172694794'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bishoftu', location = '{"lat":8.7873711,"lng":38.9931534}'
WHERE id = '3ff7b68e-955f-4eb5-b42a-346b5963129d'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bishoftu', location = '{"lat":8.7549453,"lng":38.9902682}'
WHERE id = '40dceafe-a721-45d5-b5dc-b398f6141467'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Debre Birhan', location = '{"lat":9.6752117,"lng":39.5324899}'
WHERE id = '41500b39-2235-46c1-b55b-206505d6520d'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Mek''elē', location = '{"lat":13.4842836,"lng":39.4554493}'
WHERE id = '41599fab-1f83-4fde-8d85-d0b0b5488498'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Bahir Dar Special Zone', location = '{"lat":11.5949663,"lng":37.3882251}'
WHERE id = '41c5b841-9bd5-4124-a1a3-09e026f9e598'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Lalibela', location = '{"lat":12.0314601,"lng":39.0456552}'
WHERE id = '41f01f10-f08d-442d-aa98-4a0dfa4e2980'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ababa', location = '{"lat":9.0358119,"lng":38.7524315}'
WHERE id = '4200c6c4-410f-401b-895a-81171ee9ff99'::uuid;

UPDATE public.destinations
SET region = 'Sidama', city = 'Hawassa', location = '{"lat":7.0481029,"lng":38.47861}'
WHERE id = '4241b7fc-e227-4703-a87c-6ff9b811c30b'::uuid;

UPDATE public.destinations
SET region = 'Harar', city = 'Harar', location = '{"lat":9.3118304,"lng":42.1284009}'
WHERE id = '429cbb02-0553-4bd3-a83d-496da820faa6'::uuid;

UPDATE public.destinations
SET region = 'South West Ethiopia Peoples', city = 'Bonga', location = '{"lat":7.2645383,"lng":36.2460526}'
WHERE id = '42af2888-be4c-436c-9d31-bb49b65bb063'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bishoftu', location = '{"lat":8.750004,"lng":38.981734}'
WHERE id = '42bcb77f-f818-4d77-8fa7-0c449ed25adf'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Omorate', location = '{"lat":4.8032381,"lng":36.0504375}'
WHERE id = '42c3a813-fba4-4400-b5ab-e9889e9ff496'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Dorze', location = '{"lat":6.1948568,"lng":37.5743447}'
WHERE id = '430dbe98-7bd4-4332-afd7-b8065a00ad06'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Kombolcha', location = '{"lat":11.1090822,"lng":39.71663}'
WHERE id = '4399e3bf-d306-4b46-afe0-fd9faacf66b2'::uuid;

UPDATE public.destinations
SET region = 'South West Ethiopia Peoples', location = '{"lat":6.9042595,"lng":36.7301591}'
WHERE id = '44c08981-cd9c-4a63-8534-8e0696b56e96'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Gulale', location = '{"lat":9.072071,"lng":38.7328969}'
WHERE id = '44d24dd2-3228-40cc-8ffa-e238127d74ac'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Axum', location = '{"lat":14.1295237,"lng":38.7193084}'
WHERE id = '4500b86d-33a7-4a4d-8621-2aead50e48fe'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole', location = '{"lat":8.9843917,"lng":38.78306}'
WHERE id = '459bd083-540b-4ebd-bad5-ec2934ff5d63'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ababa', location = '{"lat":9.0358119,"lng":38.7524315}'
WHERE id = '464c9e92-d2a8-44bd-84cd-8cd7bc1db5ca'::uuid;

UPDATE public.destinations
SET region = 'Oromia', location = '{"lat":7.5198392,"lng":38.7715145}'
WHERE id = '4662ab4e-d913-456a-a9c1-b75341310441'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Axum', location = '{"lat":14.1220982,"lng":38.7321749}'
WHERE id = '46920ae5-0e0f-4210-b4f2-55c17b40a2eb'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Dessie', location = '{"lat":11.122604,"lng":39.634982}'
WHERE id = '469a3d71-1f0f-4c0e-92da-ee124e9252de'::uuid;

UPDATE public.destinations
SET region = 'Somali', city = 'Jijiga', location = '{"lat":9.3508526,"lng":42.8003788}'
WHERE id = '46ee0c9d-a5b4-4dd5-a2f0-8ce0aa62dd5f'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ketema', location = '{"lat":9.0296278,"lng":38.7396038}'
WHERE id = '47085634-9818-4da4-afc0-17902a7448b1'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ketema', location = '{"lat":9.0327612,"lng":38.7408349}'
WHERE id = '473e2c3c-a89f-464b-9539-cc1a9df5cb07'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Waliso', location = '{"lat":8.5506266,"lng":37.978662}'
WHERE id = '476c4346-72af-46a4-8812-061d7559b7b3'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Lalibela', location = '{"lat":12.0336643,"lng":39.043075}'
WHERE id = '47f95ece-6bd3-4f10-86c2-ec23c84f9926'::uuid;

UPDATE public.destinations
SET region = 'South West Ethiopia Peoples', location = '{"lat":6.9042595,"lng":36.7301591}'
WHERE id = '485613b9-5817-4d5f-8e67-f0f95cfae0cb'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bishoftu', location = '{"lat":8.7789777,"lng":39.0004021}'
WHERE id = '48ef3beb-3b8d-4a85-9d02-e43ae1e79718'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bishoftu', location = '{"lat":8.7789777,"lng":39.0004021}'
WHERE id = '48f3b44e-ce60-4376-b264-050d6878b633'::uuid;

UPDATE public.destinations
SET region = 'South West Ethiopia Peoples', location = '{"lat":6.9042595,"lng":36.7301591}'
WHERE id = '4931d41e-0978-44b1-89a7-aded8123d36a'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Gulale', location = '{"lat":9.0854496,"lng":38.7371907}'
WHERE id = '49b9c467-daf4-4470-ad3e-3ed399ca92ab'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Debre Damo Debir', location = '{"lat":14.373127,"lng":39.2893444}'
WHERE id = '49fcedab-896b-4062-8db7-a86d91f9a0ad'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Yayu', location = '{"lat":8.341488,"lng":35.8122397}'
WHERE id = '4a1713be-ebd6-407c-96e4-b0514633a89b'::uuid;

UPDATE public.destinations
SET region = 'Oromia', location = '{"lat":7.6120061,"lng":38.7629256}'
WHERE id = '4a5030e1-665a-42d1-b00c-c095b05303f9'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Bahir Dar Special Zone', location = '{"lat":11.5957145,"lng":37.3854336}'
WHERE id = '4adcf746-ed3e-4d53-9568-ab68b695f841'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Kindo Koysha', location = '{"lat":6.933691,"lng":37.5892615}'
WHERE id = '4b692dd0-c8ff-4df3-83c2-9363957996c9'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Karati', location = '{"lat":5.3406958,"lng":37.437323}'
WHERE id = '4b7540cd-04de-49c8-a934-85b6a34defd3'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Alamata', location = '{"lat":12.4175995,"lng":39.5603233}'
WHERE id = '4bff11c3-fc5c-469e-a5f3-a9b285dfbb58'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Bati', location = '{"lat":11.1916257,"lng":40.019752}'
WHERE id = '4c9fe140-927c-4fdf-8301-a7fb366fc135'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Halah Gheralta', location = '{"lat":13.7478418,"lng":39.2536119}'
WHERE id = '4ceb808b-976a-40f5-b0f2-93daa39c25dc'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', location = '{"lat":5.6321485,"lng":36.2621523}'
WHERE id = '4d06800d-f98c-4f2a-92de-745c3786ae78'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Lalibela', location = '{"lat":12.0336643,"lng":39.043075}'
WHERE id = '4d25831a-7b57-4283-bf5b-6797c4f8662d'::uuid;

UPDATE public.destinations
SET region = 'South West Ethiopia Peoples', city = 'Bonga', location = '{"lat":7.2645383,"lng":36.2460526}'
WHERE id = '4d417e6c-17d9-413d-a9aa-f3d33e67ef3f'::uuid;

UPDATE public.destinations
SET region = 'Oromia', location = '{"lat":6.7942161,"lng":39.7565574}'
WHERE id = '4d8ec07c-87b9-47e9-ba7f-d8a0e28f92a6'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Gorgora', location = '{"lat":12.2382669,"lng":37.2971393}'
WHERE id = '4daf0e94-014f-4160-a956-f18fee6a76ef'::uuid;

UPDATE public.destinations
SET region = 'Amhara', location = '{"lat":10.7117887,"lng":37.8435035}'
WHERE id = '4de67e02-d7f4-4d62-a977-ce8bd88cf56e'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos', location = '{"lat":9.0142532,"lng":38.7688899}'
WHERE id = '4e78943f-28e1-414b-a864-820fbc840274'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Adama', location = '{"lat":8.5503594,"lng":39.2820348}'
WHERE id = '4e8211cc-c753-48de-be2c-df2d1dce4c4e'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Metehara', location = '{"lat":8.904429,"lng":39.9175259}'
WHERE id = '4f23b0a1-f7a8-410e-85de-1332a3e39c4a'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Wukro', location = '{"lat":13.7862549,"lng":39.601525}'
WHERE id = '4f54474a-b86d-4ae8-866e-8f1bca0c07ba'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Hana - Margo Mursi Bodie', location = '{"lat":6.2235574,"lng":36.1284585}'
WHERE id = '4fb77500-dd7e-44ed-8b4f-f8c5cf634e47'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Dendi', location = '{"lat":8.9347933,"lng":38.1236741}'
WHERE id = '4fda1ee0-a2b2-480d-a349-178e572a6e89'::uuid;

COMMIT;
