-- Generated by scripts/enrich_destinations.py
-- Review destinations_enrichment_report.csv before applying.
BEGIN;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Lideta', location = '{"lat":9.00325,"lng":38.736569}'
WHERE id = '000b9cf0-b53f-4546-8840-ba364d586682'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Gorgora', location = '{"lat":12.2382669,"lng":37.2971393}'
WHERE id = '00294e3d-1208-4208-a015-996c71cf9738'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Gulale', location = '{"lat":9.076097,"lng":38.7555656}'
WHERE id = '0051e3e0-cdf6-4292-8b3f-55e0cf27bec7'::uuid;

UPDATE public.destinations
SET region = 'Afar', location = '{"lat":13.6030321,"lng":40.6634086}'
WHERE id = '00620588-4ca4-48fa-90d5-3eba0e18392b'::uuid;

UPDATE public.destinations
SET region = 'Benishangul-Gumuz', location = '{"lat":10.3778251,"lng":35.5084442}'
WHERE id = '007b0123-edb6-4112-8470-9c97d02e180a'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bedeno', location = '{"lat":9.1061245,"lng":41.6308668}'
WHERE id = '00e4f04e-be64-4f35-8e8f-41d59df6a948'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Jinka', location = '{"lat":5.786181,"lng":36.5654425}'
WHERE id = '0113fde5-2ea6-4aeb-965d-64901480d8c0'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Nefas Silk', location = '{"lat":8.9750399,"lng":38.7563673}'
WHERE id = '0172040d-afdc-49d2-a38e-f7c51cb36544'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Yeka', location = '{"lat":9.0371282,"lng":38.8398518}'
WHERE id = '01a955e4-eb2e-4586-9b0d-5ab3c563c175'::uuid;

UPDATE public.destinations
SET region = 'Amhara', location = '{"lat":10.3511111,"lng":39.7959722}'
WHERE id = '022c139e-027b-4c2b-b90f-103bdcf0f824'::uuid;

COMMIT;
