-- Generated by scripts/enrich_destinations.py
-- Review destinations_enrichment_report.csv before applying.
BEGIN;

UPDATE public.destinations
SET images = ARRAY['https://dotjlikaurcjwabarqcy.supabase.co/storage/v1/object/public/destinations/gorgora-northern-lake-tana-dock/cover.webp']::text[]
WHERE id = '00294e3d-1208-4208-a015-996c71cf9738'::uuid;

UPDATE public.destinations
SET images = ARRAY['https://dotjlikaurcjwabarqcy.supabase.co/storage/v1/object/public/destinations/erta-ale-active-volcano-lava-hazards-field/cover.webp']::text[]
WHERE id = '00620588-4ca4-48fa-90d5-3eba0e18392b'::uuid;

UPDATE public.destinations
SET images = ARRAY['https://dotjlikaurcjwabarqcy.supabase.co/storage/v1/object/public/destinations/bishoftu-town-crater-lake-city-circuit/cover.webp']::text[]
WHERE id = '02327ceb-e29b-4d7e-8904-dd4c8f1c7944'::uuid;

UPDATE public.destinations
SET images = ARRAY['https://dotjlikaurcjwabarqcy.supabase.co/storage/v1/object/public/destinations/battlefield-of-dogali-memorial-monument/cover.webp']::text[]
WHERE id = '032ca2c4-2e8c-4a0f-9b3e-0df565405328'::uuid;

UPDATE public.destinations
SET images = ARRAY['https://dotjlikaurcjwabarqcy.supabase.co/storage/v1/object/public/destinations/chebera-churchura-national-park/cover.webp']::text[]
WHERE id = '03b49d09-289b-46f3-a0a6-911ce7e8b65c'::uuid;

UPDATE public.destinations
SET images = ARRAY['https://dotjlikaurcjwabarqcy.supabase.co/storage/v1/object/public/destinations/chencha-dorze-public-bamboo-trail/cover.webp']::text[]
WHERE id = '04ea15b4-829e-4e66-9db0-208eb90ce212'::uuid;

UPDATE public.destinations
SET images = ARRAY['https://dotjlikaurcjwabarqcy.supabase.co/storage/v1/object/public/destinations/jan-meda-public-park/cover.webp']::text[]
WHERE id = '051f97af-5ce3-4bb0-853a-7c6ae6c5903b'::uuid;

UPDATE public.destinations
SET images = ARRAY['https://dotjlikaurcjwabarqcy.supabase.co/storage/v1/object/public/destinations/harari-rural-farming-outskirts/cover.webp']::text[]
WHERE id = '055d7202-aec8-4194-afdf-f775c86e4cd5'::uuid;

UPDATE public.destinations
SET images = ARRAY['https://dotjlikaurcjwabarqcy.supabase.co/storage/v1/object/public/destinations/wolayta-sodo-cultural-handicrafts-center/cover.webp']::text[]
WHERE id = '06f6cccf-3b0c-4514-aac1-11d5c4531468'::uuid;

UPDATE public.destinations
SET images = ARRAY['https://dotjlikaurcjwabarqcy.supabase.co/storage/v1/object/public/destinations/dallol-sulfur-springs/cover.webp']::text[]
WHERE id = '08e88666-1276-403b-972c-a82a3cedd23e'::uuid;

UPDATE public.destinations
SET images = ARRAY['https://dotjlikaurcjwabarqcy.supabase.co/storage/v1/object/public/destinations/lalibela-rock-hewn-churches-bete-giyorgis-etc/cover.webp']::text[]
WHERE id = '09c323bd-9d34-4fda-ac2f-15bce647102c'::uuid;

UPDATE public.destinations
SET images = ARRAY['https://dotjlikaurcjwabarqcy.supabase.co/storage/v1/object/public/destinations/wolayta-sodo-urban-center/cover.webp']::text[]
WHERE id = '09e458fc-9121-48c5-ab82-0a2d127ef57a'::uuid;

UPDATE public.destinations
SET images = ARRAY['https://dotjlikaurcjwabarqcy.supabase.co/storage/v1/object/public/destinations/lake-ashenge-boating-shore/cover.webp']::text[]
WHERE id = '0b82fd83-fb1a-48cb-b8f4-141efbd9cac2'::uuid;

UPDATE public.destinations
SET images = ARRAY['https://dotjlikaurcjwabarqcy.supabase.co/storage/v1/object/public/destinations/tekeze-dam-lake-boating-fishing-dock/cover.webp']::text[]
WHERE id = '0c0a0214-76e4-480e-8291-7d97965501da'::uuid;

UPDATE public.destinations
SET images = ARRAY['https://dotjlikaurcjwabarqcy.supabase.co/storage/v1/object/public/destinations/dirre-sheikh-hussein-pilgrims-village/cover.webp']::text[]
WHERE id = '0cc86c22-d3a7-48d9-ac1a-1478f842b8ff'::uuid;

UPDATE public.destinations
SET images = ARRAY['https://dotjlikaurcjwabarqcy.supabase.co/storage/v1/object/public/destinations/ethnological-museum/cover.webp']::text[]
WHERE id = '0d1058d2-0ac5-4f62-904a-86b77a783a9f'::uuid;

UPDATE public.destinations
SET images = ARRAY['https://dotjlikaurcjwabarqcy.supabase.co/storage/v1/object/public/destinations/addis-ababa-city-center-meskel-square-imperial-zones/cover.webp']::text[]
WHERE id = '0f49f40b-5d9b-48c8-900f-c01e75ff02c0'::uuid;

UPDATE public.destinations
SET images = ARRAY['https://dotjlikaurcjwabarqcy.supabase.co/storage/v1/object/public/destinations/lalibela-rock-churches/cover.webp']::text[]
WHERE id = '0f779742-b201-49c7-858f-d1eadb6516b3'::uuid;

UPDATE public.destinations
SET images = ARRAY['https://dotjlikaurcjwabarqcy.supabase.co/storage/v1/object/public/destinations/jinka-south-omo-health-education-volunteer-base/cover.webp']::text[]
WHERE id = '10428c4d-037c-4235-a04c-81eeedfcbb52'::uuid;

UPDATE public.destinations
SET images = ARRAY['https://dotjlikaurcjwabarqcy.supabase.co/storage/v1/object/public/destinations/bishoftu-lake-kilole-water-outpost/cover.webp']::text[]
WHERE id = '131993b4-a8b5-41cb-a8d1-5e2610dfd540'::uuid;

UPDATE public.destinations
SET images = ARRAY['https://dotjlikaurcjwabarqcy.supabase.co/storage/v1/object/public/destinations/abuna-yemata-guh-rock-climb/cover.webp']::text[]
WHERE id = '13e068c7-3d20-4a4e-b74b-3b403ab237a2'::uuid;

UPDATE public.destinations
SET images = ARRAY['https://dotjlikaurcjwabarqcy.supabase.co/storage/v1/object/public/destinations/haile-resort-hawassa-private-boat-pier/cover.webp']::text[]
WHERE id = '16c62e77-ebbe-46f9-ac95-2a3784f4b47b'::uuid;

UPDATE public.destinations
SET images = ARRAY['https://dotjlikaurcjwabarqcy.supabase.co/storage/v1/object/public/destinations/yaya-africa-athletics-village/cover.webp']::text[]
WHERE id = '1776863c-a67a-47a1-a39b-1ff5f28972a2'::uuid;

UPDATE public.destinations
SET images = ARRAY['https://dotjlikaurcjwabarqcy.supabase.co/storage/v1/object/public/destinations/dil-chora-hospital/cover.webp']::text[]
WHERE id = '17cdd081-8692-4079-ad33-6a5c3db45ad7'::uuid;

UPDATE public.destinations
SET images = ARRAY['https://dotjlikaurcjwabarqcy.supabase.co/storage/v1/object/public/destinations/key-afer-market/cover.webp']::text[]
WHERE id = '184162e1-10f4-47c4-8df2-43e9baef7374'::uuid;

UPDATE public.destinations
SET images = ARRAY['https://dotjlikaurcjwabarqcy.supabase.co/storage/v1/object/public/destinations/dorze-elephant-shaped-bamboo-huts/cover.webp']::text[]
WHERE id = '1c3acc4f-bf27-4343-953d-1d0001863ed7'::uuid;

UPDATE public.destinations
SET images = ARRAY['https://dotjlikaurcjwabarqcy.supabase.co/storage/v1/object/public/destinations/jijiga-convention-cultural-center/cover.webp']::text[]
WHERE id = '1e0f8cff-e37b-4576-bfe4-7504166dd876'::uuid;

UPDATE public.destinations
SET images = ARRAY['https://dotjlikaurcjwabarqcy.supabase.co/storage/v1/object/public/destinations/bete-abba-libanos/cover.webp']::text[]
WHERE id = '2129a44b-cf85-453a-b73d-325d060210e1'::uuid;

UPDATE public.destinations
SET images = ARRAY['https://dotjlikaurcjwabarqcy.supabase.co/storage/v1/object/public/destinations/turmi-hamer-village-settlements/cover.webp']::text[]
WHERE id = '21bd35c9-3b3d-4cb7-b92e-6947621f5d16'::uuid;

UPDATE public.destinations
SET images = ARRAY['https://dotjlikaurcjwabarqcy.supabase.co/storage/v1/object/public/destinations/jamia-grand-mosque-of-harar/cover.webp']::text[]
WHERE id = '220cc188-0798-45da-a7d9-80c1885886e2'::uuid;

COMMIT;
