-- Generated by scripts/enrich_destinations.py
-- Review destinations_enrichment_report.csv before applying.
BEGIN;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Lideta', location = '{"lat":9.0116517,"lng":38.7385122}'
WHERE id = '6c883b0e-b8db-4e9d-9c62-90df9053b424'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos', location = '{"lat":8.9993889,"lng":38.743291}'
WHERE id = '6cc5e8b1-b605-44b5-b5df-68bc84b67610'::uuid;

COMMIT;
