-- Generated by scripts/enrich_destinations.py
-- Review destinations_enrichment_report.csv before applying.
BEGIN;

UPDATE public.destinations
SET region = 'Oromia', location = '{"lat":8.5396564,"lng":38.8539547}'
WHERE id = '50ddc07c-4b8b-444d-98e5-fd3e873baa73'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bishoftu', location = '{"lat":8.7873711,"lng":38.9931534}'
WHERE id = '50e621f5-c06b-44ca-a149-a7047ffeea6d'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos', location = '{"lat":9.0100868,"lng":38.7640678}'
WHERE id = '5145d237-df84-4487-8305-8d963ab90df2'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ababa', location = '{"lat":9.0308012,"lng":38.7664911}'
WHERE id = '5197bc40-3281-43da-a673-f9d748b3a586'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Menagesha', location = '{"lat":9.0543794,"lng":38.5707238}'
WHERE id = '5260d359-4f38-44d1-a730-141993657869'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Gonder', location = '{"lat":12.614713,"lng":37.4739339}'
WHERE id = '5285c71e-fbab-44fb-8c0b-df9520888f65'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole', location = '{"lat":8.9869542,"lng":38.7890925}'
WHERE id = '533d6499-29f2-4de3-9375-9a2232e06abb'::uuid;

UPDATE public.destinations
SET region = 'Gambela', city = 'Gambela', location = '{"lat":8.2503656,"lng":34.5877344}'
WHERE id = '53565fc0-504d-4912-8f79-a41d123b49e3'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos', location = '{"lat":9.013432,"lng":38.7497422}'
WHERE id = '53988fe3-e258-428d-bcb5-366604c5762f'::uuid;

UPDATE public.destinations
SET region = 'South West Ethiopia Peoples', city = 'Wushwush', location = '{"lat":7.3004291,"lng":36.1404862}'
WHERE id = '544f41b1-1430-4fff-8ef4-40d0d52eb250'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', location = '{"lat":5.25,"lng":37.5}'
WHERE id = '5482603e-a19e-4002-a832-caa4c20f30dd'::uuid;

UPDATE public.destinations
SET region = 'Amhara', location = '{"lat":11.8635159,"lng":37.4908505}'
WHERE id = '55985669-8d33-4e70-a8ea-d3b3e84ff753'::uuid;

UPDATE public.destinations
SET region = 'Amhara', location = '{"lat":10.7117887,"lng":37.8435035}'
WHERE id = '55aeb54e-5a5b-4a6e-b112-ab8094f3aa0b'::uuid;

UPDATE public.destinations
SET region = 'Dire Dawa', city = 'Dire Dawa', location = '{"lat":9.5913368,"lng":41.8566126}'
WHERE id = '55b9b254-f1fd-456e-a05d-2702e5572b6a'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Ambo', location = '{"lat":8.982104,"lng":37.8554406}'
WHERE id = '56197ab1-f025-438b-823d-b61e32bcb951'::uuid;

UPDATE public.destinations
SET region = 'Oromia', location = '{"lat":7.6120061,"lng":38.7629256}'
WHERE id = '56eca6e1-7606-41a1-a5d2-8d2ad4bc5a6d'::uuid;

UPDATE public.destinations
SET region = 'Gambela', city = 'Gambela', location = '{"lat":8.2503656,"lng":34.5877344}'
WHERE id = '5720d8cb-f001-4f0b-96e1-4ae770b401c2'::uuid;

UPDATE public.destinations
SET region = 'Afar', city = 'Asaita', location = '{"lat":11.5653325,"lng":41.4385892}'
WHERE id = '572d6693-ca59-48ac-aba4-e27bb9c81118'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Dessie', location = '{"lat":11.1174963,"lng":39.6323131}'
WHERE id = '578c7f27-0fb6-4ca7-b54d-38e90bfe3523'::uuid;

UPDATE public.destinations
SET region = 'Oromia', location = '{"lat":8.78333,"lng":38.71667}'
WHERE id = '57e4808b-c0a1-4cc9-9c0f-9c460fcd27e8'::uuid;

UPDATE public.destinations
SET region = 'Oromia', location = '{"lat":6.7942161,"lng":39.7565574}'
WHERE id = '586f7f47-569e-4a3f-829c-67ca7e1fd586'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Gore', location = '{"lat":8.1525979,"lng":35.5371154}'
WHERE id = '587ab765-3697-4af0-b745-81c5ab6f7a35'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Azezo', location = '{"lat":12.549068,"lng":37.4270406}'
WHERE id = '58f6d8f6-e173-4e85-a907-1ce03d4ad922'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Gazer', location = '{"lat":5.904078,"lng":36.5777252}'
WHERE id = '5940cd4e-3a83-494b-8cf1-380fbf95e168'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Shufune', location = '{"lat":9.1095594,"lng":38.7199762}'
WHERE id = '59546cd9-8e43-4fa1-bc6f-37733a3ff660'::uuid;

UPDATE public.destinations
SET region = 'Oromia', location = '{"lat":7.5390028,"lng":38.5223013}'
WHERE id = '5966f553-1ad7-4805-881a-59bae6f806bc'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos', location = '{"lat":9.0102054,"lng":38.7629294}'
WHERE id = '59792e0c-f972-415d-837d-85233b8743b9'::uuid;

UPDATE public.destinations
SET region = 'Sidama', city = 'Hawassa', location = '{"lat":7.0565734,"lng":38.5645095}'
WHERE id = '59c68638-dbde-4e61-a973-299a837d5f6c'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bishoftu', location = '{"lat":8.7436854,"lng":38.9894021}'
WHERE id = '59f277fd-ccc1-42d3-85e8-bfdd2a6b84a7'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Bahir Dar Special Zone', location = '{"lat":11.6030239,"lng":37.3797987}'
WHERE id = '59f75b6a-4179-438d-991e-2d70f1d18986'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Halah Gheralta', location = '{"lat":13.7478418,"lng":39.2536119}'
WHERE id = '5a25aa6b-7149-4646-8a59-9ac0eed9487a'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos', location = '{"lat":9.0161492,"lng":38.76822}'
WHERE id = '5a434d8d-bb0d-4a1a-822f-bf98fc0f4246'::uuid;

UPDATE public.destinations
SET region = 'Sidama', city = 'Hawassa', location = '{"lat":7.040469,"lng":38.4945612}'
WHERE id = '5a72b83b-fa8c-43fa-9f07-7300ee34b739'::uuid;

UPDATE public.destinations
SET region = 'Amhara', location = '{"lat":10.7117887,"lng":37.8435035}'
WHERE id = '5aa3e09e-81dc-4910-b241-f68432ff254b'::uuid;

UPDATE public.destinations
SET region = 'Afar', location = '{"lat":12.29583,"lng":42.22806}'
WHERE id = '5afedf5a-519c-499c-a3b0-53185c958ccb'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ababa', location = '{"lat":9.0260054,"lng":38.7507566}'
WHERE id = '5b0361dc-661a-4ae1-a57e-e93a5acd26f6'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Lalibela', location = '{"lat":12.0360639,"lng":39.0456845}'
WHERE id = '5b7175e4-cfe8-4397-8cf1-2ea8bb24b75d'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Gore', location = '{"lat":8.1525979,"lng":35.5371154}'
WHERE id = '5b72bbaf-e3b4-4fdd-9030-e3789d6bf325'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Arsi Negelle', location = '{"lat":7.5919956,"lng":38.6913141}'
WHERE id = '5ba0ed28-8146-49bb-91e3-6c4ffcb2f7a5'::uuid;

UPDATE public.destinations
SET region = 'Sidama', city = 'Harabet Shumba', location = '{"lat":7.1010154,"lng":38.6270522}'
WHERE id = '5c3a2ca1-79d1-42ad-baf7-a3b1f7f236f0'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Yeka', location = '{"lat":9.0225064,"lng":38.7820276}'
WHERE id = '5c457c35-9ab5-49f4-b88c-ff5b7e8c3e5a'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole', location = '{"lat":9.0002179,"lng":38.7833921}'
WHERE id = '5c90954b-462e-4e2f-a9fd-b86ec5e2163c'::uuid;

UPDATE public.destinations
SET region = 'Sidama', city = 'Aleta Wendo', location = '{"lat":6.6046692,"lng":38.4247871}'
WHERE id = '5ce73a7a-e2ac-49d5-9da3-5018cec93d5a'::uuid;

UPDATE public.destinations
SET region = 'Sidama', city = 'Hawassa', location = '{"lat":7.0481029,"lng":38.47861}'
WHERE id = '5cfef0c4-85fe-4fa3-9530-c03a23960fc0'::uuid;

UPDATE public.destinations
SET region = 'South West Ethiopia Peoples', city = 'Bonga', location = '{"lat":7.2645383,"lng":36.2460526}'
WHERE id = '5e085177-a180-4369-9013-db829885227b'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Tiya', location = '{"lat":8.437331,"lng":38.609296}'
WHERE id = '5e99d589-9e8a-493d-b5ef-6df29399b119'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bishoftu', location = '{"lat":8.7789777,"lng":39.0004021}'
WHERE id = '5ecb6b6c-0ecc-49ff-bc02-c7a199ca385f'::uuid;

UPDATE public.destinations
SET region = 'Sidama', city = 'Hawassa', location = '{"lat":7.0476368,"lng":38.4682618}'
WHERE id = '5ed8b317-4fc5-42f6-8b0b-47f20d9f885f'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Arsi Negelle', location = '{"lat":7.5284208,"lng":38.6680653}'
WHERE id = '5f4a7e8f-0983-4b84-a80c-ab65cf708ee1'::uuid;

UPDATE public.destinations
SET region = 'Amhara', location = '{"lat":10.7117887,"lng":37.8435035}'
WHERE id = '5f5585e6-4710-44c9-8369-baa9e4fdcf27'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Sodere', location = '{"lat":8.4034494,"lng":39.3869748}'
WHERE id = '5f6baf9d-b2f5-4411-a8a8-e9bbe4537813'::uuid;

UPDATE public.destinations
SET region = 'Amhara', location = '{"lat":11.5245732,"lng":39.3529106}'
WHERE id = '5fa1edbf-7d4f-45ab-b6dc-5a2e5ee4a93c'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bishoftu', location = '{"lat":8.750004,"lng":38.981734}'
WHERE id = '607b3912-f39b-43d7-845e-2d0e789df856'::uuid;

UPDATE public.destinations
SET region = 'Oromia', location = '{"lat":7.6120061,"lng":38.7629256}'
WHERE id = '613a9429-d256-4600-870e-cd8b1b384c56'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bale', location = '{"lat":7.7308591,"lng":39.9998827}'
WHERE id = '61a22afe-fc57-46a4-8499-721b658c1226'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Omorate', location = '{"lat":4.8032381,"lng":36.0504375}'
WHERE id = '61aa18b2-7477-4373-91a4-8e03656b2c67'::uuid;

UPDATE public.destinations
SET region = 'Oromia', location = '{"lat":8.5396564,"lng":38.8539547}'
WHERE id = '6224fdbb-385c-4de0-87b1-89ae8b3c8c8d'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos', location = '{"lat":9.0185621,"lng":38.7562463}'
WHERE id = '6239e48b-37ce-42eb-8bae-5ce1207783b3'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos', location = '{"lat":9.0133925,"lng":38.756404}'
WHERE id = '62783716-55b7-4691-bf65-0167086218a7'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Bati', location = '{"lat":11.1916257,"lng":40.019752}'
WHERE id = '6322f9a2-20ad-44ab-bc7d-e02bc2e22363'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Sululta', location = '{"lat":9.2893858,"lng":38.8135595}'
WHERE id = '6337dd00-4575-4a82-8f29-f015ca6e16c0'::uuid;

UPDATE public.destinations
SET region = 'Amhara', location = '{"lat":11.9507719,"lng":37.294878}'
WHERE id = '634b65cc-17fe-48ab-b8d8-769b46401d23'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Dorze', location = '{"lat":6.1948568,"lng":37.5743447}'
WHERE id = '635a2e98-c03d-4730-9b5e-f29aee1f543d'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Gonder', location = '{"lat":12.610368,"lng":37.466766}'
WHERE id = '63bae99e-dce2-4a53-85d5-d5219e965a4b'::uuid;

COMMIT;
