-- Generated by scripts/enrich_destinations.py
-- Review destinations_enrichment_report.csv before applying.
BEGIN;

UPDATE public.destinations
SET location = '{"lat":8.7948903,"lng":37.8910436}'
WHERE id = '3d7f1f98-a03c-465a-9e6d-acae80b5b970'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Lalibela', location = '{"lat":12.0314601,"lng":39.0456552}'
WHERE id = '41f01f10-f08d-442d-aa98-4a0dfa4e2980'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Axum', location = '{"lat":14.1295237,"lng":38.7193084}'
WHERE id = '4500b86d-33a7-4a4d-8621-2aead50e48fe'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ketema', location = '{"lat":9.0327612,"lng":38.7408349}'
WHERE id = '473e2c3c-a89f-464b-9539-cc1a9df5cb07'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Debre Damo Debir', location = '{"lat":14.373127,"lng":39.2893444}'
WHERE id = '49fcedab-896b-4062-8db7-a86d91f9a0ad'::uuid;

COMMIT;
