-- Auto-generated by scripts/fill_missing_regions.js
-- Generated: 2026-08-01T02:48:09.125Z
-- Resolved: 638 destinations
-- Unresolved: 0 destinations

BEGIN;

UPDATE public.destinations
SET city = 'Dallol'
WHERE id = '00620588-4ca4-48fa-90d5-3eba0e18392b'::uuid;

UPDATE public.destinations
SET region = 'Benishangul-Gumuz', city = 'Assosa'
WHERE id = '007b0123-edb6-4112-8470-9c97d02e180a'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Jinka'
WHERE id = '0113fde5-2ea6-4aeb-965d-64901480d8c0'::uuid;

UPDATE public.destinations
SET region = 'Benishangul-Gumuz', city = 'Assosa'
WHERE id = '0172040d-afdc-49d2-a38e-f7c51cb36544'::uuid;

UPDATE public.destinations
SET city = 'North Shewa'
WHERE id = '022c139e-027b-4c2b-b90f-103bdcf0f824'::uuid;

UPDATE public.destinations
SET region = 'Sidama', city = 'Wondo Genet'
WHERE id = '0255ec62-2fd1-40be-ac57-209276df35e9'::uuid;

UPDATE public.destinations
SET region = 'South West Ethiopia Peoples', city = 'Masha'
WHERE id = '02c8223e-334d-47e5-b354-7fca28aada4f'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Dessie'
WHERE id = '032ca2c4-2e8c-4a0f-9b3e-0df565405328'::uuid;

UPDATE public.destinations
SET region = 'South West Ethiopia Peoples', city = 'Mizan Aman'
WHERE id = '037f40de-3fe9-4a23-9b9e-bf17b49de895'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos'
WHERE id = '0383471e-05bb-422a-872c-430f3ecf90b0'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos'
WHERE id = '039c265c-7824-4623-8e6a-455de2877896'::uuid;

UPDATE public.destinations
SET city = 'Bonga'
WHERE id = '03b49d09-289b-46f3-a0a6-911ce7e8b65c'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos'
WHERE id = '03fdc7fc-8467-46cf-a763-6e088fde3e14'::uuid;

UPDATE public.destinations
SET region = 'South West Ethiopia Peoples', city = 'Mizan Aman'
WHERE id = '03fee98a-a4f1-406e-ac0b-2db9aa5a2915'::uuid;

UPDATE public.destinations
SET city = 'Durame'
WHERE id = '04c8c45f-4738-457f-bf20-218105ff3170'::uuid;

UPDATE public.destinations
SET region = 'Harar', city = 'Harar'
WHERE id = '055d7202-aec8-4194-afdf-f775c86e4cd5'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bale'
WHERE id = '0601c42b-9a91-41fe-a460-4708f4d35127'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos'
WHERE id = '0621462d-39b6-421d-93c2-36425fc9ba8c'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Mek''elē'
WHERE id = '06692b34-d8e7-4a29-bf58-74a899324989'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Sawla'
WHERE id = '06929243-25f5-4b7f-818e-6770c4fd6500'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bishoftu'
WHERE id = '06e8bf00-f0ca-4393-b9a2-c04eb25fb2bc'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos'
WHERE id = '0719dd1e-6986-49b7-b092-400e2548dfc5'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bekoji'
WHERE id = '07384a8f-5e47-43e5-af76-0ed738a4f7f6'::uuid;

UPDATE public.destinations
SET city = 'Semera'
WHERE id = '07732b82-a311-40cc-b641-f0118bb25bce'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Injibara'
WHERE id = '079c543b-0632-403a-a752-7f7b63cd0037'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Debre Markos'
WHERE id = '07e3c3e0-9588-41e5-a2b6-5865142da6e2'::uuid;

UPDATE public.destinations
SET city = 'Dallol'
WHERE id = '08e88666-1276-403b-972c-a82a3cedd23e'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Metu'
WHERE id = '098a3ef4-e0f9-4680-a0a3-531cd2363b7c'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Shakiso'
WHERE id = '09cf80ad-8f11-4213-860c-c391cac7c1e4'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Kindo Koysha'
WHERE id = '0a20e07d-73dd-4284-ae5b-b631cc2cc559'::uuid;

UPDATE public.destinations
SET city = 'Bahir Dar Special Zone'
WHERE id = '0a2a2811-9f5b-4f9a-8074-5e180fd06d45'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ketema'
WHERE id = '0a56edc3-e173-4766-863d-d602923659eb'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Jinka'
WHERE id = '0a85ecd4-5c50-4860-b012-f6780d7ed2d3'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ketema'
WHERE id = '0b323a29-7996-4f3d-b524-51210f902bdd'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bale'
WHERE id = '0bb81add-f212-4fa1-a84c-03ac54cb7b4e'::uuid;

UPDATE public.destinations
SET region = 'Harar', city = 'Harar'
WHERE id = '0beb83f4-243e-4161-8657-8f7ce8b4d268'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Wenchi'
WHERE id = '0bfc7ee8-ddd1-4b35-baa9-543a2a227862'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Tekeze'
WHERE id = '0c0a0214-76e4-480e-8291-7d97965501da'::uuid;

UPDATE public.destinations
SET city = 'Bishoftu'
WHERE id = '0c0f9ce0-6896-4e41-a1fa-d5e3c229b28a'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Sheik Hussein'
WHERE id = '0cc86c22-d3a7-48d9-ac1a-1478f842b8ff'::uuid;

UPDATE public.destinations
SET region = 'South West Ethiopia Peoples', city = 'Bonga'
WHERE id = '0d291d6c-0210-408b-87a8-fbc919f72dc5'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Tekeze'
WHERE id = '0db2f2ba-292b-4bfd-a534-f3bbcf855467'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Awash'
WHERE id = '0e43bad9-7f39-4795-be9d-01fd987acf85'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bishoftu'
WHERE id = '0e4d4519-15ac-4164-95ff-67610eea618a'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Debre Markos'
WHERE id = '0f2b4014-1411-4d39-9d1f-ab7c9840a894'::uuid;

UPDATE public.destinations
SET city = 'Yeha'
WHERE id = '0f3ec61a-c1a4-4baf-bfdc-6913b4805a5c'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ababa'
WHERE id = '0f7c84bd-4645-4e2b-b0c8-c603b9a940b1'::uuid;

UPDATE public.destinations
SET region = 'Central Ethiopia Regional State', city = 'Worabe'
WHERE id = '0fa2359e-59e0-4cb3-867c-b289e8e9a009'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Jinka'
WHERE id = '10428c4d-037c-4235-a04c-81eeedfcbb52'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Gulale'
WHERE id = '1083c39b-85cc-457d-9a68-518fe138f7be'::uuid;

UPDATE public.destinations
SET region = 'Afar', city = 'Semera'
WHERE id = '10995a8c-f549-4261-9251-3c7e872b92b8'::uuid;

UPDATE public.destinations
SET city = 'Teppi'
WHERE id = '10aad439-21ab-49ae-bad6-cd8d0e02d12f'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Gulale'
WHERE id = '10c92854-678b-4c37-9275-8d10f798aa6d'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bishoftu'
WHERE id = '131993b4-a8b5-41cb-a8d1-5e2610dfd540'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Metu'
WHERE id = '133d233e-e6d0-4a8e-803a-7a7b8b5bde07'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Halah Gheralta'
WHERE id = '13e068c7-3d20-4a4e-b74b-3b403ab237a2'::uuid;

UPDATE public.destinations
SET region = 'Afar', city = 'Semera'
WHERE id = '14dcdb3b-f234-4f0e-9ddb-270c10ebcc13'::uuid;

UPDATE public.destinations
SET city = 'Bonga'
WHERE id = '151689f0-1345-4c94-8b5e-4cf3b59dfae8'::uuid;

UPDATE public.destinations
SET city = 'Bishoftu'
WHERE id = '155560ee-ef59-4e8f-9b0a-da01cfb2db33'::uuid;

UPDATE public.destinations
SET region = 'Sidama', city = 'Hawassa'
WHERE id = '15d4cc48-4db3-4cbb-91c9-c60fa8b4dc57'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'North Shewa'
WHERE id = '15f2bcde-0809-406f-8919-09b8f795e41a'::uuid;

UPDATE public.destinations
SET city = 'Jijiga'
WHERE id = '1618e41c-dd41-468c-bc4d-eb68f0980534'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos'
WHERE id = '16b17298-cf95-44da-b6a5-4c1bce95c425'::uuid;

UPDATE public.destinations
SET city = 'North Shewa'
WHERE id = '171119ef-dd22-425f-93bc-654ef09a656a'::uuid;

UPDATE public.destinations
SET region = 'Central Ethiopia Regional State', city = 'Worabe'
WHERE id = '17182a01-db5e-4920-b6bb-5927b96a2ccb'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bishoftu'
WHERE id = '17520cea-bed8-4aa0-b020-30e597001408'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ababa'
WHERE id = '1780d35c-2488-4b5e-b3ae-042a32f6c0b7'::uuid;

UPDATE public.destinations
SET region = 'Dire Dawa', city = 'Dire Dawa'
WHERE id = '17cdd081-8692-4079-ad33-6a5c3db45ad7'::uuid;

UPDATE public.destinations
SET region = 'South West Ethiopia Peoples', city = 'Bonga'
WHERE id = '18d1a00d-e89d-4c2a-81e3-727d2f2c2196'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Debre Markos'
WHERE id = '1911def4-e997-465b-a0a3-6d9d84380461'::uuid;

UPDATE public.destinations
SET region = 'Harar', city = 'Harar'
WHERE id = '1a1c5e1b-dafa-4c16-b381-623fbaa66752'::uuid;

UPDATE public.destinations
SET city = 'Semera'
WHERE id = '1a3def45-0960-4282-bebd-627a7cb980c4'::uuid;

UPDATE public.destinations
SET region = 'Harar', city = 'Harar'
WHERE id = '1a5b3dff-4d10-4581-8c58-b2c5f9aec1f4'::uuid;

UPDATE public.destinations
SET city = 'Konso'
WHERE id = '1b0dae3c-22ba-4e5d-ba89-22160801cca4'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Awash'
WHERE id = '1cf5758b-28cb-430a-b66a-8d238d4d8bb5'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'North Shewa'
WHERE id = '1d914cd7-3a4f-4b25-ac05-35aae3470100'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Wolaita Sodo'
WHERE id = '1e396328-3fdf-40f1-b7dd-41362f74ef63'::uuid;

UPDATE public.destinations
SET city = 'North Shewa'
WHERE id = '1e95d4ee-0a3f-4595-98b3-9e7949a572cf'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Kombolcha'
WHERE id = '1e9cbc26-1c66-4df8-a395-3ce61bb60b65'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Yirga Cheffe'
WHERE id = '1ed00cb8-cefc-4d4f-be7b-e45568710d02'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Debre Libanos'
WHERE id = '1ed24426-c2c9-4515-8ff8-f7200e264835'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Sawla'
WHERE id = '1ee1842e-065b-46cc-972f-8d9d45d54b92'::uuid;

UPDATE public.destinations
SET city = 'Dessie'
WHERE id = '1f001180-7b6a-4c63-80ea-2d8f6aa0fdfb'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Gondar'
WHERE id = '1f3e6ebe-2be1-4614-82f1-e2f837b3d3d7'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Debre Damo'
WHERE id = '1f69a209-ecd9-4cd9-9188-57c315e4f2be'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole'
WHERE id = '1fafd623-6c4d-41bb-a79b-8b5bd35127d9'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Injibara'
WHERE id = '1ff14e7b-bfb6-444f-9af4-b1073a2631d3'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'East Shewa'
WHERE id = '200f2932-52b1-430f-87fa-ef56ba6bee1d'::uuid;

UPDATE public.destinations
SET region = 'Benishangul-Gumuz', city = 'Assosa'
WHERE id = '2022c34b-b7e3-4236-81e3-d04af7a3d038'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Dinsho'
WHERE id = '207de875-a9dc-412b-8054-964c5edc08b7'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Asella'
WHERE id = '21d9b8a0-7f58-4f22-96b8-78e242ae990c'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Debre Markos'
WHERE id = '2272a61f-9359-4e0c-a986-2026a826d363'::uuid;

UPDATE public.destinations
SET city = 'Debark'
WHERE id = '23226a89-46e7-4984-99ee-5cc67e1cc906'::uuid;

UPDATE public.destinations
SET city = 'Hawassa'
WHERE id = '24028b03-8409-4402-9702-50e66d44c031'::uuid;

UPDATE public.destinations
SET city = 'Shashemene'
WHERE id = '24d6e6ee-90b9-49d3-9b43-ac8fa2d59587'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Jinka'
WHERE id = '26cfc331-c3b9-4089-a0ed-b629bbd081d6'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Metehara'
WHERE id = '28b06163-a019-4ec8-806d-dc45aba5595f'::uuid;

UPDATE public.destinations
SET city = 'Debre Markos'
WHERE id = '2b3cc33e-44bc-40f6-91a3-2b03e30b882b'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Haromaya'
WHERE id = '2cdc89c9-ccae-4a4a-a328-41dcfe7efd2e'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bishoftu'
WHERE id = '2dd76ae5-d856-4946-83ab-85a9bd32a9d3'::uuid;

UPDATE public.destinations
SET region = 'Gambela', city = 'Gambela'
WHERE id = '2de90c71-ca60-4d2b-be4b-22ab54f37a93'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos'
WHERE id = '2e8a6a51-a57c-43f3-8cd8-49f38b7bb164'::uuid;

UPDATE public.destinations
SET region = 'Benishangul-Gumuz', city = 'Assosa'
WHERE id = '3096f7ab-0a87-42fa-ba55-98282bb96595'::uuid;

UPDATE public.destinations
SET region = 'Central Ethiopia Regional State', city = 'Hosaina'
WHERE id = '31b2466f-8630-4b81-8717-2af3da7822c3'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Wolaita Sodo'
WHERE id = '31fb5ee6-550b-44b9-a935-eb136e4db8ab'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Awash'
WHERE id = '3286a788-e2b1-4bec-a5ea-c32b752fe610'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Yabēlo'
WHERE id = '32ee3318-b222-4de7-b1e2-ff8a62cd2dfa'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Gulale'
WHERE id = '3307136d-33b9-46d1-a85d-329b832ef1fa'::uuid;

UPDATE public.destinations
SET region = 'Afar', city = 'Semera'
WHERE id = '3337e9f7-776d-43c5-8f15-ea2a1ad159cd'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Wenchi'
WHERE id = '3393d169-bb0a-4fca-9812-109036f62ad4'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Adama'
WHERE id = '353a512f-270c-49f3-8a0b-a72199f59027'::uuid;

UPDATE public.destinations
SET region = 'South West Ethiopia Peoples', city = 'Mizan Aman'
WHERE id = '357cf054-8b96-4b60-90fd-26a6517404a0'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Gondar'
WHERE id = '35f47335-8797-403c-84b7-4d773d3255ae'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Kindo Koysha'
WHERE id = '3672280d-719b-4f45-a075-330c2a8e2814'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bishoftu'
WHERE id = '37a12e87-515b-44fa-a6a8-d7989b4017e4'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Jinka'
WHERE id = '37babb65-974f-4586-a52c-06cc4ffd339d'::uuid;

UPDATE public.destinations
SET region = 'South West Ethiopia Peoples', city = 'Bonga'
WHERE id = '3950d41d-cf77-437e-ace5-3f6d1a7491a3'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Mek''elē'
WHERE id = '39afddda-e645-44b2-86b1-e2e9ab09e2c9'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Jimma'
WHERE id = '3a215d89-fea3-4dbe-955f-0f36787befa8'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Gulale'
WHERE id = '3abb2bc8-cd5e-4567-8459-71ea7cba5b36'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Yeka'
WHERE id = '3be3419a-6f26-4fe8-a36f-234e728ea785'::uuid;

UPDATE public.destinations
SET region = 'Benishangul-Gumuz', city = 'Assosa'
WHERE id = '3bf44e2f-bffc-4e61-96af-1b6c31f2963c'::uuid;

UPDATE public.destinations
SET region = 'Afar', city = 'Semera'
WHERE id = '3d634d41-af7e-40c2-8ed2-4a56559fc7a2'::uuid;

UPDATE public.destinations
SET city = 'Debark'
WHERE id = '3d816d2c-3881-4ed4-a503-4601492b0a6a'::uuid;

UPDATE public.destinations
SET city = 'Bahir Dar Special Zone'
WHERE id = '3da4a265-b1fa-4350-84ef-ecc140ceece6'::uuid;

UPDATE public.destinations
SET city = 'Langano'
WHERE id = '3effdf2c-3399-434c-9c27-142f0e4b0899'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Adama'
WHERE id = '3f3b8afc-11fc-47e2-b1cf-3cab71138da8'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bishoftu'
WHERE id = '3f48658f-cee9-4fc1-be39-695f3040da45'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Gulale'
WHERE id = '3f866e65-8b6c-4b3d-be32-0b419e440ff1'::uuid;

UPDATE public.destinations
SET city = 'Dallol'
WHERE id = '3f8bde2a-5b1f-46a6-a08b-638ce57b9af3'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Gulale'
WHERE id = '430ea818-4176-4cc7-a307-47b499882d5a'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos'
WHERE id = '43700e13-9720-4983-9e6b-a1ce20eb9bfc'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Konso'
WHERE id = '43ab2358-38d7-4156-b8d1-f0749fec4dbe'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Adwa'
WHERE id = '44a8af1f-80b0-4a23-90db-f5272c52c1af'::uuid;

UPDATE public.destinations
SET city = 'Bonga'
WHERE id = '44c08981-cd9c-4a63-8534-8e0696b56e96'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Konso'
WHERE id = '45ccffd6-2de8-46d3-a9d0-b7e0b44398da'::uuid;

UPDATE public.destinations
SET city = 'Langano'
WHERE id = '4662ab4e-d913-456a-a9c1-b75341310441'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Langano'
WHERE id = '46e80005-808f-4339-b70a-f57de8e593c9'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Awash'
WHERE id = '46f3711b-bf97-4783-a645-73d6fbd8b7de'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Mek''elē'
WHERE id = '47a09f66-86ef-4853-9aee-e651001356d4'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos'
WHERE id = '47b0950a-dd1d-4a47-aad3-b274f128c1af'::uuid;

UPDATE public.destinations
SET city = 'Bonga'
WHERE id = '485613b9-5817-4d5f-8e67-f0f95cfae0cb'::uuid;

UPDATE public.destinations
SET region = 'Central Ethiopia Regional State', city = 'Worabe'
WHERE id = '4874523d-bc8a-4678-a3df-70bdfce3adda'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Yirga Cheffe'
WHERE id = '489c201a-ff25-4eea-9b27-0df71437394b'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Arba Minch'
WHERE id = '48dba260-8847-4357-a1d2-b853875fa23a'::uuid;

UPDATE public.destinations
SET city = 'Bonga'
WHERE id = '4931d41e-0978-44b1-89a7-aded8123d36a'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Dessie'
WHERE id = '4955807c-67c6-4cda-aa64-e9f28261921e'::uuid;

UPDATE public.destinations
SET region = 'Central Ethiopia Regional State', city = 'Welkite'
WHERE id = '49b32550-7e9e-4315-afcc-22c2d46e7319'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bishoftu'
WHERE id = '49c80e26-f7f6-4f1d-b254-cad1a2bc3655'::uuid;

UPDATE public.destinations
SET city = 'Langano'
WHERE id = '4a5030e1-665a-42d1-b00c-c095b05303f9'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos'
WHERE id = '4b1a2b03-b04c-4bb7-ab2c-6419329638f7'::uuid;

UPDATE public.destinations
SET city = 'Jinka'
WHERE id = '4d06800d-f98c-4f2a-92de-745c3786ae78'::uuid;

UPDATE public.destinations
SET city = 'Dinsho'
WHERE id = '4d8ec07c-87b9-47e9-ba7f-d8a0e28f92a6'::uuid;

UPDATE public.destinations
SET city = 'Debre Markos'
WHERE id = '4de67e02-d7f4-4d62-a977-ce8bd88cf56e'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Hayq'
WHERE id = '4e00ed19-fb66-4c84-9268-281d54ec1406'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Gulale'
WHERE id = '4f0debde-c9f8-447c-bd73-3354543ac950'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Bahir Dar Special Zone'
WHERE id = '4f1c8cc1-62b0-44b0-bd8c-6503ed6d7a21'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ketema'
WHERE id = '4ff4d3bb-8e6a-494c-be44-5c63eafb4869'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Axum'
WHERE id = '508b35ff-c7c5-42c2-8add-7ca23943c516'::uuid;

UPDATE public.destinations
SET city = 'Dendi'
WHERE id = '50ddc07c-4b8b-444d-98e5-fd3e873baa73'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ketema'
WHERE id = '50ec4e15-a707-45aa-81c8-cc3ef3910027'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Dessie'
WHERE id = '51071284-8440-4876-a880-f5b6ab994788'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Awash'
WHERE id = '51c2c3e9-5372-43ed-bc2f-17a4bbb78ceb'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Metu'
WHERE id = '52b26f43-475d-4d78-a552-facb4e03fabe'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Bahir Dar Special Zone'
WHERE id = '5379dcb1-0f39-45e7-bccb-7d4727f09d13'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'East Shewa'
WHERE id = '53e13fe6-dfd5-4af9-ba94-2903d804bc65'::uuid;

UPDATE public.destinations
SET city = 'Konso'
WHERE id = '5482603e-a19e-4002-a832-caa4c20f30dd'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ababa'
WHERE id = '551642cd-83d7-4a04-882e-552d4eb0fd80'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Yabēlo'
WHERE id = '55614d2f-89f1-4c71-b3b0-625ea64c59be'::uuid;

UPDATE public.destinations
SET city = 'Bahir Dar Special Zone'
WHERE id = '55985669-8d33-4e70-a8ea-d3b3e84ff753'::uuid;

UPDATE public.destinations
SET city = 'Debre Markos'
WHERE id = '55aeb54e-5a5b-4a6e-b112-ab8094f3aa0b'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Konso'
WHERE id = '55cde165-1a79-46e8-b8bd-2a72e3f479cc'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Wolaita Sodo'
WHERE id = '5601a0b7-c3cd-463b-b11e-d0920287401e'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Wenchi'
WHERE id = '565e2fbe-684e-4f62-b4b2-c8ffd04c72a0'::uuid;

UPDATE public.destinations
SET city = 'Langano'
WHERE id = '56eca6e1-7606-41a1-a5d2-8d2ad4bc5a6d'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Gulale'
WHERE id = '57562c1b-d9e1-4e20-9439-cd554caec184'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Wenchi'
WHERE id = '577f9abc-caa9-4db7-b2fb-85dd2235356a'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ketema'
WHERE id = '57a4df51-664e-4637-891c-27e6de3d0f8a'::uuid;

UPDATE public.destinations
SET city = 'Shashemene'
WHERE id = '57e4808b-c0a1-4cc9-9c0f-9c460fcd27e8'::uuid;

UPDATE public.destinations
SET city = 'Dinsho'
WHERE id = '586f7f47-569e-4a3f-829c-67ca7e1fd586'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Debre Markos'
WHERE id = '587ecae5-c03c-4241-b154-9f038e86b6e2'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Wenchi'
WHERE id = '58c9e3c6-5f2b-46e3-bdfd-247f27fd3f59'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Lalibela'
WHERE id = '58fc4ba3-40ba-4081-9b63-f06b6562c9f4'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos'
WHERE id = '59213d73-f699-4e9e-a7a7-2b7bacb38353'::uuid;

UPDATE public.destinations
SET city = 'Arsi Negelle'
WHERE id = '5966f553-1ad7-4805-881a-59bae6f806bc'::uuid;

UPDATE public.destinations
SET city = 'Debre Markos'
WHERE id = '5aa3e09e-81dc-4910-b241-f68432ff254b'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Adwa'
WHERE id = '5af1b662-3df1-4cba-9cb5-0a734f977119'::uuid;

UPDATE public.destinations
SET city = 'Awash'
WHERE id = '5afedf5a-519c-499c-a3b0-53185c958ccb'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Dendi'
WHERE id = '5cd06f1e-246b-45de-83c0-eb514220953d'::uuid;

UPDATE public.destinations
SET region = 'Sidama', city = 'Hawassa'
WHERE id = '5d921774-ceec-4ab6-a275-7690aeb0b27e'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos'
WHERE id = '5d9ef771-8180-47d4-a853-033b16c8afcc'::uuid;

UPDATE public.destinations
SET city = 'Debre Markos'
WHERE id = '5f5585e6-4710-44c9-8369-baa9e4fdcf27'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Arba Minch'
WHERE id = '5f9562e4-b3c9-4bf8-83d5-2fd9438b81d6'::uuid;

UPDATE public.destinations
SET city = 'Wollo'
WHERE id = '5fa1edbf-7d4f-45ab-b6dc-5a2e5ee4a93c'::uuid;

UPDATE public.destinations
SET region = 'Afar', city = 'Semera'
WHERE id = '602a0fe7-98e5-404f-bc7a-fc47fa238002'::uuid;

UPDATE public.destinations
SET city = 'Langano'
WHERE id = '613a9429-d256-4600-870e-cd8b1b384c56'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Wukro'
WHERE id = '6151ba43-5bd7-426d-b383-1c0829462d6a'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Adwa'
WHERE id = '61555a68-11c8-46fb-a17a-081fce0da812'::uuid;

UPDATE public.destinations
SET region = 'Benishangul-Gumuz', city = 'Assosa'
WHERE id = '616d3f0e-89e1-4a53-a515-bde34ae4850e'::uuid;

UPDATE public.destinations
SET city = 'Dendi'
WHERE id = '6224fdbb-385c-4de0-87b1-89ae8b3c8c8d'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Yeha'
WHERE id = '62526dc5-8e94-402f-8757-6fbde7a110b5'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ketema'
WHERE id = '6300931c-3ab6-41a6-a793-9355a0a6e2ee'::uuid;

UPDATE public.destinations
SET city = 'Bahir Dar Special Zone'
WHERE id = '634b65cc-17fe-48ab-b8d8-769b46401d23'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'East Shewa'
WHERE id = '63cb91a4-40f3-4d29-8826-9a9ccb44c13e'::uuid;

UPDATE public.destinations
SET region = 'Sidama', city = 'Hawassa'
WHERE id = '646cceb9-9b24-49e2-a445-d976da182723'::uuid;

UPDATE public.destinations
SET city = 'Tendaho'
WHERE id = '64d79049-824e-447d-9295-528cf0dc2f80'::uuid;

UPDATE public.destinations
SET city = 'Asaita'
WHERE id = '65fd1b83-514b-4f10-bac4-f4e88a03070d'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos'
WHERE id = '67381361-9a08-442c-9655-5cc9a90c8b21'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Awash'
WHERE id = '678d89b2-b8f0-4a2f-ad3d-21937a7c8736'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Gore'
WHERE id = '681816d7-79d7-42dc-86c0-e89153f648d1'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Dessie'
WHERE id = '68c81bcb-2cd5-4830-9433-6a3f16984144'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Omorate'
WHERE id = '6a0a01d1-4ae2-4473-9fc1-30f6ff672ace'::uuid;

UPDATE public.destinations
SET city = 'Debre Markos'
WHERE id = '6ad09a0a-e179-4659-9ef9-48f0f8842ff8'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Adwa'
WHERE id = '6af5fcaf-0f7a-422f-afb4-eb3c92075ab9'::uuid;

UPDATE public.destinations
SET city = 'Dallol'
WHERE id = '6b48558c-8f66-48e5-8256-390af4262692'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Gore'
WHERE id = '6b9a30c3-642e-4887-a787-4fe997a4c982'::uuid;

UPDATE public.destinations
SET region = 'Afar', city = 'Dallol'
WHERE id = '6beae27e-b640-4eab-8dc6-9cbe62a15b7b'::uuid;

UPDATE public.destinations
SET city = 'Jimma'
WHERE id = '6bfc2bf6-f880-4626-86b6-f40bbd334847'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'East Shewa'
WHERE id = '6ca8c5a6-0df2-4901-bb9d-bd3ddc8c1e40'::uuid;

UPDATE public.destinations
SET city = 'Debark'
WHERE id = '6ceaf39e-da7e-4e79-8097-f606b29cf7f6'::uuid;

UPDATE public.destinations
SET city = 'North Shewa'
WHERE id = '6d1ff157-30a7-4e30-a84b-3e6902657388'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Metehara'
WHERE id = '6e30a166-b1cf-4a6d-8ba8-b290c765f9c8'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Wolaita Sodo'
WHERE id = '6ed10846-8977-4147-8645-539cc1aa8ac0'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Axum'
WHERE id = '6ed137e6-b2fb-45de-a9cb-632d60b3e26e'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Yabēlo'
WHERE id = '6ee3278a-2bde-4a93-ad42-b5292b25b6f9'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Bahir Dar Special Zone'
WHERE id = '6eec3cd6-0847-4e46-979d-28b1aa86c20a'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Debre Tabor'
WHERE id = '70d891ea-fc2f-47a2-9747-c78f8fc3249a'::uuid;

UPDATE public.destinations
SET region = 'Central Ethiopia Regional State', city = 'Welkite'
WHERE id = '717107ce-f6a3-4b16-a798-5e52ff9e657c'::uuid;

UPDATE public.destinations
SET region = 'Harar', city = 'Harar'
WHERE id = '71853a5b-2c2e-416d-803e-b4bb670de0ac'::uuid;

UPDATE public.destinations
SET region = 'Central Ethiopia Regional State', city = 'Hosaina'
WHERE id = '72959167-72a6-43cf-af90-6344ccf7430c'::uuid;

UPDATE public.destinations
SET city = 'Arsi Negelle'
WHERE id = '72e9f520-f4ea-4bac-8419-6688f25a6966'::uuid;

UPDATE public.destinations
SET region = 'Somali', city = 'Jijiga'
WHERE id = '739a8b04-9360-4442-8326-c61ffe7de64f'::uuid;

UPDATE public.destinations
SET city = 'Arba Minch'
WHERE id = '73ac5648-8a44-493e-81ad-74bd712adc6f'::uuid;

UPDATE public.destinations
SET region = 'Afar', city = 'Semera'
WHERE id = '747633e2-2aaa-42a2-a116-d54d3b9aa7ad'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Gulale'
WHERE id = '75629099-8287-4f41-8c1b-fceb18999bf1'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Wenchi'
WHERE id = '758d3678-744c-4d4d-baaa-3160b2116e1b'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos'
WHERE id = '75ce2351-c396-401e-9d0d-7d041e2524c4'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Asella'
WHERE id = '76af50a0-f47f-40a6-85f9-379922cf2cbd'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Konso'
WHERE id = '7763645c-ba1d-43f1-9056-1945753f1978'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Debre Markos'
WHERE id = '77ce857f-7bfb-4c7c-be3e-e5794e34a3b0'::uuid;

UPDATE public.destinations
SET city = 'Debre Markos'
WHERE id = '77d50b88-c513-48e5-bd4b-5884529a42aa'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bishoftu'
WHERE id = '791fd2e8-d352-4ff4-be89-1f21f63ab7d2'::uuid;

UPDATE public.destinations
SET city = 'Debark'
WHERE id = '7978eafa-3e91-4915-ab4e-415ca2e10beb'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Wollo'
WHERE id = '79edb245-2330-4d30-a972-eb648227b2df'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Ankober'
WHERE id = '7a00111b-9a60-4113-8a08-3fec28046725'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Ambo'
WHERE id = '7a5e0fe6-3e60-4db5-8eff-b9547c1883fd'::uuid;

UPDATE public.destinations
SET region = 'South West Ethiopia Peoples', city = 'Bonga'
WHERE id = '7afecfb4-d229-4c76-9edd-ba490b0355ed'::uuid;

UPDATE public.destinations
SET region = 'Afar', city = 'Semera'
WHERE id = '7b23982e-4363-4a29-96c7-5b3f00898229'::uuid;

UPDATE public.destinations
SET city = 'Arba Minch'
WHERE id = '7bacf781-a26b-46a8-81e1-b12eeb816990'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Axum'
WHERE id = '7bcbed40-6495-4be9-aa57-c74b340efdbc'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole'
WHERE id = '7cd80dc4-e5d4-47a6-8b1b-cd4b8b4252b9'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Metehara'
WHERE id = '7cf3597a-13a5-40f2-abad-ed22febf9b77'::uuid;

UPDATE public.destinations
SET city = 'Debark'
WHERE id = '7d01281b-5acf-4850-90d2-74d00c1829cc'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Injibara'
WHERE id = '7db7e03a-a831-40a0-8d2f-d4e9b43af733'::uuid;

UPDATE public.destinations
SET region = 'South West Ethiopia Peoples', city = 'Bonga'
WHERE id = '7de8f2d0-cea7-417d-8616-bf91e2ed6c2b'::uuid;

UPDATE public.destinations
SET city = 'Shashemene'
WHERE id = '7f03a0a7-5543-4810-af24-c9738cd35f15'::uuid;

UPDATE public.destinations
SET city = 'Alatish'
WHERE id = '7f7941de-606d-41f2-9784-a581d6b3a775'::uuid;

UPDATE public.destinations
SET city = 'Bale'
WHERE id = '8009a153-ae22-4577-b206-fd7f5242770c'::uuid;

UPDATE public.destinations
SET region = 'Benishangul-Gumuz', city = 'Assosa'
WHERE id = '808ac17a-9ec9-46a4-b8bf-91d7a9709b08'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Mek''elē'
WHERE id = '80f516ce-6570-467e-b52d-b250909d14d8'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ababa'
WHERE id = '810c6f17-ed36-4bc7-bef4-9af0082f5de2'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Adwa'
WHERE id = '812db92e-8bc5-4ba1-aa6c-1f5a50495e53'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Nekemte'
WHERE id = '828adfee-2dac-4c07-bd30-e0f392ea439c'::uuid;

UPDATE public.destinations
SET city = 'Debark'
WHERE id = '82aba8b1-2db2-4e2d-a571-714d5afee55b'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ababa'
WHERE id = '83381113-88e0-4b99-a696-5429844cbeca'::uuid;

UPDATE public.destinations
SET city = 'Dallol'
WHERE id = '835093ea-45b9-4aa7-b2db-64933e21749b'::uuid;

UPDATE public.destinations
SET city = 'Asaita'
WHERE id = '83e79b66-f2d6-4aef-bc7b-78f8090042da'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Jinka'
WHERE id = '84cfd8ed-473b-42b3-9f1a-f106be9b0b5b'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Adama'
WHERE id = '86bfa076-8fe0-4906-9393-c7b532ed92bb'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ababa'
WHERE id = '870dbcdd-f0e1-4ca5-b549-02e9b9430349'::uuid;

UPDATE public.destinations
SET region = 'Sidama', city = 'Hawassa'
WHERE id = '8717e5d4-d053-438e-ab34-4f076e27b61f'::uuid;

UPDATE public.destinations
SET city = 'Konso'
WHERE id = '875b32ea-050c-4fd2-b883-749a03f6646d'::uuid;

UPDATE public.destinations
SET city = 'Sawla'
WHERE id = '87f36375-f6b3-4789-b379-de10e85bdc11'::uuid;

UPDATE public.destinations
SET city = 'Debre Markos'
WHERE id = '87f84f43-33a6-42f8-8896-c33235bd2bb1'::uuid;

UPDATE public.destinations
SET region = 'South West Ethiopia Peoples', city = 'Mizan Aman'
WHERE id = '8809f9f2-116f-4013-86a8-2c5a18175bda'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos'
WHERE id = '8852aefd-6716-4705-ade6-d70e40db9973'::uuid;

UPDATE public.destinations
SET region = 'South West Ethiopia Peoples', city = 'Bonga'
WHERE id = '885649e0-596c-4fc0-b81d-778d432372f5'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'East Shewa'
WHERE id = '8875723d-4573-45bf-9874-0ae1210d22f1'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Woldia'
WHERE id = '892cbc79-6390-42d1-bd71-2ed79b378d1a'::uuid;

UPDATE public.destinations
SET region = 'Afar', city = 'Dallol'
WHERE id = '8956ca30-716e-4923-b7aa-61fd70fa671d'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Awash'
WHERE id = '89ab6e9f-04fe-477b-95d7-c7c1c0e41884'::uuid;

UPDATE public.destinations
SET region = 'Central Ethiopia Regional State', city = 'Hosaina'
WHERE id = '89b0fb74-c0f0-4cbc-8eab-43ca95b5268c'::uuid;

UPDATE public.destinations
SET city = 'North Shewa'
WHERE id = '8a2c9876-3d1d-4329-80cc-19e3e34cf107'::uuid;

UPDATE public.destinations
SET region = 'Sidama', city = 'Hawassa'
WHERE id = '8ab6c3ad-4cc0-46b9-8163-aca350724db1'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Dinsho'
WHERE id = '8cd7d29e-ca5c-4c5d-9547-58b4d24745ff'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'East Shewa'
WHERE id = '8dcb4a89-1e11-477e-adfc-cba608eccc66'::uuid;

UPDATE public.destinations
SET city = 'Dallol'
WHERE id = '8dd89383-1d93-4358-9f05-75d34b5e5adc'::uuid;

UPDATE public.destinations
SET region = 'South West Ethiopia Peoples', city = 'Bonga'
WHERE id = '8e2d27ee-d1df-42eb-85d6-fd8b214bd966'::uuid;

UPDATE public.destinations
SET region = 'Somali', city = 'Jijiga'
WHERE id = '8e43f02f-24a3-47a8-ae88-2cae06889f34'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Kindo Koysha'
WHERE id = '8e909beb-aa25-4342-881d-1faf0cd3cb30'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Arba Minch'
WHERE id = '8f0ed152-8290-4805-98e9-e7cded62f931'::uuid;

UPDATE public.destinations
SET city = 'Konso'
WHERE id = '8f41c1ee-880f-4605-948d-d7151f570088'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos'
WHERE id = '8f8c7971-f9fa-4e30-bd73-2cfdde6d4cd6'::uuid;

UPDATE public.destinations
SET city = 'Bahir Dar Special Zone'
WHERE id = '9063a991-68a8-4abb-aa58-84e371147fbf'::uuid;

UPDATE public.destinations
SET city = 'Dinsho'
WHERE id = '912c9319-94d0-4491-a362-a1aa2b995122'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Gulale'
WHERE id = '91b4d2c6-1baf-43f4-b20f-236de77fb168'::uuid;

UPDATE public.destinations
SET city = 'Wollo'
WHERE id = '91dbff24-9719-448d-8429-56a2d907f9cf'::uuid;

UPDATE public.destinations
SET region = 'Harar', city = 'Harar'
WHERE id = '91f5ec03-87e1-493a-adc9-d5432193b182'::uuid;

UPDATE public.destinations
SET city = 'Konso'
WHERE id = '92b7858d-63ae-40c4-8b8b-d7f22c2eed15'::uuid;

UPDATE public.destinations
SET region = 'Central Ethiopia Regional State', city = 'Worabe'
WHERE id = '93d40feb-ce2a-42b8-a1fa-176bd74f9488'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Gulale'
WHERE id = '9476315f-86bd-4c97-aaf7-def273a2daaa'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Yeka'
WHERE id = '94812cd7-959b-4b3b-8045-77417362aa2b'::uuid;

UPDATE public.destinations
SET region = 'Harar', city = 'Harar'
WHERE id = '94869432-e851-4cea-b7db-939fa7be65b6'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Wolaita Sodo'
WHERE id = '94d5c37d-fa37-40a2-ab31-54ebcb67a3c5'::uuid;

UPDATE public.destinations
SET region = 'Central Ethiopia Regional State', city = 'Hosaina'
WHERE id = '94f57ddf-1897-4e4e-8c52-8b3a9c13bccf'::uuid;

UPDATE public.destinations
SET city = 'Metu'
WHERE id = '9554eb6d-d648-47d0-b756-4988f68aed35'::uuid;

UPDATE public.destinations
SET city = 'Jinka'
WHERE id = '955e6d60-f49f-4c8d-b957-20f01cb2a2ef'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Arba Minch'
WHERE id = '95fec16c-2089-4eb1-bb40-3d7910f36919'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Debre Markos'
WHERE id = '96c55b56-44f3-4324-b389-ea53f6b35bc8'::uuid;

UPDATE public.destinations
SET city = 'North Shewa'
WHERE id = '96d5b8bd-cbcc-423d-bd71-e1c7af28bebe'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Sawla'
WHERE id = '979a23fe-2a2d-47a7-abae-dc2b33f33350'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Jinka'
WHERE id = '98488f14-3547-441e-89f0-77b416fdad3d'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Halah Gheralta'
WHERE id = '985d43dc-05d4-43c9-9394-f0cb0a06c034'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Metehara'
WHERE id = '98c1ea10-4a2e-43bb-b9e2-013369decee7'::uuid;

UPDATE public.destinations
SET city = 'Awash'
WHERE id = '990bab76-f1d7-4a01-8cbf-95a413e5cf62'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Wajira Hudo'
WHERE id = '991aae19-c03d-463e-8972-7315ecc8ff17'::uuid;

UPDATE public.destinations
SET region = 'South West Ethiopia Peoples', city = 'Masha'
WHERE id = '994caadf-34b4-425e-a463-f421f7789912'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Sof Omar'
WHERE id = '9965e3e8-94cd-47f5-a2cb-1f9b54a77425'::uuid;

UPDATE public.destinations
SET city = 'Dallol'
WHERE id = '99e4f495-c8c9-4080-a4be-19a62d296698'::uuid;

UPDATE public.destinations
SET city = 'Metehara'
WHERE id = '9a56505f-aa6c-483b-afbb-e357ef11b7ae'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bishoftu'
WHERE id = '9ae04c21-11f2-497e-ab55-0d70ea594866'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Ambo'
WHERE id = '9af706fa-5816-450d-8b1d-0c0054c5703d'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Ambo'
WHERE id = '9b41010d-256d-49e3-a5d8-3274cbafac53'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Lalibela'
WHERE id = '9cf8629a-5d09-4add-9bee-8d89ce0f44cc'::uuid;

UPDATE public.destinations
SET city = 'Langano'
WHERE id = '9d095ae9-630c-4366-a967-537dd17b1062'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Jinka'
WHERE id = '9d5f8831-95c6-4402-bb6d-e5d2d51a4fbd'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Axum'
WHERE id = '9db1e1d4-5ba2-4000-93ac-a0a0d2a5c195'::uuid;

UPDATE public.destinations
SET city = 'Yeha'
WHERE id = '9e43ef47-9766-48de-a223-dbb837559cda'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Ankober'
WHERE id = '9f077fc3-adef-4f23-aa41-eec7ed8b126a'::uuid;

UPDATE public.destinations
SET city = 'Arsi Negelle'
WHERE id = '9f2b1214-5912-4aa3-baf1-cde511a0f0fc'::uuid;

UPDATE public.destinations
SET region = 'South West Ethiopia Peoples', city = 'Masha'
WHERE id = '9fc01cc9-3dc5-4a9e-9dbf-02200bcee829'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Bahir Dar'
WHERE id = '9fd98183-74ba-4250-b0fc-7c931db0acd7'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Sawla'
WHERE id = 'a1ef5df7-cce4-45d0-ba46-7f308e494537'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Chencha'
WHERE id = 'a36e1261-f724-4624-a1c2-3052f5045f9b'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole'
WHERE id = 'a4590c74-818e-4c5d-b77a-f0d086057790'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Mek''elē'
WHERE id = 'a584404f-6bdc-4509-b15b-f3849b06d125'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Omorate'
WHERE id = 'a5df60e9-c2d9-4a85-bf82-f339274cab73'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Yabēlo'
WHERE id = 'a64316d3-1e4b-4c96-b429-3998b8e8d0d9'::uuid;

UPDATE public.destinations
SET city = 'Bahir Dar Special Zone'
WHERE id = 'a69a4f2a-a69b-4d64-837c-5bf3eedd0c69'::uuid;

UPDATE public.destinations
SET city = 'Arsi Negelle'
WHERE id = 'a69cdcf8-67e2-4923-82db-a3e87eef84a3'::uuid;

UPDATE public.destinations
SET city = 'Dallol'
WHERE id = 'a6d4fa71-f780-48c5-a115-162a08f816ca'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Omorate'
WHERE id = 'a739aaa5-5c63-489e-b0de-d4432dc62de7'::uuid;

UPDATE public.destinations
SET city = 'Debre Markos'
WHERE id = 'a86ee5bc-cd7e-4a91-9f3e-7af4e40039d1'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Yirga Cheffe'
WHERE id = 'a8f499a1-073c-4219-92ae-7e4a4ebdea65'::uuid;

UPDATE public.destinations
SET city = 'Bonga'
WHERE id = 'a9666c25-4c4b-4bdf-abd6-95ca09b2891f'::uuid;

UPDATE public.destinations
SET region = 'Harar', city = 'Harar'
WHERE id = 'a9dffab7-8c8d-417c-8a30-4e5dbdc067ce'::uuid;

UPDATE public.destinations
SET city = 'Konso'
WHERE id = 'aa0ffa48-cede-4d4c-999d-1fa870f9141c'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole'
WHERE id = 'aa6c0945-3928-4d30-afd3-651362c8152d'::uuid;

UPDATE public.destinations
SET city = 'Arsi Negelle'
WHERE id = 'aa7db2b3-e978-40ef-a447-af33678cf9f5'::uuid;

UPDATE public.destinations
SET city = 'Konso'
WHERE id = 'abad81e9-d84c-4846-b88c-ab64a36b4327'::uuid;

UPDATE public.destinations
SET region = 'Central Ethiopia Regional State', city = 'Welkite'
WHERE id = 'abce70c4-d1f2-4ed5-bfd9-b63ffcc199e0'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Gulale'
WHERE id = 'aca6e86c-fb19-4fe4-b441-3791249ebde2'::uuid;

UPDATE public.destinations
SET region = 'Somali', city = 'Jijiga'
WHERE id = 'acf09791-c56d-4e12-b883-14bbcf964393'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Awash'
WHERE id = 'ad3b739a-efe0-428e-abbc-fd39480657dc'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Mek''elē'
WHERE id = 'ad62ee0f-0424-4851-a1d7-5c32903add84'::uuid;

UPDATE public.destinations
SET city = 'North Shewa'
WHERE id = 'ae586ea6-be22-47cb-a0b6-79775802dc87'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Adama'
WHERE id = 'aed683d3-0307-4abb-98f3-a8e25645aa21'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Wenchi'
WHERE id = 'af7bb4ed-fff5-4e06-b5da-fc329d82d1fe'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ababa'
WHERE id = 'afca8363-2f78-4c8e-91cf-afe3abfab5bb'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole'
WHERE id = 'affd4889-de6c-4dd1-aa73-05087cb2537f'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Waliso'
WHERE id = 'b03d1698-6c76-41fa-a74d-29805896d22f'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole'
WHERE id = 'b044136b-5159-4c41-8d0f-f205bafc2af9'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos'
WHERE id = 'b0593f5d-c975-467a-8583-b01faf1afd22'::uuid;

UPDATE public.destinations
SET region = 'Afar', city = 'Semera'
WHERE id = 'b14ecf8a-6df7-4193-85e5-28ced46f78aa'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos'
WHERE id = 'b1693eaa-a9a5-4e24-8d9b-f6cbf55415ad'::uuid;

UPDATE public.destinations
SET region = 'Sidama', city = 'Irgalem'
WHERE id = 'b1a65bc3-e022-4324-aca5-cb2fd04db0c9'::uuid;

UPDATE public.destinations
SET region = 'Sidama', city = 'Wondo Genet'
WHERE id = 'b23868c7-7502-47f0-b40e-465c1581a15d'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ababa'
WHERE id = 'b2389ebb-016a-4235-9ea5-93a8fee8b962'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos'
WHERE id = 'b23d5681-12bb-488c-b0ba-9dc07402bb6f'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Menagesha'
WHERE id = 'b2719832-bb7c-4ad6-924d-2fd7cd4783aa'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Wolaita Sodo'
WHERE id = 'b2cc4241-dbb0-4484-a7f0-0081725bec7b'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Metehara'
WHERE id = 'b474cb05-04e1-4512-bd7b-3383bafff91d'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Gulale'
WHERE id = 'b4a07b20-3354-418a-a80b-17a2ac4d0189'::uuid;

UPDATE public.destinations
SET region = 'Benishangul-Gumuz', city = 'Assosa'
WHERE id = 'b587b09e-5cf7-46bb-ab15-2883d5dbb624'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos'
WHERE id = 'b591f80f-e757-4848-b688-e50b97007931'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bishoftu'
WHERE id = 'b59727e4-d721-47d4-b534-ffdc553357e5'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole'
WHERE id = 'b6046336-8442-4977-850f-14dfd8c9d66f'::uuid;

UPDATE public.destinations
SET region = 'South West Ethiopia Peoples', city = 'Bonga'
WHERE id = 'b66b300d-f7f3-4aea-aece-a0c1a5518667'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Bahir Dar Special Zone'
WHERE id = 'b697b80e-b8f3-4880-92a9-8b2279b70a5a'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Bahir Dar Special Zone'
WHERE id = 'b6d0822a-e078-4fe7-a40f-d464fda30f7e'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Arsi Negelle'
WHERE id = 'b6d115e1-9702-4726-a874-591db2868a7a'::uuid;

UPDATE public.destinations
SET region = 'South West Ethiopia Peoples', city = 'Masha'
WHERE id = 'b7859b5c-c334-446f-bb0c-32d5b320250c'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Arba Minch'
WHERE id = 'b786899e-1235-4309-8773-302db27fe085'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Bahir Dar'
WHERE id = 'b79a32d5-6c63-4cc1-becb-c2f1eba832b7'::uuid;

UPDATE public.destinations
SET city = 'Bahir Dar Special Zone'
WHERE id = 'b7b844b3-22fb-437a-8e8f-627a9593794e'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Tis Abay'
WHERE id = 'b7bfc38d-0f85-4a35-bebf-58be47ede083'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Lalibela'
WHERE id = 'b7cda2f1-eaef-40d3-b85d-40f2ccd26f66'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Adama'
WHERE id = 'b81ee5f1-0025-46e8-892d-32113fa97521'::uuid;

UPDATE public.destinations
SET city = 'Debark'
WHERE id = 'b87059a5-5673-48c5-839a-b2b0997a6f55'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Nekemte'
WHERE id = 'b8802b66-fe0e-4ee7-af1b-888ac78b6f90'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Wajira Hudo'
WHERE id = 'b90d1e5f-6af8-4c9b-992c-101e44d8ac58'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos'
WHERE id = 'b93352cd-2f5c-4b4f-a433-9380939782cd'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Arba Minch'
WHERE id = 'b9519fdf-5fc5-41bb-acd1-23bddbbb0383'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Yabēlo'
WHERE id = 'b9a23bb4-1ffc-4535-b70e-56ed34bdde64'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Arsi Negelle'
WHERE id = 'ba001415-e817-4ba5-91ab-19576b02886c'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos'
WHERE id = 'ba333088-9c00-4ee7-b962-298e550aefba'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Sof Omar'
WHERE id = 'ba380ed4-ea00-42e0-9a34-ae2427ca9117'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Dinsho'
WHERE id = 'ba5ee543-3d16-4d06-83b9-fc0de1b389c4'::uuid;

UPDATE public.destinations
SET region = 'South West Ethiopia Peoples', city = 'Bonga'
WHERE id = 'ba88e856-c9a7-46a7-81f5-41cb3cfe90ad'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Shakiso'
WHERE id = 'ba97f6e3-ded6-4b0f-9b91-c34ce33838c4'::uuid;

UPDATE public.destinations
SET city = 'Langano'
WHERE id = 'ba9f56d3-b00a-4c7a-8531-0833b494f3cd'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Wajira Hudo'
WHERE id = 'bb297d28-8b26-43f4-87ad-45513e12cbbe'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Holeta'
WHERE id = 'bb55b346-d2fa-403f-8891-d4d865bf798d'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Konso'
WHERE id = 'bb7553ff-8dce-4d61-ac69-ce032ad551d9'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Debre Tabor'
WHERE id = 'bba05c41-e598-4829-b96a-281cd5bb56bc'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bishoftu'
WHERE id = 'bbba8177-f6f8-4379-bb72-c74eddfef287'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos'
WHERE id = 'bbbd1301-3228-4439-bb78-cc3abaa079a5'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'North Shewa'
WHERE id = 'bc5c38df-1497-4ecd-96d1-924bc1f164fe'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Alamata'
WHERE id = 'bcd68e30-4fab-43ff-b93d-67a768a35b86'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ababa'
WHERE id = 'bd1ca5ba-8165-4805-9eb5-c49d8b293553'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Arba Minch'
WHERE id = 'bd57c662-08da-46da-bffa-c648362a13bc'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Konso'
WHERE id = 'bda1d2aa-2b5c-4c90-a201-bfc2793fa645'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ababa'
WHERE id = 'bdc914c6-b0cc-4302-ad5a-7496a8b5f740'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole'
WHERE id = 'bdd10ec0-fe1e-4536-b60a-400ed9c2804a'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Bahir Dar Special Zone'
WHERE id = 'bdd6772f-6bfb-4879-bdb6-f65d3ce9c837'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Awash'
WHERE id = 'be0be554-18e3-4a59-b93e-6d77199792a3'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Dinsho'
WHERE id = 'be24de44-9b7a-47c4-8687-51d5883c45e7'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Dinsho'
WHERE id = 'be311a32-b448-41f8-8f63-647f6f77af15'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Axum'
WHERE id = 'be475223-1ec6-4fca-abca-1460ed81b275'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Mek''elē'
WHERE id = 'beab2afc-d527-4d16-966c-139621393de9'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Yirga Cheffe'
WHERE id = 'bf5bc580-1fa1-40cd-9318-e7976d9762cd'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole'
WHERE id = 'bf6a9db1-5f34-4588-831c-f56b6debc699'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole'
WHERE id = 'bf769125-da9b-49e1-bd60-ea7ecdb4c2b2'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos'
WHERE id = 'bf9007da-9802-469e-8a39-7298e9991d49'::uuid;

UPDATE public.destinations
SET region = 'Central Ethiopia Regional State', city = 'Welkite'
WHERE id = 'c06dbff9-909d-4784-b3dd-a813bd5aad65'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Sawla'
WHERE id = 'c0790a25-dedf-41d2-9ed5-29c856eed804'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Wenchi'
WHERE id = 'c08bc924-0acd-43cb-9f12-bbc3ea1da327'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Langano'
WHERE id = 'c0b7dbc0-d2f1-4be1-84bf-e3299256a73b'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Adwa'
WHERE id = 'c179481b-6c20-4865-b8f5-dbcb192b4f58'::uuid;

UPDATE public.destinations
SET city = 'Jimma'
WHERE id = 'c1a6a16f-b964-4020-996f-e52242832066'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'North Shewa'
WHERE id = 'c24b3f36-1bf5-4f43-84b4-4bbf702c8125'::uuid;

UPDATE public.destinations
SET region = 'Sidama', city = 'Hawassa'
WHERE id = 'c2a5f29a-8add-47cb-b37b-afe5615dff82'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ababa'
WHERE id = 'c2c2d6ce-e4ff-4cfa-8c01-919b7023a595'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Arsi Negelle'
WHERE id = 'c2c38c81-48d4-497e-87ff-d0758826c84c'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Bahir Dar Special Zone'
WHERE id = 'c308b7ca-980c-4258-ac88-d390865e20c2'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Sheik Hussein'
WHERE id = 'c3787e08-91b7-48a7-a6e5-cfa5aad25850'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Wolaita Sodo'
WHERE id = 'c3857f50-9955-4876-b3e6-19e9ede617b0'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole'
WHERE id = 'c3c9d58f-18ce-48c3-94d5-140fc8406d02'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Arba Minch'
WHERE id = 'c47e7771-4ec9-4e1c-87e6-4819fc1cf1a6'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Bati'
WHERE id = 'c48cf56c-8d47-4e35-a941-7d14e0fe1db0'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Gidole'
WHERE id = 'c4ab2a3f-ee1f-4113-b6f1-70e95604faba'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Kindo Koysha'
WHERE id = 'c63b0741-da33-4f2c-8a84-e52814f969cd'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Yirga Cheffe'
WHERE id = 'c644698a-faaa-474f-9a3c-913f713849f4'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Shashemene'
WHERE id = 'c66c5518-fc5c-43e0-8db8-62928fff08e5'::uuid;

UPDATE public.destinations
SET city = 'Debark'
WHERE id = 'c69c8eff-ee2c-473f-8102-5e00f9f366f3'::uuid;

UPDATE public.destinations
SET region = 'Sidama', city = 'Hawassa'
WHERE id = 'c7472836-4b47-4f35-b75c-3e6b91dc752d'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Wenchi'
WHERE id = 'c74ec0f3-cc83-492e-83ef-e848a7f1c346'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Bahir Dar Special Zone'
WHERE id = 'c758dc1d-f331-43f5-8391-6618dd72af28'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos'
WHERE id = 'c793a71f-abbc-4db9-96ff-5c90e817e977'::uuid;

UPDATE public.destinations
SET city = 'Arba Minch'
WHERE id = 'c7b77278-f7c6-434d-ab40-d4435aa9aee4'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole'
WHERE id = 'c7d9ce90-b7e9-4e67-89eb-d6097111ee39'::uuid;

UPDATE public.destinations
SET city = 'Debark'
WHERE id = 'c8018a74-ffd7-4341-a735-7a7041108187'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Gore'
WHERE id = 'c80324f7-a8ac-49d2-984a-1363d4a01d2b'::uuid;

UPDATE public.destinations
SET region = 'Afar', city = 'Dallol'
WHERE id = 'c8106f86-c5a5-4155-b9c0-843f43e74df1'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Shashemene'
WHERE id = 'c8314a67-e6f0-462f-a0b5-f89adcd07412'::uuid;

UPDATE public.destinations
SET region = 'Dire Dawa', city = 'Dire Dawa'
WHERE id = 'c84f5b62-9037-4c44-b17d-2ec447c4d113'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole'
WHERE id = 'c9577d03-df72-451d-8753-0634bb21b5b0'::uuid;

UPDATE public.destinations
SET region = 'Sidama', city = 'Irgalem'
WHERE id = 'c97a3843-b2a7-40eb-9556-760eb4719a37'::uuid;

UPDATE public.destinations
SET region = 'Afar', city = 'Semera'
WHERE id = 'c9aadb98-ff7c-46c2-9c51-e3ce746d3977'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Ambo'
WHERE id = 'c9e51ff6-14bf-4b3a-b67d-a7077395aa6d'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Wukro'
WHERE id = 'c9fa1b0f-5aea-47e9-bedc-a2eb0f81ba81'::uuid;

UPDATE public.destinations
SET city = 'Semera'
WHERE id = 'ca107b8f-38d9-463b-93fa-900d3dc3c7ea'::uuid;

UPDATE public.destinations
SET city = 'Alatish'
WHERE id = 'ca8b058d-8a0f-4be6-a308-b19e065fcc52'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Nekemte'
WHERE id = 'cabd417b-7068-42f3-9e54-94a4c910a935'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole'
WHERE id = 'cb069543-1748-406e-85c5-a1ce6a139fbe'::uuid;

UPDATE public.destinations
SET region = 'Harar', city = 'Harar'
WHERE id = 'cb38f3d5-5889-4363-beeb-aaf60ba7c5fd'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'North Shewa'
WHERE id = 'cb48a7f7-9b77-419e-87e3-155d66bfe051'::uuid;

UPDATE public.destinations
SET city = 'Bahir Dar Special Zone'
WHERE id = 'cb6263ff-6d91-4ec3-b653-624f067d0a72'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Axum'
WHERE id = 'cc03ab07-e8c5-4875-aa6b-ff703490518e'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ababa'
WHERE id = 'cc41f408-e4b5-4ed8-9d1f-6163c440bc60'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos'
WHERE id = 'cc651d7e-3e4a-4581-801b-2759342e9238'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Adwa'
WHERE id = 'cca58efb-210d-46e4-bdc7-e18d09c0f047'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Melka Awash'
WHERE id = 'ccca7f40-195e-4bbb-9b40-eef93c2d3c19'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Yabēlo'
WHERE id = 'cd0b9480-c5e4-4ad6-9fea-3a06caf2b957'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'East Shewa'
WHERE id = 'cd27f056-465d-4de6-885a-3303d66bb62c'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bishoftu'
WHERE id = 'cdd44bf2-aac8-4bd7-903c-c8becde358ba'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Dinsho'
WHERE id = 'ce315b42-117f-4561-9e47-159111abbb8d'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Halah Gheralta'
WHERE id = 'cee7e00f-e1be-4c5b-8530-409d3c0cc123'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bishoftu'
WHERE id = 'd0c78cdc-e007-4232-81b4-a00a2a3d0365'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Dinsho'
WHERE id = 'd0f6ae18-31eb-4c9c-aa39-eb90c6529f1d'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Sof Omar'
WHERE id = 'd16140a6-e1a1-4ac3-a1f9-b7b08ba9bbd6'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Waliso'
WHERE id = 'd1960692-3be1-4dd9-9704-792abf9649dc'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Wolaita Sodo'
WHERE id = 'd19b0076-cc1c-42ed-9e0e-fedf79181c99'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Debre Markos'
WHERE id = 'd1a5ceb5-e488-4a1e-811e-1e5b18bf6f85'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole'
WHERE id = 'd1e5d3ca-937e-4599-be47-2221add9304d'::uuid;

UPDATE public.destinations
SET region = 'Harar', city = 'Harar'
WHERE id = 'd2b651f4-500d-4e36-971a-d9757c2471fa'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Melka Awash'
WHERE id = 'd308d163-cb67-4f16-82cc-bfde3e42667e'::uuid;

UPDATE public.destinations
SET region = 'Central Ethiopia Regional State', city = 'Welkite'
WHERE id = 'd37a302d-a566-4feb-8677-a5615194a1fa'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bishoftu'
WHERE id = 'd3e114d6-9200-4ddf-a2f0-5facfd55520b'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Gulale'
WHERE id = 'd403b0cc-d554-42ae-bb06-6f9761dc9a67'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bishoftu'
WHERE id = 'd40e83d4-324f-4ae4-8c3a-f135f1dea77e'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Nekemte'
WHERE id = 'd43c3571-c894-49a4-a2cf-c74c1f62b4ba'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Debre Markos'
WHERE id = 'd6cd3ad9-9dca-4129-8ea9-1f90382595bd'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Bahir Dar Special Zone'
WHERE id = 'd6df88bd-3851-4bfa-8035-ded28f9bf6f1'::uuid;

UPDATE public.destinations
SET region = 'Afar', city = 'Semera'
WHERE id = 'd6f4b506-358c-4c07-8613-545df8856a24'::uuid;

UPDATE public.destinations
SET region = 'Central Ethiopia Regional State', city = 'Hosaina'
WHERE id = 'd9200ca5-7926-41cc-a947-69ca12c42f63'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Omorate'
WHERE id = 'da090c95-b649-47c3-b1a3-ec24daee6852'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Ankober'
WHERE id = 'da75ccf6-1c7c-4820-adcd-137529a8fcb1'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Bahir Dar Special Zone'
WHERE id = 'daa5fe9a-bba1-478f-ac29-4df3e649c514'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Gondar'
WHERE id = 'dac81ac1-35fc-432e-9cd8-daf0752fcc5d'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Sof Omar'
WHERE id = 'db32061a-ab70-4f9b-ac1f-43199b1eec7f'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Waliso'
WHERE id = 'db321a40-1895-499a-b7e3-0d36dcd6075f'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Metu'
WHERE id = 'db593f69-6a53-49a8-b2ee-7ef49c5e7aa5'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Halah Gheralta'
WHERE id = 'db62f9e9-528d-4391-8bf2-1b6942014eda'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole'
WHERE id = 'dbf38013-7737-452c-b446-a1bafad5c7de'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Dinsho'
WHERE id = 'dc09a11b-a8d9-415f-8219-aeb1b62bb939'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Arsi Negelle'
WHERE id = 'dc5beebd-989a-421f-bc04-1acf95121a0b'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bishoftu'
WHERE id = 'dc6033f3-6e96-480e-bc1c-1a585c1faf16'::uuid;

UPDATE public.destinations
SET region = 'Somali', city = 'Jijiga'
WHERE id = 'dc659384-abee-4587-a7cb-8c8905a2338e'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Bahir Dar Special Zone'
WHERE id = 'dc6c13c6-9881-429d-9cce-bdbf3a3320b7'::uuid;

UPDATE public.destinations
SET city = 'North Shewa'
WHERE id = 'dd373029-f367-4677-9213-c7074713ac9d'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Gulale'
WHERE id = 'de0111c1-703e-4a89-b998-99ca0df03a61'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Omorate'
WHERE id = 'de476c5c-1f7b-44e6-b522-a1b087934aab'::uuid;

UPDATE public.destinations
SET region = 'South West Ethiopia Peoples', city = 'Mizan Aman'
WHERE id = 'de804fb7-93e7-425c-9ea1-55219fe34242'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos'
WHERE id = 'deaec14b-0031-4456-866d-2ac585815219'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Gore'
WHERE id = 'deb3bf1c-c2a1-4b71-a02c-fd7d9e92e1c2'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Wenchi'
WHERE id = 'df9ba565-7a8a-434a-a692-a89f70761e4b'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Debark'
WHERE id = 'df9dca52-8ed4-4611-b7ef-04776d976b17'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole'
WHERE id = 'dfe26783-ecf8-4932-9e7e-be9054d0e8d3'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Turmi'
WHERE id = 'e08c1b7d-f15f-4226-9a5f-3693faa2eb30'::uuid;

UPDATE public.destinations
SET region = 'Central Ethiopia Regional State', city = 'Welkite'
WHERE id = 'e0ee99c1-c9fb-4dfd-b2cd-11b6d59fa054'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Lalibela'
WHERE id = 'e0eff33d-15e7-414f-b4b1-b789a8c93d34'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Bahir Dar'
WHERE id = 'e1382cdc-e501-45f4-9f90-7d38c112fe15'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos'
WHERE id = 'e146f45b-dfc7-462c-975a-7e0ac0d35fb8'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Lalibela'
WHERE id = 'e161228f-f8bb-4d3c-b956-302608ba79ac'::uuid;

UPDATE public.destinations
SET city = 'Dallol'
WHERE id = 'e16cab51-6ff7-4411-8838-d9c7f44a3a6d'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Tis Abay'
WHERE id = 'e2094401-518e-4d27-9264-269f57b3ced2'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Debre Birhan'
WHERE id = 'e29e1457-4de8-430d-af73-bfa7b7e3c8fc'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Lalibela'
WHERE id = 'e2bc4b10-628f-47d2-958e-b668cc85549e'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Gondar'
WHERE id = 'e2d4af36-94e9-4b2b-aaa3-79acec03717a'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Waliso'
WHERE id = 'e2ee61b6-a524-49b4-86d6-bc8e3c455418'::uuid;

UPDATE public.destinations
SET city = 'Arsi Negelle'
WHERE id = 'e3442236-676c-47fc-b4ac-1a07a49cc3e9'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Metehara'
WHERE id = 'e36ccfb2-d9d8-4896-9acc-b67043d86c1c'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Turmi'
WHERE id = 'e425980a-bc0c-48c0-88a0-42c35caf9007'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Debre Markos'
WHERE id = 'e5290277-feee-4b18-a0fb-09251f03e4cc'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Bati'
WHERE id = 'e52c385f-efbd-441b-a870-46d78f57672d'::uuid;

UPDATE public.destinations
SET city = 'Bahir Dar Special Zone'
WHERE id = 'e5616ade-a78a-4848-8707-767599849de4'::uuid;

UPDATE public.destinations
SET region = 'Dire Dawa', city = 'Dire Dawa'
WHERE id = 'e5a45217-8193-4c21-bbd7-7966c36992a5'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Arba Minch'
WHERE id = 'e5b41c71-30d9-454f-b3fe-e78c346bb04e'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Debre Birhan'
WHERE id = 'e5c19409-7709-446d-8fc4-6cc5d63148f2'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bishoftu'
WHERE id = 'e65e7f57-6eef-478b-8498-2f914684b727'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Bati'
WHERE id = 'e65fb972-3b2e-4f44-b378-2d948e987d65'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Asella'
WHERE id = 'e66176f0-f729-448a-aca2-77fd4ae714c5'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Alatish'
WHERE id = 'e6acf773-bd3b-4622-b2bf-4cfafa5128f1'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos'
WHERE id = 'e6af91ca-a88f-4ee3-9d46-82bf64a02c56'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Woldia'
WHERE id = 'e6cc1fdf-d513-4b90-b9e6-2021a93d2770'::uuid;

UPDATE public.destinations
SET region = 'South West Ethiopia Peoples', city = 'Mizan Aman'
WHERE id = 'e6dd5fbc-db07-4b35-bba3-98d9a31fb295'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos'
WHERE id = 'e716d533-bba5-4c25-9cae-9a803c2aa308'::uuid;

UPDATE public.destinations
SET region = 'South West Ethiopia Peoples', city = 'Mizan Aman'
WHERE id = 'e79223a1-6dce-4a14-b44e-deeb2c28045c'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Jimma'
WHERE id = 'e7ae24aa-a8d8-4cd2-8e07-7d08d375b178'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Yayu'
WHERE id = 'e7c363de-1af4-452b-b4c4-9c74db93493a'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Debre Tabor'
WHERE id = 'e7e1ca0d-d70f-4ad8-9990-bea6c6731a80'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole'
WHERE id = 'e7e254b7-1000-462a-a259-0da538f5b711'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos'
WHERE id = 'e81feb9c-c32c-4a24-a4bd-0e0eec85baea'::uuid;

UPDATE public.destinations
SET city = 'Asaita'
WHERE id = 'e87aea51-547a-4d61-9a2b-23633a6efd90'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'North Shewa'
WHERE id = 'e87b2936-859d-416d-8b23-b4f78208f8ea'::uuid;

UPDATE public.destinations
SET region = 'Sidama', city = 'Hawassa'
WHERE id = 'e87ffaf7-af57-4323-a7c3-7bb4ae446e3a'::uuid;

UPDATE public.destinations
SET city = 'Bahir Dar Special Zone'
WHERE id = 'e8a409e6-5891-4fe6-8616-1f0561d86892'::uuid;

UPDATE public.destinations
SET region = 'Sidama', city = 'Hawassa'
WHERE id = 'e90392a8-2d5f-4483-9955-18a916528b95'::uuid;

UPDATE public.destinations
SET city = 'Langano'
WHERE id = 'ea95cafa-c224-4b52-99de-4e124eca5483'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Melka Awash'
WHERE id = 'eb1d0d9e-7b02-4cf7-af59-450813aa3f3a'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Debre Markos'
WHERE id = 'eb2e3e36-5bf3-452c-95b0-ab1937262da7'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Gonder'
WHERE id = 'eba7e017-0af8-439a-a338-fb1f39de4e66'::uuid;

UPDATE public.destinations
SET city = 'Arsi Negelle'
WHERE id = 'ebf1a4c1-7721-498d-891d-f315b78f02a6'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ketema'
WHERE id = 'ebf571b4-02ac-4d05-a9e4-03240d95c05b'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Adama'
WHERE id = 'ec0b4b39-c066-45e2-8866-0df91f8f5703'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ababa'
WHERE id = 'ec45b60c-8984-4721-8ae2-fa2cb42338ac'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole'
WHERE id = 'ed02e462-6e16-418e-b34d-c2cedcf84deb'::uuid;

UPDATE public.destinations
SET region = 'Central Ethiopia Regional State', city = 'Worabe'
WHERE id = 'ed96b619-8ac4-46dc-81ae-868b541e5960'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Langano'
WHERE id = 'edc5f20c-be22-4100-9eef-7812f6d79f01'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Gorgora'
WHERE id = 'ee082331-2520-4e5d-8ab7-d51a399353e5'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Halah Gheralta'
WHERE id = 'ee72cb82-67ef-47c7-8a66-898521f72dea'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ababa'
WHERE id = 'eec44c92-342d-447e-bb7e-05e6363f86b9'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Sawla'
WHERE id = 'eeefd997-3866-44c2-bd0e-91dfec7a9b65'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Injibara'
WHERE id = 'efba5d01-d208-4b19-b897-c156b7128c3f'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Yirga Cheffe'
WHERE id = 'f0027c6c-b9cc-474d-bf04-058fb4496ffd'::uuid;

UPDATE public.destinations
SET region = 'Central Ethiopia Regional State', city = 'Durame'
WHERE id = 'f00b827d-8d9d-4a02-adba-c6c1d60d1558'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Bahir Dar'
WHERE id = 'f020dc2c-784a-4055-9936-a0ddc2cc2191'::uuid;

UPDATE public.destinations
SET region = 'Harar', city = 'Harar'
WHERE id = 'f020e9ad-58c9-438f-b695-c59f443b6512'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Gondar'
WHERE id = 'f02bd757-7a00-4d80-8858-21e2cbfe73bf'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Chencha'
WHERE id = 'f0368d9f-0208-439e-b7f3-354d921da1a1'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Yabēlo'
WHERE id = 'f0466c41-21ac-49f8-8d7a-23a1dd97e87d'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Langano'
WHERE id = 'f078adc4-fc0e-45e4-b32f-957ff310e3eb'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Gulale'
WHERE id = 'f07fa47a-e4ce-47b0-8299-df90bfcc2562'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos'
WHERE id = 'f1364905-24d4-4be6-81cb-677c3d884297'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Konso'
WHERE id = 'f17f41b3-119b-4238-bf27-bfd8a7967d50'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole'
WHERE id = 'f1c602bd-c002-4115-b125-07efa6beaed2'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Adwa'
WHERE id = 'f1dba427-0151-4849-a4aa-d11007f5561f'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ketema'
WHERE id = 'f1e94284-9699-4c01-b031-18b1bd010ca0'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Metehara'
WHERE id = 'f22e131e-f6ff-46fd-b62e-4ebfcc558a91'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ketema'
WHERE id = 'f2349bdb-6eed-434d-8d05-ce735c27ecc3'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos'
WHERE id = 'f2a62849-1864-4f76-af5e-d5fee1a177ea'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Arsi Negelle'
WHERE id = 'f2cf8403-c3f0-4603-baea-f72a479907b3'::uuid;

UPDATE public.destinations
SET city = 'Dinsho'
WHERE id = 'f2ec6eeb-5f2e-4321-90af-393ed36d7387'::uuid;

UPDATE public.destinations
SET region = 'South West Ethiopia Peoples', city = 'Mizan Aman'
WHERE id = 'f35da1ee-0a7f-4d44-81ac-d8f5260f8e44'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Gulale'
WHERE id = 'f361bd54-2e54-4135-a8a2-343e0870a03c'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ababa'
WHERE id = 'f36fbf60-eda8-42f9-8e76-8910fbf1dbbf'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos'
WHERE id = 'f3bedb08-8399-4461-85d5-34fd8057c78e'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Wolaita Sodo'
WHERE id = 'f42a7d8d-a948-4176-be13-0f4f36be34f3'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole'
WHERE id = 'f43e0c0a-cd23-484d-a406-03dddfaca3ab'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Sawla'
WHERE id = 'f4f95286-6786-41e9-b522-aa015246904a'::uuid;

UPDATE public.destinations
SET region = 'South West Ethiopia Peoples', city = 'Mizan Aman'
WHERE id = 'f5019af9-5bc6-47e4-8b44-8accbd6baa67'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Woldia'
WHERE id = 'f529ccff-d391-4563-8af9-0df8519f3852'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Nekemte'
WHERE id = 'f542507f-3f8c-46fe-a308-e16f4f32959b'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Axum'
WHERE id = 'f5c107b6-a5ae-4cd5-b074-4e2e8aada1dc'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Omorate'
WHERE id = 'f69157ac-685f-4b5f-b0af-6b71347979f7'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Wenchi'
WHERE id = 'f694be04-381b-440a-9545-81543d975602'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Ambo'
WHERE id = 'f6cb8c09-9a5b-409f-8f6c-8405a1459cfa'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Arba Minch'
WHERE id = 'f6cf073d-078f-470a-93e6-aae295b800f0'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Yayu'
WHERE id = 'f6d8b632-3147-471e-86e7-093ab1c3ca64'::uuid;

UPDATE public.destinations
SET region = 'Afar', city = 'Asaita'
WHERE id = 'f719cc5a-5aa3-4f16-b7c4-dad3732304ce'::uuid;

UPDATE public.destinations
SET city = 'Dallol'
WHERE id = 'f74134b4-4bc5-4a9e-a55a-a3fcca665db5'::uuid;

UPDATE public.destinations
SET region = 'Sidama', city = 'Hawassa'
WHERE id = 'f7b2a94d-8716-4079-bea8-10fc20b7de92'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole'
WHERE id = 'f80ad547-5744-4311-9968-43bbd54ed74e'::uuid;

UPDATE public.destinations
SET city = 'Dinsho'
WHERE id = 'f838def2-16ed-4546-b32f-97336cfd5fdb'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Ankober'
WHERE id = 'f8ae3391-2ecb-40d9-a797-060b45c8e45c'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ketema'
WHERE id = 'f8f2ed1c-8207-428e-8c79-74753db23607'::uuid;

UPDATE public.destinations
SET region = 'Sidama', city = 'Hawassa'
WHERE id = 'f9c64f77-b388-4e33-8870-fbe0668e3643'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ababa'
WHERE id = 'fa19f548-e5b2-4b6b-ab8b-9f11f8eee0b5'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole'
WHERE id = 'faa1f17f-ab29-45cc-9b33-904ecf78289e'::uuid;

UPDATE public.destinations
SET region = 'Sidama', city = 'Hawassa'
WHERE id = 'faa2b5ea-c52b-442e-b9fb-0f2221786936'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Alamata'
WHERE id = 'faa9bc01-6952-41fd-bb5d-73e2a8c15a18'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos'
WHERE id = 'fad2e7fb-348d-4f00-ae5d-fa4254a97217'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ketema'
WHERE id = 'fae714ce-8f16-45a7-86a6-b11fb7f600ec'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bishoftu'
WHERE id = 'fb09c840-17ec-4fd8-bb29-0df3d3c3e573'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Lalibela'
WHERE id = 'fb802d8c-6e47-4412-af36-e3ad6b44a8ef'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Sawla'
WHERE id = 'fc00cdd1-1699-4f5b-aed6-3f3482045951'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ababa'
WHERE id = 'fcb62da3-38a1-47f1-b2a2-16f25fc56ba3'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Gondar'
WHERE id = 'fd153e00-5d73-4e0f-ae57-6c1630596485'::uuid;

UPDATE public.destinations
SET city = 'Jimma'
WHERE id = 'fd70affa-c62c-4892-8eed-fc976450ce69'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Jinka'
WHERE id = 'fd92a05a-3ab7-49ce-8c87-48a532c91c42'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole'
WHERE id = 'fdde23d4-2203-4160-93cd-84a0d88274c5'::uuid;

UPDATE public.destinations
SET city = 'Dallol'
WHERE id = 'fdf6e1fb-0195-4081-b0e2-bb21501d95ae'::uuid;

UPDATE public.destinations
SET city = 'Langano'
WHERE id = 'feb50060-1608-4cda-bf5f-d395da4818af'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Holeta'
WHERE id = 'fec97e8f-a3e5-4836-8ce3-ba981d8b1ff6'::uuid;

UPDATE public.destinations
SET region = 'Sidama', city = 'Hawassa'
WHERE id = 'fecbd9aa-4b22-48e3-b1d4-f450e2d3992f'::uuid;

UPDATE public.destinations
SET city = 'Dallol'
WHERE id = 'ff8cbf83-f899-4c5c-aa5d-6c7796a0b61d'::uuid;

UPDATE public.destinations
SET region = 'Central Ethiopia Regional State', city = 'Durame'
WHERE id = 'ffca54ea-b470-4b3b-ba34-3ca0e84517b7'::uuid;

COMMIT;
