-- Generated by scripts/enrich_destinations.py
-- Review destinations_enrichment_report.csv before applying.
BEGIN;

UPDATE public.destinations
SET region = 'Somali', city = 'Jijiga', location = '{"lat":9.3595825,"lng":42.8011943}'
WHERE id = 'a3674094-06ce-460e-a0b5-794603a7574d'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Lalibela', location = '{"lat":12.033783,"lng":39.0439966}'
WHERE id = 'a683a9af-809c-48ea-8732-e47bc46ab955'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos', location = '{"lat":9.0047069,"lng":38.7670633}'
WHERE id = 'aaedbac4-8136-41c0-a679-f9159aa9705d'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos', location = '{"lat":9.0100868,"lng":38.7640678}'
WHERE id = 'aaf39f24-f344-4aca-b02c-7987205bd9e5'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Gulale', location = '{"lat":9.0507285,"lng":38.7611956}'
WHERE id = 'ab036e39-48a4-4f83-927e-c6f35dc44a70'::uuid;

COMMIT;
