-- Generated by scripts/enrich_destinations.py
-- Review destinations_enrichment_report.csv before applying.
BEGIN;

UPDATE public.destinations
SET region = 'Sidama', city = 'Hawassa', location = '{"lat":7.0476368,"lng":38.4682618}'
WHERE id = '648bdc09-cd0f-4915-9e79-83b8cf62d074'::uuid;

UPDATE public.destinations
SET region = 'Afar', location = '{"lat":11.5501731,"lng":41.3888651}'
WHERE id = '64d79049-824e-447d-9295-528cf0dc2f80'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole', location = '{"lat":9.0003176,"lng":38.7872056}'
WHERE id = '64f5e6cd-d7c8-4ee3-9091-21ff4f851f58'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Asella', location = '{"lat":7.9150565,"lng":39.2620904}'
WHERE id = '6525ad8d-450a-4eab-8c46-602f29e60b2d'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Mek''elē', location = '{"lat":13.4842836,"lng":39.4554493}'
WHERE id = '656ef50f-0224-48ff-bf13-9f72009240f4'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Debre Libanos', location = '{"lat":9.7336961,"lng":38.8138446}'
WHERE id = '657486e7-1f74-4541-b7db-e6fdd6ca8235'::uuid;

UPDATE public.destinations
SET region = 'Afar', location = '{"lat":11.1711957,"lng":41.7873451}'
WHERE id = '65fd1b83-514b-4f10-bac4-f4e88a03070d'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Yeka', location = '{"lat":9.0205677,"lng":38.8002333}'
WHERE id = '661a4bd8-89ca-447e-9341-9d4403f5872a'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Adet', location = '{"lat":11.2628077,"lng":37.4859752}'
WHERE id = '663dd3bb-96b0-480f-8ea5-51689c3e6967'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos', location = '{"lat":9.0161832,"lng":38.7677471}'
WHERE id = '668c5fdf-aa64-4a76-8568-861c82198a93'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Dessie', location = '{"lat":11.122604,"lng":39.634982}'
WHERE id = '67225d3a-ffaf-4a0b-9125-eacb1a2467a3'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole', location = '{"lat":8.9869542,"lng":38.7890925}'
WHERE id = '6813575d-96cc-42be-b65b-e016185db629'::uuid;

UPDATE public.destinations
SET region = 'Somali', city = 'Jijiga', location = '{"lat":9.3508526,"lng":42.8003788}'
WHERE id = '69044005-6dd1-4baa-a7bf-5ac45942266f'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Jimma', location = '{"lat":7.6756152,"lng":36.8478779}'
WHERE id = '6922d03b-2e0a-43e8-ad8c-570f62c016ff'::uuid;

UPDATE public.destinations
SET region = 'Sidama', city = 'Irgalem', location = '{"lat":6.7473747,"lng":38.40767}'
WHERE id = '692926ec-f32f-4685-b291-a17e5aa1e39e'::uuid;

UPDATE public.destinations
SET region = 'Harar', city = 'Harar', location = '{"lat":9.3118304,"lng":42.1284009}'
WHERE id = '694cfc0b-4394-40a0-b7e5-32aaa17d5ab3'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bale', location = '{"lat":7.7308591,"lng":39.9998827}'
WHERE id = '69c333c5-10b0-4d5f-95a5-9c7f05521d4a'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Ankober', location = '{"lat":9.5911547,"lng":39.7338213}'
WHERE id = '6a708f59-6b30-45a4-9ced-db6d926f2b43'::uuid;

UPDATE public.destinations
SET region = 'Amhara', location = '{"lat":10.7117887,"lng":37.8435035}'
WHERE id = '6ad09a0a-e179-4659-9ef9-48f0f8842ff8'::uuid;

UPDATE public.destinations
SET region = 'Afar', location = '{"lat":13.9528181,"lng":40.6366886}'
WHERE id = '6b48558c-8f66-48e5-8256-390af4262692'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ababa', location = '{"lat":9.0358119,"lng":38.7524315}'
WHERE id = '6beb2067-f215-4d07-a80e-7c486a81a6f6'::uuid;

UPDATE public.destinations
SET region = 'Oromia', location = '{"lat":8.25,"lng":36.91667}'
WHERE id = '6bfc2bf6-f880-4626-86b6-f40bbd334847'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bishoftu', location = '{"lat":8.750004,"lng":38.981734}'
WHERE id = '6c7a043c-5bff-443a-9499-79fe143ad512'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Lideta', location = '{"lat":9.0116517,"lng":38.7385122}'
WHERE id = '6c883b0e-b8db-4e9d-9c62-90df9053b424'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Arba Minch', location = '{"lat":6.0302778,"lng":37.5921705}'
WHERE id = '6caa0ab7-6fa4-485d-af54-761a45f3d5a2'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ababa', location = '{"lat":9.0358119,"lng":38.7524315}'
WHERE id = '6cba1f7c-4a71-4c37-a357-6e5d58a52218'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Altipiano Sora', location = '{"lat":12.4138829,"lng":38.6617562}'
WHERE id = '6cc423aa-f46e-4c7f-af02-13439b70781e'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos', location = '{"lat":8.9993889,"lng":38.743291}'
WHERE id = '6cc5e8b1-b605-44b5-b5df-68bc84b67610'::uuid;

UPDATE public.destinations
SET region = 'Gambela', city = 'Gambela', location = '{"lat":8.2503656,"lng":34.5877344}'
WHERE id = '6cc83001-5676-4d8e-8b06-22f0ab80eb5b'::uuid;

UPDATE public.destinations
SET region = 'Amhara', location = '{"lat":13.2458802,"lng":38.0999456}'
WHERE id = '6ceaf39e-da7e-4e79-8097-f606b29cf7f6'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Wukro', location = '{"lat":13.7862549,"lng":39.601525}'
WHERE id = '6d0addeb-e6bf-4e18-9fd9-476918014e60'::uuid;

UPDATE public.destinations
SET region = 'Amhara', location = '{"lat":10.3511111,"lng":39.7959722}'
WHERE id = '6d1ff157-30a7-4e30-a84b-3e6902657388'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Dessie', location = '{"lat":11.122604,"lng":39.634982}'
WHERE id = '6d8a98f8-7f29-4096-986a-1fdff33246ac'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ababa', location = '{"lat":9.0358119,"lng":38.7524315}'
WHERE id = '6de79b57-18cb-4858-b7a4-cd7efe7f713f'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Bahir Dar Special Zone', location = '{"lat":11.5957145,"lng":37.3854336}'
WHERE id = '6ebdfa50-948b-4a55-b876-75027bfeff53'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Mecam', location = '{"lat":12.75,"lng":39.68333}'
WHERE id = '6ec0c0e2-9f74-4a68-83a1-19a1b25e40cf'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Dorze', location = '{"lat":6.1948568,"lng":37.5743447}'
WHERE id = '6ef89f25-49f4-4d34-a0b2-4366d37d902a'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Jinka', location = '{"lat":5.786181,"lng":36.5654425}'
WHERE id = '6f0c80e8-8f2a-4577-810c-26657a4753e3'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Shakiso', location = '{"lat":5.7746802,"lng":38.9028468}'
WHERE id = '6f424124-ebba-488d-b52f-1af1a3422633'::uuid;

UPDATE public.destinations
SET region = 'Sidama', city = 'Hawassa', location = '{"lat":7.0481029,"lng":38.47861}'
WHERE id = '6f76873a-2039-489a-9879-f0a6b25c24c2'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos', location = '{"lat":9.0100868,"lng":38.7640678}'
WHERE id = '6f9058d6-050c-460d-b4e6-dda815555391'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bishoftu', location = '{"lat":8.750004,"lng":38.981734}'
WHERE id = '708dce05-ba03-4a7a-a387-5aa2ce0ee152'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Jimma', location = '{"lat":7.6756152,"lng":36.8478779}'
WHERE id = '70cecc9a-79c8-4b63-977f-1ec8642df328'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole', location = '{"lat":8.9997998,"lng":38.7840093}'
WHERE id = '71a0f2e7-dfb2-4f1e-86d3-c339cb24bd5a'::uuid;

UPDATE public.destinations
SET region = 'Sidama', city = 'Hawassa', location = '{"lat":7.0519849,"lng":38.4834978}'
WHERE id = '71bfbd21-38b2-4cc9-8fe7-c9f387c89b43'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole', location = '{"lat":9.0135725,"lng":38.7800846}'
WHERE id = '7288f377-de14-49a6-abe4-ecce81608dc2'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Sodere', location = '{"lat":8.4034494,"lng":39.3869748}'
WHERE id = '72dca287-624c-468a-a6c6-a5fd99ba4909'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Gonder', location = '{"lat":12.610368,"lng":37.466766}'
WHERE id = '72e965f1-e8b4-435a-8127-1ec31d3d45ea'::uuid;

UPDATE public.destinations
SET region = 'Oromia', location = '{"lat":5.0,"lng":37.0}'
WHERE id = '72e9f520-f4ea-4bac-8419-6688f25a6966'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Arba Minch', location = '{"lat":6.0215142,"lng":37.5539809}'
WHERE id = '7326e44a-6069-462a-abf4-ee25de2db194'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Gonder', location = '{"lat":12.610368,"lng":37.466766}'
WHERE id = '737dad16-70aa-4b63-bd37-f2563ce871ed'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', location = '{"lat":5.835358,"lng":37.568742}'
WHERE id = '73ac5648-8a44-493e-81ad-74bd712adc6f'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos', location = '{"lat":9.010443,"lng":38.7651132}'
WHERE id = '73fa1647-e28a-4ed2-8c91-01d9e8af8517'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Halah Gheralta', location = '{"lat":13.7478418,"lng":39.2536119}'
WHERE id = '744bca88-3b45-4fbf-a9d9-28e8c3f28974'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Ankober', location = '{"lat":9.5911547,"lng":39.7338213}'
WHERE id = '753031cc-2dfd-4765-aeb5-776df375a55b'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Dahana', location = '{"lat":12.4298493,"lng":38.82529}'
WHERE id = '7573f029-279f-4fce-a981-04527cfb1046'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Metu', location = '{"lat":8.2956473,"lng":35.5834319}'
WHERE id = '75a34292-e2bf-40bb-8848-710890acde9f'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Lalibela', location = '{"lat":12.0360639,"lng":39.0456845}'
WHERE id = '75d0ec7a-424a-418e-a85f-9f2cda14bbad'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Dinsho', location = '{"lat":7.108213,"lng":39.780153}'
WHERE id = '75d23b20-011f-43bf-92ce-863f0cc0cc0b'::uuid;

UPDATE public.destinations
SET region = 'Dire Dawa', city = 'Dire Dawa', location = '{"lat":9.5913368,"lng":41.8566126}'
WHERE id = '7632ad52-c5db-4151-beb2-afa168a24600'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Melka Awash', location = '{"lat":8.705032,"lng":38.5996486}'
WHERE id = '766d4383-7b86-400b-8964-a88261cba48b'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ababa', location = '{"lat":9.0379782,"lng":38.7618606}'
WHERE id = '7700497d-3c1e-4056-b314-3b8c7d6a7327'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Arba Minch', location = '{"lat":6.0659447,"lng":37.5600365}'
WHERE id = '7721fb0f-91e7-420b-9571-f3d72180fa00'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole', location = '{"lat":8.9955392,"lng":38.7870007}'
WHERE id = '772718d2-2fcd-4651-b304-2f42ba25545a'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Awash', location = '{"lat":8.9034451,"lng":39.9186248}'
WHERE id = '774fb0dd-af2d-4f6b-aa4d-83e060941082'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos', location = '{"lat":9.0161832,"lng":38.7677471}'
WHERE id = '7766b967-9486-4a9f-840d-f27ba1d5db25'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Gatira', location = '{"lat":8.0424398,"lng":36.3410514}'
WHERE id = '77a2c585-e455-4d80-865c-97065deba4cc'::uuid;

UPDATE public.destinations
SET region = 'Amhara', location = '{"lat":10.7117887,"lng":37.8435035}'
WHERE id = '77d50b88-c513-48e5-bd4b-5884529a42aa'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Lalibela', location = '{"lat":12.0360639,"lng":39.0456845}'
WHERE id = '77e40b88-aec6-430b-afb4-fdfc163e79fb'::uuid;

COMMIT;
