-- Generated by scripts/enrich_destinations.py
-- Review destinations_enrichment_report.csv before applying.
BEGIN;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Omorate', location = '{"lat":4.8032381,"lng":36.0504375}'
WHERE id = '8f15be20-81cc-41c0-8560-0edcd02889d6'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos', location = '{"lat":9.0159277,"lng":38.7712221}'
WHERE id = '8f1e59ff-3f5d-4f0c-8872-ddd7ec9d468e'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', location = '{"lat":5.25,"lng":37.5}'
WHERE id = '8f41c1ee-880f-4605-948d-d7151f570088'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bishoftu', location = '{"lat":8.7873711,"lng":38.9931534}'
WHERE id = '8f65d342-d22a-4b44-95b2-b38f63f74553'::uuid;

UPDATE public.destinations
SET region = 'Amhara', location = '{"lat":11.9507719,"lng":37.294878}'
WHERE id = '9063a991-68a8-4abb-aa58-84e371147fbf'::uuid;

UPDATE public.destinations
SET region = 'South West Ethiopia Peoples', city = 'Bonga', location = '{"lat":7.2645383,"lng":36.2460526}'
WHERE id = '909e4cf2-c7ff-4ab4-85b1-dbcdc3aaefe4'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Adama', location = '{"lat":8.5633204,"lng":39.2903721}'
WHERE id = '90ae9c67-5eb1-49f9-9eed-2335fe70afa3'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Dendi', location = '{"lat":8.9347933,"lng":38.1236741}'
WHERE id = '91086c98-7678-44f3-975b-c91441850ea6'::uuid;

UPDATE public.destinations
SET region = 'Oromia', location = '{"lat":6.7584724,"lng":39.7218796}'
WHERE id = '912c9319-94d0-4491-a362-a1aa2b995122'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ababa', location = '{"lat":9.0225621,"lng":38.7527167}'
WHERE id = '913a500a-f3f6-4bf3-9ef1-8ea1d0487905'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Debre Libanos', location = '{"lat":9.7295697,"lng":38.8167682}'
WHERE id = '914678a4-c6d8-4245-800d-fcdcd29726e9'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Bahir Dar', location = '{"lat":11.6039786,"lng":37.3212006}'
WHERE id = '91544c3a-921b-40f3-9431-6e2c8601790e'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ketema', location = '{"lat":9.0321724,"lng":38.7398953}'
WHERE id = '917a1935-f63a-42c6-b62b-6562fba03986'::uuid;

UPDATE public.destinations
SET region = 'Amhara', location = '{"lat":11.5245732,"lng":39.3529106}'
WHERE id = '91dbff24-9719-448d-8429-56a2d907f9cf'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Melka Awash', location = '{"lat":8.705032,"lng":38.5996486}'
WHERE id = '920e5e85-d676-427b-be80-421953474914'::uuid;

UPDATE public.destinations
SET region = 'Sidama', city = 'Hawassa', location = '{"lat":7.0481029,"lng":38.47861}'
WHERE id = '927ecbc5-df2d-490f-9084-5a55d905d06e'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', location = '{"lat":5.25,"lng":37.5}'
WHERE id = '92b7858d-63ae-40c4-8b8b-d7f22c2eed15'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Bahir Dar Special Zone', location = '{"lat":11.5949663,"lng":37.3882251}'
WHERE id = '92c55696-bd94-407e-9d30-b3f7480ba4e1'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Jimma', location = '{"lat":7.6792877,"lng":36.8533248}'
WHERE id = '93622d43-1d35-4375-8ae9-a7870a3234dc'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Yabēlo', location = '{"lat":4.8888074,"lng":38.109828}'
WHERE id = '9368a510-3ea4-41ab-a507-3bcb9402a37f'::uuid;

UPDATE public.destinations
SET region = 'Somali', city = 'Jijiga', location = '{"lat":9.3508526,"lng":42.8003788}'
WHERE id = '938d92ee-aa43-43e7-bb0e-13e642a5b5fd'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Tiya', location = '{"lat":8.437331,"lng":38.609296}'
WHERE id = '93b305b7-2ee4-449c-a9f8-5dc363c705d9'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Halah Gheralta', location = '{"lat":13.7478418,"lng":39.2536119}'
WHERE id = '93fde9e1-4b9b-4a3e-82e5-a186153ee5d0'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos', location = '{"lat":9.0142532,"lng":38.7688899}'
WHERE id = '94b1a91f-4cc4-43dd-8a87-c620e203e29d'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ababa', location = '{"lat":9.0308012,"lng":38.7664911}'
WHERE id = '94bf4182-8b92-486d-bdec-be8e046e2204'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Turmi', location = '{"lat":4.96835,"lng":36.487794}'
WHERE id = '94d12a41-7f0c-4a7b-a886-29f692d429e0'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Debre Damo Debir', location = '{"lat":14.373127,"lng":39.2893444}'
WHERE id = '9500da88-001f-43f0-878b-5e3a2daee625'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Yabēlo', location = '{"lat":4.8888074,"lng":38.109828}'
WHERE id = '9542fac3-8a72-4cd2-8698-4d022b301034'::uuid;

UPDATE public.destinations
SET region = 'Oromia', location = '{"lat":8.41667,"lng":35.75}'
WHERE id = '9554eb6d-d648-47d0-b756-4988f68aed35'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bishoftu', location = '{"lat":8.7873711,"lng":38.9931534}'
WHERE id = '955a9a28-7c28-451f-85ca-c0226728fa0a'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', location = '{"lat":5.6321485,"lng":36.2621523}'
WHERE id = '955e6d60-f49f-4c8d-b957-20f01cb2a2ef'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole', location = '{"lat":8.9794625,"lng":38.7833267}'
WHERE id = '957352d9-93b3-4283-90bc-59f6054d806f'::uuid;

UPDATE public.destinations
SET region = 'Afar', city = 'Semera', location = '{"lat":11.7923098,"lng":41.0089155}'
WHERE id = '95869035-afc3-4181-84fc-199ca30e1a83'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Gonder', location = '{"lat":12.610368,"lng":37.466766}'
WHERE id = '963f586a-6bc8-40de-b5eb-ecf0d6abde0f'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Jinka', location = '{"lat":5.7895896,"lng":36.5681704}'
WHERE id = '96749ad5-3ee7-40f8-9a62-f025b2fce475'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole', location = '{"lat":8.9485552,"lng":38.7959826}'
WHERE id = '96829d8e-cb24-413f-8c3a-7da7ce58d8ef'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Moyale', location = '{"lat":3.5241898,"lng":39.0512683}'
WHERE id = '9686b9ba-499c-4897-8c78-61af60f16d85'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Debre Libanos', location = '{"lat":9.7120303,"lng":38.8475576}'
WHERE id = '96cec641-2b83-4c42-b491-76f45a934edf'::uuid;

UPDATE public.destinations
SET region = 'Amhara', location = '{"lat":10.3511111,"lng":39.7959722}'
WHERE id = '96d5b8bd-cbcc-423d-bd71-e1c7af28bebe'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos', location = '{"lat":9.0204847,"lng":38.7595978}'
WHERE id = '9797f82d-d977-4d1b-8742-c6c69bcb2ea0'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Omorate', location = '{"lat":4.8032381,"lng":36.0504375}'
WHERE id = '97f54aa2-42c0-4402-bc79-ec1ed17e0e02'::uuid;

UPDATE public.destinations
SET region = 'Somali', city = 'Jijiga', location = '{"lat":9.3508526,"lng":42.8003788}'
WHERE id = '97fa3b51-4afd-449f-8fe5-d89fa2746edc'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Bahir Dar Special Zone', location = '{"lat":11.5957145,"lng":37.3854336}'
WHERE id = '9811f302-c7d8-4dc7-ba9a-fa1b342d7837'::uuid;

UPDATE public.destinations
SET region = 'Sidama', city = 'Wondo Genet', location = '{"lat":7.0854757,"lng":38.6141113}'
WHERE id = '983e12e8-2109-4ca0-88eb-8ab86c337ee6'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Sheik Hussein', location = '{"lat":7.7466905,"lng":40.7074585}'
WHERE id = '98825d15-0444-4c03-aafd-531652d97ce9'::uuid;

UPDATE public.destinations
SET region = 'Afar', location = '{"lat":12.29583,"lng":42.22806}'
WHERE id = '990bab76-f1d7-4a01-8cbf-95a413e5cf62'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Walmara', location = '{"lat":8.96667,"lng":38.53333}'
WHERE id = '99d5e22c-f497-4c5b-956e-4c0ad4e3970f'::uuid;

UPDATE public.destinations
SET region = 'Afar', location = '{"lat":13.9528181,"lng":40.6366886}'
WHERE id = '99e4f495-c8c9-4080-a4be-19a62d296698'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Dessie', location = '{"lat":11.122604,"lng":39.634982}'
WHERE id = '9a2b1b60-8109-4faf-afdf-3cd13a617d71'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos', location = '{"lat":9.010443,"lng":38.7651132}'
WHERE id = '9a2cd2c9-90bf-473f-b560-3bfa87e6eecc'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos', location = '{"lat":9.0211333,"lng":38.7622597}'
WHERE id = '9a43800e-30e2-4a59-9d66-8c4d960dcedc'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Bahir Dar Special Zone', location = '{"lat":11.6030239,"lng":37.3797987}'
WHERE id = '9a4b4a01-887a-4cbf-87ea-646cb1ed08c2'::uuid;

UPDATE public.destinations
SET region = 'Oromia', location = '{"lat":8.9875653,"lng":39.9019248}'
WHERE id = '9a56505f-aa6c-483b-afbb-e357ef11b7ae'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Wukro', location = '{"lat":13.7862549,"lng":39.601525}'
WHERE id = '9b35e32e-ffdd-4b17-be32-bafe32cbfcc7'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole', location = '{"lat":9.0147551,"lng":38.7835838}'
WHERE id = '9b45c302-6e42-424d-9fb1-965eac7c81ae'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Sheik Hussein', location = '{"lat":7.7466905,"lng":40.7074585}'
WHERE id = '9c2c28d9-abe6-49fc-84f7-cbe4015d7655'::uuid;

UPDATE public.destinations
SET region = 'Oromia', location = '{"lat":7.6120061,"lng":38.7629256}'
WHERE id = '9d095ae9-630c-4366-a967-537dd17b1062'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Arba Minch', location = '{"lat":6.0215142,"lng":37.5539809}'
WHERE id = '9d78ce5f-f785-4f8c-a063-26790078bebf'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Hana - Margo Mursi Bodie', location = '{"lat":6.2235574,"lng":36.1284585}'
WHERE id = '9e204ec0-8363-4d3e-9cf6-f44d8cb34e4b'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Yirga Cheffe', location = '{"lat":6.1529383,"lng":38.2023167}'
WHERE id = '9e3ba575-35e4-415c-8952-d54f1ffcf04c'::uuid;

UPDATE public.destinations
SET region = 'Tigray', location = '{"lat":14.25,"lng":38.91667}'
WHERE id = '9e43ef47-9766-48de-a223-dbb837559cda'::uuid;

UPDATE public.destinations
SET region = 'Sidama', city = 'Cheffe', location = '{"lat":7.0529428,"lng":38.4995556}'
WHERE id = '9ee64cf3-15be-44ed-b853-3265ccf3e729'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Jimma', location = '{"lat":7.6756152,"lng":36.8478779}'
WHERE id = '9f29e052-016b-4def-81d2-893b9b1dac54'::uuid;

UPDATE public.destinations
SET region = 'Oromia', location = '{"lat":8.1600308,"lng":39.1370309}'
WHERE id = '9f2b1214-5912-4aa3-baf1-cde511a0f0fc'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Bahir Dar Special Zone', location = '{"lat":11.6030239,"lng":37.3797987}'
WHERE id = '9f715fe1-efd5-4353-8eb1-f884ba3930fd'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bishoftu', location = '{"lat":8.750004,"lng":38.981734}'
WHERE id = '9fa2904a-22f7-4061-b474-cb5c0697c9f2'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole', location = '{"lat":9.0034887,"lng":38.8049675}'
WHERE id = '9fd08c2c-7be0-4324-a085-3e706038313a'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole', location = '{"lat":9.0034887,"lng":38.8049675}'
WHERE id = '9fd4b89d-dc4d-4d91-b7de-0a32141cc862'::uuid;

UPDATE public.destinations
SET region = 'Afar', city = 'Semera', location = '{"lat":11.7965635,"lng":41.0104744}'
WHERE id = 'a0221617-ca7f-4426-8818-1659c4e2d0ad'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Arba Minch', location = '{"lat":6.0215142,"lng":37.5539809}'
WHERE id = 'a0328609-3fe7-43fe-81a0-0aca483cdc68'::uuid;

COMMIT;
