-- Generated by scripts/enrich_destinations.py
-- Review destinations_enrichment_report.csv before applying.
BEGIN;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole', location = '{"lat":9.0060961,"lng":38.8111966}'
WHERE id = 'a054f916-a89b-4c4a-9799-236911eb8713'::uuid;

UPDATE public.destinations
SET region = 'Afar', city = 'Tendaho', location = '{"lat":11.5148566,"lng":40.9301381}'
WHERE id = 'a0f2eee3-35df-4e97-9555-49952c8adeb1'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos', location = '{"lat":9.0147265,"lng":38.767437}'
WHERE id = 'a0fc6e0a-530d-4b95-8df7-035f22f57412'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Ambo Zuria', location = '{"lat":8.7875309,"lng":37.8843326}'
WHERE id = 'a11a9666-01ed-422b-a2fd-6ad6a125a4b3'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Mek''elē', location = '{"lat":13.4929955,"lng":39.4729467}'
WHERE id = 'a1501a3d-7c66-4936-aa94-f785ea092633'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Gulale', location = '{"lat":9.0853416,"lng":38.7383628}'
WHERE id = 'a1a647e8-8e96-4985-81b5-841922a1c9f9'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Turmi', location = '{"lat":4.96835,"lng":36.487794}'
WHERE id = 'a209eb52-7fa4-43cf-97f8-891e26770368'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole', location = '{"lat":8.9985133,"lng":38.8092576}'
WHERE id = 'a2b6930f-8f3e-4366-a66e-b58fb09c9354'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Arba Minch', location = '{"lat":6.0215142,"lng":37.5539809}'
WHERE id = 'a310b843-e800-451d-9347-dacef53bf90a'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Gonder', location = '{"lat":12.6174164,"lng":37.4575171}'
WHERE id = 'a35b1ac5-02c8-4c8d-b3c5-1d5fa4718be2'::uuid;

UPDATE public.destinations
SET region = 'Somali', city = 'Jijiga', location = '{"lat":9.3595825,"lng":42.8011943}'
WHERE id = 'a3674094-06ce-460e-a0b5-794603a7574d'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole', location = '{"lat":9.0071908,"lng":38.8061823}'
WHERE id = 'a412401c-9edd-4790-9bf7-b5c4d4b14070'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Gorgora', location = '{"lat":12.2382669,"lng":37.2971393}'
WHERE id = 'a420fb0b-fa70-4247-89d8-6d03814c9a67'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Sheik Hussein', location = '{"lat":7.7466905,"lng":40.7074585}'
WHERE id = 'a471e427-7849-4b2f-b1ec-722588e9fbd2'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Axum', location = '{"lat":14.1422913,"lng":38.7292489}'
WHERE id = 'a4a27727-8501-4e4a-a377-2d947cb81ed6'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Sodere', location = '{"lat":8.4034494,"lng":39.3869748}'
WHERE id = 'a4ce71e3-c668-464a-a1d5-2b23c23a2ba5'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Lalibela', location = '{"lat":12.033783,"lng":39.0439966}'
WHERE id = 'a683a9af-809c-48ea-8732-e47bc46ab955'::uuid;

UPDATE public.destinations
SET region = 'Harar', city = 'Harar', location = '{"lat":9.3118304,"lng":42.1284009}'
WHERE id = 'a6938b22-e38d-4f39-9426-4a8d00eaad13'::uuid;

UPDATE public.destinations
SET region = 'Amhara', location = '{"lat":11.8635159,"lng":37.4908505}'
WHERE id = 'a69a4f2a-a69b-4d64-837c-5bf3eedd0c69'::uuid;

UPDATE public.destinations
SET region = 'Oromia', location = '{"lat":7.4047633,"lng":38.4271591}'
WHERE id = 'a69cdcf8-67e2-4923-82db-a3e87eef84a3'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bishoftu', location = '{"lat":8.7832477,"lng":38.9969502}'
WHERE id = 'a6c5fb8f-0f92-4ebd-a3bd-ef2205c31644'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Sodere', location = '{"lat":8.4034494,"lng":39.3869748}'
WHERE id = 'a6cf02c6-b55e-4988-aa17-3e8714b558f4'::uuid;

UPDATE public.destinations
SET region = 'Afar', location = '{"lat":14.2424728,"lng":40.2996919}'
WHERE id = 'a6d4fa71-f780-48c5-a115-162a08f816ca'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Jimma', location = '{"lat":7.6756152,"lng":36.8478779}'
WHERE id = 'a7875a12-13ae-4274-9563-4ecd05892b69'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Debre Libanos', location = '{"lat":9.7295697,"lng":38.8167682}'
WHERE id = 'a8036c35-608a-41ed-b286-62e4ee33a54b'::uuid;

UPDATE public.destinations
SET region = 'Amhara', location = '{"lat":10.7117887,"lng":37.8435035}'
WHERE id = 'a86ee5bc-cd7e-4a91-9f3e-7af4e40039d1'::uuid;

UPDATE public.destinations
SET region = 'South West Ethiopia Peoples', location = '{"lat":6.9042595,"lng":36.7301591}'
WHERE id = 'a9666c25-4c4b-4bdf-abd6-95ca09b2891f'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos', location = '{"lat":9.0159277,"lng":38.7712221}'
WHERE id = 'a97248f8-ff53-4f50-b569-89d1ab6a120b'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', location = '{"lat":5.25,"lng":37.5}'
WHERE id = 'aa0ffa48-cede-4d4c-999d-1fa870f9141c'::uuid;

UPDATE public.destinations
SET region = 'Oromia', location = '{"lat":7.5390028,"lng":38.5223013}'
WHERE id = 'aa7db2b3-e978-40ef-a447-af33678cf9f5'::uuid;

UPDATE public.destinations
SET region = 'Sidama', city = 'Hawassa', location = '{"lat":7.0481029,"lng":38.47861}'
WHERE id = 'aa84c129-93c8-46c3-9bae-2abbb64d8ba9'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos', location = '{"lat":9.0047069,"lng":38.7670633}'
WHERE id = 'aaedbac4-8136-41c0-a679-f9159aa9705d'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos', location = '{"lat":9.0100868,"lng":38.7640678}'
WHERE id = 'aaf39f24-f344-4aca-b02c-7987205bd9e5'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Gulale', location = '{"lat":9.0507285,"lng":38.7611956}'
WHERE id = 'ab036e39-48a4-4f83-927e-c6f35dc44a70'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Yabēlo', location = '{"lat":4.8888074,"lng":38.109828}'
WHERE id = 'ab05f92d-9430-45db-b067-57f3f5e9d21f'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Debre Libanos', location = '{"lat":9.7120303,"lng":38.8475576}'
WHERE id = 'ab294bec-dde6-4d2e-973b-41b9fa7a5c40'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Axum', location = '{"lat":14.1422913,"lng":38.7292489}'
WHERE id = 'ab47d58d-c48f-4c55-a084-1ba86d43c53f'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole', location = '{"lat":9.0034887,"lng":38.8049675}'
WHERE id = 'ab60729b-f045-4435-9031-abb6c44a6012'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Lalibela', location = '{"lat":12.0432542,"lng":39.0370149}'
WHERE id = 'ab6fe8ad-0f59-495f-9f3c-73eb7e36689a'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', location = '{"lat":5.25,"lng":37.5}'
WHERE id = 'abad81e9-d84c-4846-b88c-ab64a36b4327'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Debre Tabor', location = '{"lat":11.856591,"lng":38.008309}'
WHERE id = 'ac27be0e-8dd4-447c-a6b6-468b6493eda9'::uuid;

UPDATE public.destinations
SET region = 'Sidama', city = 'Hawassa', location = '{"lat":7.0673591,"lng":38.4978857}'
WHERE id = 'acc97225-1dff-49dc-a5db-bb0fc854c20d'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos', location = '{"lat":9.0141275,"lng":38.7521409}'
WHERE id = 'acd40618-1c52-483a-a8c0-23714e3c91e5'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Arba Minch', location = '{"lat":6.0659447,"lng":37.5600365}'
WHERE id = 'acf58a47-0296-4e95-919c-ae9d881e6d38'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ababa', location = '{"lat":9.0236603,"lng":38.7595819}'
WHERE id = 'acfaedcc-5bc8-469b-bad3-f73791526690'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Tis Abay', location = '{"lat":11.4878798,"lng":37.5875677}'
WHERE id = 'ad051875-a9c0-4a60-bf71-6adfacb5838d'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Adama', location = '{"lat":8.5408627,"lng":39.2655724}'
WHERE id = 'ad5f9af1-939c-4e66-9aa6-9a34757052b2'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Bahir Dar Special Zone', location = '{"lat":11.5957145,"lng":37.3854336}'
WHERE id = 'ad9d5a61-da3f-4a35-a9c4-76027dd54cee'::uuid;

UPDATE public.destinations
SET region = 'Afar', city = 'Asaita', location = '{"lat":11.5653325,"lng":41.4385892}'
WHERE id = 'ada48223-5661-467d-a0ad-52e36324390a'::uuid;

UPDATE public.destinations
SET region = 'Amhara', location = '{"lat":10.51667,"lng":39.76667}'
WHERE id = 'ae586ea6-be22-47cb-a0b6-79775802dc87'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Axum', location = '{"lat":14.1220982,"lng":38.7321749}'
WHERE id = 'ae74983d-a9e2-4b1a-a5ef-5be62fc8eabb'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Jimma', location = '{"lat":7.6756152,"lng":36.8478779}'
WHERE id = 'aea4a4cd-8591-40dd-b241-2a03c7d8111c'::uuid;

UPDATE public.destinations
SET region = 'Afar', city = 'Asaita', location = '{"lat":11.5653325,"lng":41.4385892}'
WHERE id = 'b072f551-6080-47a8-913d-931ec74cf1f0'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Felegsha', location = '{"lat":13.8755536,"lng":39.5987026}'
WHERE id = 'b1ac8823-6c29-45f3-99a5-ca887fb8be27'::uuid;

UPDATE public.destinations
SET region = 'Sidama', city = 'Hawassa', location = '{"lat":7.0481029,"lng":38.47861}'
WHERE id = 'b1fbbc83-92ee-4466-9cd9-43b7a4bbb880'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bedele', location = '{"lat":8.455645,"lng":36.352545}'
WHERE id = 'b24ddf98-b79e-47d6-9c19-e9aba66cebe1'::uuid;

UPDATE public.destinations
SET region = 'Gambela', city = 'Gambela', location = '{"lat":8.2503656,"lng":34.5877344}'
WHERE id = 'b24f6732-55ea-4196-bbaf-a6ff017a7104'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Bahir Dar', location = '{"lat":11.608003,"lng":37.3699025}'
WHERE id = 'b28cd2b2-a2df-4c8c-841a-3db9cfdeab88'::uuid;

UPDATE public.destinations
SET region = 'South West Ethiopia Peoples', city = 'Bonga', location = '{"lat":7.2645383,"lng":36.2460526}'
WHERE id = 'b61e5b08-c91d-4ce2-bba1-6fa553d26f78'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Sendafa', location = '{"lat":9.155868,"lng":39.023811}'
WHERE id = 'b6aecfe1-84e4-4370-8992-304f2c4a9c25'::uuid;

UPDATE public.destinations
SET region = 'Amhara', location = '{"lat":11.9507719,"lng":37.294878}'
WHERE id = 'b7b844b3-22fb-437a-8e8f-627a9593794e'::uuid;

UPDATE public.destinations
SET region = 'Amhara', location = '{"lat":13.2458802,"lng":38.0999456}'
WHERE id = 'b87059a5-5673-48c5-839a-b2b0997a6f55'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Jimma', location = '{"lat":7.6792877,"lng":36.8533248}'
WHERE id = 'b89ac6af-28f2-42d9-affc-ec736d03d69a'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Ambo', location = '{"lat":8.982104,"lng":37.8554406}'
WHERE id = 'b97358c0-f417-43e9-9de8-bedfd44c3f28'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bishoftu', location = '{"lat":8.750004,"lng":38.981734}'
WHERE id = 'ba25d77c-f5de-4608-b79c-4045fed750c3'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Arba Minch', location = '{"lat":6.0215142,"lng":37.5539809}'
WHERE id = 'ba3f6a9e-2205-40e9-a44f-57a2416dc874'::uuid;

UPDATE public.destinations
SET region = 'Oromia', location = '{"lat":7.6120061,"lng":38.7629256}'
WHERE id = 'ba9f56d3-b00a-4c7a-8531-0833b494f3cd'::uuid;

UPDATE public.destinations
SET region = 'Central Ethiopia Regional State', city = 'Durame', location = '{"lat":7.2438769,"lng":37.9049922}'
WHERE id = 'bca8a498-3c19-46be-b940-475794956631'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Gonder', location = '{"lat":12.610368,"lng":37.466766}'
WHERE id = 'bf322d22-992f-4e90-9a6b-135d8559f6cf'::uuid;

UPDATE public.destinations
SET region = 'Sidama', city = 'Hawassa', location = '{"lat":7.0481029,"lng":38.47861}'
WHERE id = 'c169a18c-4de9-4748-84b7-aa3b16fc0e67'::uuid;

UPDATE public.destinations
SET region = 'Oromia', location = '{"lat":8.0316904,"lng":37.5949265}'
WHERE id = 'c1a6a16f-b964-4020-996f-e52242832066'::uuid;

UPDATE public.destinations
SET region = 'Gambela', city = 'Gambela', location = '{"lat":8.2503656,"lng":34.5877344}'
WHERE id = 'c1f3f587-83ba-4f98-be06-5fd54d0b7d3b'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bishoftu', location = '{"lat":8.750004,"lng":38.981734}'
WHERE id = 'c2e0d3b0-1dd9-4031-845b-7d765123d934'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Debre Libanos', location = '{"lat":9.7120303,"lng":38.8475576}'
WHERE id = 'c4da7498-1ddf-4c3c-9f0e-cfa8e976aed0'::uuid;

UPDATE public.destinations
SET region = 'Amhara', location = '{"lat":13.2458802,"lng":38.0999456}'
WHERE id = 'c69c8eff-ee2c-473f-8102-5e00f9f366f3'::uuid;

UPDATE public.destinations
SET region = 'Benishangul-Gumuz', city = 'Assosa', location = '{"lat":10.0646352,"lng":34.5437024}'
WHERE id = 'c6e3c14d-8389-4905-8674-ce35539ea16b'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', location = '{"lat":5.835358,"lng":37.568742}'
WHERE id = 'c7b77278-f7c6-434d-ab40-d4435aa9aee4'::uuid;

UPDATE public.destinations
SET region = 'Amhara', location = '{"lat":13.2364263,"lng":38.3684558}'
WHERE id = 'c8018a74-ffd7-4341-a735-7a7041108187'::uuid;

UPDATE public.destinations
SET region = 'Gambela', city = 'Gambela', location = '{"lat":8.2503656,"lng":34.5877344}'
WHERE id = 'c89ff16a-7e73-433c-bf47-61a47da76fb9'::uuid;

UPDATE public.destinations
SET region = 'Sidama', city = 'Hawassa', location = '{"lat":7.0481029,"lng":38.47861}'
WHERE id = 'c9975165-c30b-4042-a1cc-702150fece87'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Lideta', location = '{"lat":9.0020475,"lng":38.7235554}'
WHERE id = 'c9a05a72-07be-48ff-9b30-486f79cc9dc3'::uuid;

UPDATE public.destinations
SET region = 'Harar', city = 'Harar', location = '{"lat":9.3118304,"lng":42.1284009}'
WHERE id = 'ca093e05-7e32-465f-af28-9bae848b0b22'::uuid;

UPDATE public.destinations
SET region = 'Afar', location = '{"lat":10.953845,"lng":40.7470623}'
WHERE id = 'ca107b8f-38d9-463b-93fa-900d3dc3c7ea'::uuid;

UPDATE public.destinations
SET region = 'Amhara', location = '{"lat":12.1520426,"lng":35.5789699}'
WHERE id = 'ca8b058d-8a0f-4be6-a308-b19e065fcc52'::uuid;

UPDATE public.destinations
SET region = 'Harar', city = 'Harar', location = '{"lat":9.3118304,"lng":42.1284009}'
WHERE id = 'cae2a2ec-99ff-42d8-a1f2-e6adcbc1d210'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Jimma', location = '{"lat":7.6792877,"lng":36.8533248}'
WHERE id = 'cafeeec4-78c6-4d43-a466-5143963694a9'::uuid;

UPDATE public.destinations
SET region = 'Amhara', location = '{"lat":11.9507719,"lng":37.294878}'
WHERE id = 'cb6263ff-6d91-4ec3-b653-624f067d0a72'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole', location = '{"lat":8.9844824,"lng":38.7779038}'
WHERE id = 'cb88aaea-a723-4a93-9787-1e7974f21a6b'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ababa', location = '{"lat":9.0358119,"lng":38.7524315}'
WHERE id = 'cbf61002-7255-40ff-8c84-916440b60555'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Humera', location = '{"lat":14.2876868,"lng":36.6088415}'
WHERE id = 'ccd96c6a-653b-4b49-b89d-ad46f0fdbfb5'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Sululta', location = '{"lat":9.1080861,"lng":38.8193556}'
WHERE id = 'cd92f038-c21a-441d-9a30-b1f45c8c7f06'::uuid;

UPDATE public.destinations
SET region = 'South West Ethiopia Peoples', city = 'Bonga', location = '{"lat":7.2645383,"lng":36.2460526}'
WHERE id = 'cd97858d-7037-4d55-adb0-5a02849abdb7'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Sululta', location = '{"lat":9.1080861,"lng":38.8193556}'
WHERE id = 'cdc31095-fd44-4139-946a-c3dfdcdd0b5e'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Sululta', location = '{"lat":9.1080861,"lng":38.8193556}'
WHERE id = 'ce27af69-9b78-4eed-be46-2f16e237ef30'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Sululta', location = '{"lat":9.1080861,"lng":38.8193556}'
WHERE id = 'cf28194b-f40c-4afe-91c8-1d98b22fde6a'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Arba Minch', location = '{"lat":6.0215142,"lng":37.5539809}'
WHERE id = 'cf918c3c-bd90-411d-88d6-ac3e9c4a59a8'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ababa', location = '{"lat":9.0358119,"lng":38.7524315}'
WHERE id = 'd08196bd-3d5d-4036-9f21-892902b23899'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Tiya', location = '{"lat":8.437331,"lng":38.609296}'
WHERE id = 'd14f5e73-2d24-4e2d-9c2e-684649b58120'::uuid;

UPDATE public.destinations
SET region = 'South West Ethiopia Peoples', city = 'Bonga', location = '{"lat":7.2645383,"lng":36.2460526}'
WHERE id = 'd1fcf8af-7f2d-48fe-aaaa-640788f75ffa'::uuid;

UPDATE public.destinations
SET region = 'Benishangul-Gumuz', city = 'Assosa', location = '{"lat":10.0646352,"lng":34.5437024}'
WHERE id = 'd2308de5-fb96-44af-b084-3c50311dbf52'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Sebatamit', location = '{"lat":11.5250362,"lng":37.4002724}'
WHERE id = 'd3572147-baed-4397-b69a-380ec7a58894'::uuid;

UPDATE public.destinations
SET region = 'Sidama', city = 'Hawassa', location = '{"lat":7.0481029,"lng":38.47861}'
WHERE id = 'd40f95e9-ebb1-48a5-9d82-b405882ae682'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Wolaita Sodo', location = '{"lat":6.8577533,"lng":37.7578499}'
WHERE id = 'd58e4ea2-e53f-46dc-ac71-74e34a197f27'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Dessie', location = '{"lat":11.122604,"lng":39.634982}'
WHERE id = 'd6b3ee59-b0d1-42ec-9ec1-6e2edb0335d8'::uuid;

UPDATE public.destinations
SET region = 'Harar', city = 'Harar', location = '{"lat":9.3118304,"lng":42.1284009}'
WHERE id = 'd7f5a624-739b-41fd-b8e1-892b02e83a62'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Ankober', location = '{"lat":9.5911547,"lng":39.7338213}'
WHERE id = 'd9060840-28ba-48c8-8e9e-54a647b5c49f'::uuid;

UPDATE public.destinations
SET region = 'Benishangul-Gumuz', city = 'Assosa', location = '{"lat":10.0646352,"lng":34.5437024}'
WHERE id = 'd9c33e5f-b8ad-41c5-b07f-00fcb967bd10'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Ankober', location = '{"lat":9.5911547,"lng":39.7338213}'
WHERE id = 'da70a43d-429f-4e57-a02b-51f7d4ae990b'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ketema', location = '{"lat":9.0431757,"lng":38.723931}'
WHERE id = 'da831cda-4c1d-4ed2-b618-29e712ef9443'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Arba Minch', location = '{"lat":6.0215142,"lng":37.5539809}'
WHERE id = 'dbaf8569-c376-4600-b4f1-4fbbd65a7342'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Goba', location = '{"lat":7.0073251,"lng":39.9694204}'
WHERE id = 'dbd1d649-dee6-4d21-b919-375f7640111f'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Debre Libanos', location = '{"lat":9.7120303,"lng":38.8475576}'
WHERE id = 'dbe91004-6fc5-4257-9308-9cc595ac0057'::uuid;

UPDATE public.destinations
SET region = 'Benishangul-Gumuz', city = 'Assosa', location = '{"lat":10.0646352,"lng":34.5437024}'
WHERE id = 'dc000e55-c905-48f5-85ec-081dcf26edd1'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bishoftu', location = '{"lat":8.750004,"lng":38.981734}'
WHERE id = 'dcce7b3d-71ff-490e-b2ad-5dde6d5f7c9c'::uuid;

UPDATE public.destinations
SET region = 'Amhara', location = '{"lat":10.3511111,"lng":39.7959722}'
WHERE id = 'dd373029-f367-4677-9213-c7074713ac9d'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Dendi', location = '{"lat":8.9347933,"lng":38.1236741}'
WHERE id = 'dfeeb2c0-b6a8-45d6-bbd7-149e0848373a'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Jibat', location = '{"lat":8.7435984,"lng":37.4727901}'
WHERE id = 'e088bf30-3862-40b0-98c5-ff9093204c93'::uuid;

UPDATE public.destinations
SET region = 'Afar', location = '{"lat":14.2424728,"lng":40.2996919}'
WHERE id = 'e16cab51-6ff7-4411-8838-d9c7f44a3a6d'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Tiya', location = '{"lat":8.437331,"lng":38.609296}'
WHERE id = 'e225fcf9-c537-426c-bf36-c2d4681477b2'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Tiya', location = '{"lat":8.437331,"lng":38.609296}'
WHERE id = 'e287794e-e687-46bd-8c89-a0fd0a991ddd'::uuid;

UPDATE public.destinations
SET region = 'Oromia', location = '{"lat":5.0,"lng":37.0}'
WHERE id = 'e3442236-676c-47fc-b4ac-1a07a49cc3e9'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Yeha', location = '{"lat":14.2859622,"lng":39.0179108}'
WHERE id = 'e43e4909-b137-48b4-8547-494e60b916cb'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ababa', location = '{"lat":9.0358119,"lng":38.7524315}'
WHERE id = 'e48e38f3-4bc6-4813-bc19-ebb73f341bba'::uuid;

UPDATE public.destinations
SET region = 'Amhara', location = '{"lat":11.9507719,"lng":37.294878}'
WHERE id = 'e5616ade-a78a-4848-8707-767599849de4'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Sawla', location = '{"lat":6.3,"lng":36.88333}'
WHERE id = 'e6a71555-87d2-47cc-8e94-e4e7448720de'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Dessie', location = '{"lat":11.122604,"lng":39.634982}'
WHERE id = 'e74aec4a-cdcd-4719-8afa-dda297aefca6'::uuid;

UPDATE public.destinations
SET region = 'South West Ethiopia Peoples', city = 'Bonga', location = '{"lat":7.2645383,"lng":36.2460526}'
WHERE id = 'e805e290-ebae-4a5b-a71d-229842a165fb'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ababa', location = '{"lat":9.0379782,"lng":38.7618606}'
WHERE id = 'e81593e7-1a80-422a-806d-e7166b95dd4b'::uuid;

UPDATE public.destinations
SET region = 'Afar', location = '{"lat":11.1711957,"lng":41.7873451}'
WHERE id = 'e87aea51-547a-4d61-9a2b-23633a6efd90'::uuid;

UPDATE public.destinations
SET region = 'Amhara', location = '{"lat":11.9507719,"lng":37.294878}'
WHERE id = 'e8a409e6-5891-4fe6-8616-1f0561d86892'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Sululta', location = '{"lat":9.1080861,"lng":38.8193556}'
WHERE id = 'e92f2113-aa5c-4746-8711-c467e756133e'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bishoftu', location = '{"lat":8.750004,"lng":38.981734}'
WHERE id = 'e963b6cc-ebf5-4a41-8c8c-f2962eded182'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Bahir Dar Special Zone', location = '{"lat":11.5949663,"lng":37.3882251}'
WHERE id = 'ea0ba2f3-930b-4f23-9921-651d6ffc8be6'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Jimma', location = '{"lat":7.6756152,"lng":36.8478779}'
WHERE id = 'ea5a585b-cd87-41c9-a60c-52ef5ed6d716'::uuid;

UPDATE public.destinations
SET region = 'Oromia', location = '{"lat":7.6120061,"lng":38.7629256}'
WHERE id = 'ea95cafa-c224-4b52-99de-4e124eca5483'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bekoji', location = '{"lat":7.53333,"lng":39.25}'
WHERE id = 'ea9c4823-337f-4fa7-83f1-4f8c613bf54c'::uuid;

UPDATE public.destinations
SET region = 'Somali', city = 'Jijiga', location = '{"lat":9.3508526,"lng":42.8003788}'
WHERE id = 'eab7d110-b8f3-4f20-b2d2-c074be48d63d'::uuid;

UPDATE public.destinations
SET region = 'Oromia', location = '{"lat":5.0,"lng":37.0}'
WHERE id = 'ebf1a4c1-7721-498d-891d-f315b78f02a6'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos', location = '{"lat":9.0102293,"lng":38.7606309}'
WHERE id = 'ec22ddef-81bc-4ab1-bc33-c3f8d72bf7c9'::uuid;

UPDATE public.destinations
SET region = 'Sidama', city = 'Hawassa', location = '{"lat":7.0481029,"lng":38.47861}'
WHERE id = 'ecc39e6b-1161-445e-afd8-c5cec07e3a89'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Nefas Silk', location = '{"lat":8.9838715,"lng":38.7380028}'
WHERE id = 'ecfc43b1-9721-4ef9-9916-eaa9849a8fc7'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Axum', location = '{"lat":14.1220982,"lng":38.7321749}'
WHERE id = 'ed633c8c-49bc-4e51-8d0f-4f4f8ef7470f'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Dessie', location = '{"lat":11.122604,"lng":39.634982}'
WHERE id = 'ee73dcca-d489-42d1-bb33-da72503e05c6'::uuid;

UPDATE public.destinations
SET region = 'South West Ethiopia Peoples', city = 'Bonga', location = '{"lat":7.2645383,"lng":36.2460526}'
WHERE id = 'ef501534-2aa3-406d-af92-d48f0b23db1a'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Adama', location = '{"lat":8.5410261,"lng":39.2705461}'
WHERE id = 'efa805e9-ec74-4111-b642-71d1f68e8944'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Ankober', location = '{"lat":9.5911547,"lng":39.7338213}'
WHERE id = 'f1b2eed3-1c68-4a61-94c5-c19315a48c1d'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bishoftu', location = '{"lat":8.750004,"lng":38.981734}'
WHERE id = 'f20aefba-6c93-4e33-b33e-56dbc2023015'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Sawla', location = '{"lat":6.3,"lng":36.88333}'
WHERE id = 'f2323e8e-c2d2-4006-9519-93bf1cb00e94'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Ankober', location = '{"lat":9.5911547,"lng":39.7338213}'
WHERE id = 'f242dbb6-f609-40a1-8e22-7a8fa0ecdb65'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bishoftu', location = '{"lat":8.750004,"lng":38.981734}'
WHERE id = 'f2bf3376-ee72-4135-a2f0-b25e76371d50'::uuid;

UPDATE public.destinations
SET region = 'Oromia', location = '{"lat":6.7134709,"lng":39.7257306}'
WHERE id = 'f2ec6eeb-5f2e-4321-90af-393ed36d7387'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Arba Minch', location = '{"lat":6.0215142,"lng":37.5539809}'
WHERE id = 'f523892d-a1ff-415a-bcc3-d9e91d48f73c'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Axum', location = '{"lat":14.1220982,"lng":38.7321749}'
WHERE id = 'f5598e75-4d99-4bbb-8542-8973730acbd7'::uuid;

UPDATE public.destinations
SET region = 'Afar', location = '{"lat":13.6030321,"lng":40.6634086}'
WHERE id = 'f74134b4-4bc5-4a9e-a55a-a3fcca665db5'::uuid;

UPDATE public.destinations
SET region = 'Gambela', city = 'Gambela', location = '{"lat":8.2503656,"lng":34.5877344}'
WHERE id = 'f76074bd-f01a-4a71-ac18-b80b20754a75'::uuid;

UPDATE public.destinations
SET region = 'Oromia', location = '{"lat":6.7942161,"lng":39.7565574}'
WHERE id = 'f838def2-16ed-4546-b32f-97336cfd5fdb'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Wukro', location = '{"lat":13.7862549,"lng":39.601525}'
WHERE id = 'f8fc9957-1134-4746-8b3b-163e33e44218'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Arba Minch', location = '{"lat":6.0215142,"lng":37.5539809}'
WHERE id = 'fa770e9d-85b7-40dd-94b9-fd9d3f259882'::uuid;

UPDATE public.destinations
SET region = 'Harar', city = 'Harar', location = '{"lat":9.3118304,"lng":42.1284009}'
WHERE id = 'fa918efc-1c60-4de2-af6a-aeca9f89c8df'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Gonder', location = '{"lat":12.610368,"lng":37.466766}'
WHERE id = 'fb513339-93d3-4c0d-ac68-2bed64c29016'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Sululta', location = '{"lat":9.1080861,"lng":38.8193556}'
WHERE id = 'fb62bd51-4233-4ac4-8348-f47a9b9c1ebb'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Sululta', location = '{"lat":9.1080861,"lng":38.8193556}'
WHERE id = 'fd1a2aff-f66a-4de6-adc8-55b0c7c6f77e'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Kindo Koysha', location = '{"lat":6.933691,"lng":37.5892615}'
WHERE id = 'fd6cfc99-458f-4dfc-bd77-f6720ecfb327'::uuid;

UPDATE public.destinations
SET region = 'Oromia', location = '{"lat":8.0316904,"lng":37.5949265}'
WHERE id = 'fd70affa-c62c-4892-8eed-fc976450ce69'::uuid;

UPDATE public.destinations
SET region = 'South West Ethiopia Peoples', city = 'Bonga', location = '{"lat":7.2645383,"lng":36.2460526}'
WHERE id = 'fdd4bb48-c039-4b1b-a7a4-acf5b2b2b81f'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bishoftu', location = '{"lat":8.750004,"lng":38.981734}'
WHERE id = 'fdd810f1-c4fb-4188-8646-d3d28ff84471'::uuid;

UPDATE public.destinations
SET region = 'Afar', location = '{"lat":13.6030321,"lng":40.6634086}'
WHERE id = 'fdf6e1fb-0195-4081-b0e2-bb21501d95ae'::uuid;

UPDATE public.destinations
SET region = 'Oromia', location = '{"lat":7.6120061,"lng":38.7629256}'
WHERE id = 'feb50060-1608-4cda-bf5f-d395da4818af'::uuid;

UPDATE public.destinations
SET region = 'Afar', location = '{"lat":13.6030321,"lng":40.6634086}'
WHERE id = 'ff8cbf83-f899-4c5c-aa5d-6c7796a0b61d'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ababa', location = '{"lat":9.0358119,"lng":38.7524315}'
WHERE id = 'ffe16577-526f-4996-aa2d-bea0f45c4e41'::uuid;

COMMIT;
