-- Generated by scripts/enrich_destinations.py
-- Review destinations_enrichment_report.csv before applying.
BEGIN;

UPDATE public.destinations
SET region = 'Oromia', city = 'Asela', location = '{"lat":7.9677229,"lng":39.1327111}'
WHERE id = '00e4f04e-be64-4f35-8e8f-41d59df6a948'::uuid;

COMMIT;
