-- Generated by scripts/enrich_destinations_google.py
BEGIN;

UPDATE public.destinations
SET region = 'Oromia', city = 'Ambo', location = '{"lat":9.077867699999999,"lng":38.588705700000006}'
WHERE id = '000b9cf0-b53f-4546-8840-ba364d586682'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Gondar', location = '{"lat":12.609496000000002,"lng":37.470178}'
WHERE id = '0051e3e0-cdf6-4292-8b3f-55e0cf27bec7'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Asela', location = '{"lat":7.969162799999999,"lng":39.131521}'
WHERE id = '00e4f04e-be64-4f35-8e8f-41d59df6a948'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Gulele', location = '{"lat":9.0469448,"lng":38.7577717}'
WHERE id = '0d1058d2-0ac5-4f62-904a-86b77a783a9f'::uuid;

UPDATE public.destinations
SET region = 'Sidama', city = 'Awasa', location = '{"lat":7.0795884,"lng":38.479093899999995}'
WHERE id = '0deb4635-ec6e-41d1-95cf-f0b0d2389259'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Arba Minch', location = '{"lat":6.029646199999999,"lng":37.5918419}'
WHERE id = '0e95b8df-daa1-4410-a730-189befba6f99'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'East Shewa', location = '{"lat":7.9265107,"lng":38.7552253}'
WHERE id = '14fcb4c1-abbd-41c3-b00f-cf1decb0777c'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Sululta', location = '{"lat":9.103813599999999,"lng":38.7109595}'
WHERE id = '1776863c-a67a-47a1-a39b-1ff5f28972a2'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Mekele', location = '{"lat":13.4960787,"lng":39.4570393}'
WHERE id = '20833650-32b4-4b1e-8aab-7d9b3fb8e27c'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Mekele', location = '{"lat":13.4964142,"lng":39.460983299999995}'
WHERE id = '21432d95-30dd-40e4-9388-ee6133851758'::uuid;

UPDATE public.destinations
SET region = 'Harar', city = 'Jegol', location = '{"lat":9.3109748,"lng":42.138774399999996}'
WHERE id = '220cc188-0798-45da-a7d9-80c1885886e2'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Arba Minch', location = '{"lat":6.009771799999999,"lng":37.5553594}'
WHERE id = '2c71cbff-592a-4424-9657-eade98bf9987'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Mekele', location = '{"lat":13.4964142,"lng":39.460983299999995}'
WHERE id = '2ceb15dd-7be7-413f-9582-0f9d00bf115b'::uuid;

COMMIT;
