-- Generated by scripts/enrich_destinations.py
-- Review destinations_enrichment_report.csv before applying.
BEGIN;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bishoftu', location = '{"lat":8.7873711,"lng":38.9931534}'
WHERE id = '10a673a7-4637-4406-b3ce-1ba3b0959686'::uuid;

UPDATE public.destinations
SET region = 'South West Ethiopia Peoples', location = '{"lat":7.4231767,"lng":35.4344487}'
WHERE id = '10aad439-21ab-49ae-bad6-cd8d0e02d12f'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Gidole', location = '{"lat":5.6505459,"lng":37.3660534}'
WHERE id = '10cae156-391a-4c15-9fa6-2d9adfd70352'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole', location = '{"lat":8.9954956,"lng":38.8143721}'
WHERE id = '113b58ce-45b5-4569-89d4-f5f7ca88df14'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Arba Minch', location = '{"lat":6.02604,"lng":37.56775}'
WHERE id = '1199349e-9884-4cf4-9829-6629cbdc454a'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Arsi Negelle', location = '{"lat":7.5919956,"lng":38.6913141}'
WHERE id = '11d5d687-cf9d-4d2e-80fa-c16dc4bc2d07'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Adama', location = '{"lat":8.5410261,"lng":39.2705461}'
WHERE id = '123cfd93-3039-4f07-a333-891d1dae1ff3'::uuid;

UPDATE public.destinations
SET region = 'South West Ethiopia Peoples', city = 'Masha', location = '{"lat":7.747454,"lng":35.475953}'
WHERE id = '128ea5e5-e0c7-4b55-ab19-15fcaa579189'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Gorgora', location = '{"lat":12.2382669,"lng":37.2971393}'
WHERE id = '128fc595-bc5c-412c-9acb-c322347df6f3'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos', location = '{"lat":9.0100868,"lng":38.7640678}'
WHERE id = '12d7c2e5-6f22-407c-b6f5-f9d62a3f7e4f'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Gonder', location = '{"lat":12.610368,"lng":37.466766}'
WHERE id = '142fb748-0f18-4bf9-841b-11aa0b15611d'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Dorze', location = '{"lat":6.1948568,"lng":37.5743447}'
WHERE id = '146f6075-c877-4699-affe-e3d724587aa7'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Yabēlo', location = '{"lat":4.8888074,"lng":38.109828}'
WHERE id = '148034e4-7fe4-4dad-8d25-5be713fff5fe'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Lalibela', location = '{"lat":12.0360639,"lng":39.0456845}'
WHERE id = '14cd6748-c252-4f1d-af1b-7145c3d63012'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Felegsha', location = '{"lat":13.8755536,"lng":39.5987026}'
WHERE id = '14f1955f-8954-4783-bac3-6c65d261f23b'::uuid;

UPDATE public.destinations
SET region = 'South West Ethiopia Peoples', location = '{"lat":6.9042595,"lng":36.7301591}'
WHERE id = '151689f0-1345-4c94-8b5e-4cf3b59dfae8'::uuid;

UPDATE public.destinations
SET region = 'Afar', city = 'Semera', location = '{"lat":11.7923098,"lng":41.0089155}'
WHERE id = '154e92cf-82ab-4022-9339-7a382efd7a69'::uuid;

UPDATE public.destinations
SET region = 'Oromia', location = '{"lat":8.93278,"lng":41.80361}'
WHERE id = '155560ee-ef59-4e8f-9b0a-da01cfb2db33'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos', location = '{"lat":9.0094467,"lng":38.7533049}'
WHERE id = '15580d30-aaf4-41e6-8928-1b7ce0c5b9d7'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Gonder', location = '{"lat":12.610368,"lng":37.466766}'
WHERE id = '15b19af3-fa80-42e8-a887-582c31528014'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole', location = '{"lat":8.9822541,"lng":38.8383871}'
WHERE id = '160260ef-113c-4092-b084-b9344923802e'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Walmara', location = '{"lat":8.96667,"lng":38.53333}'
WHERE id = '160cbdd9-963a-4959-8f22-f565a0621de3'::uuid;

UPDATE public.destinations
SET region = 'Somali', location = '{"lat":4.5638106,"lng":40.1494701}'
WHERE id = '1618e41c-dd41-468c-bc4d-eb68f0980534'::uuid;

UPDATE public.destinations
SET region = 'South West Ethiopia Peoples', city = 'Wushwush', location = '{"lat":7.3004291,"lng":36.1404862}'
WHERE id = '16716603-1c73-4a69-b4e5-aa9673c399fd'::uuid;

UPDATE public.destinations
SET region = 'Sidama', city = 'Hawassa', location = '{"lat":7.0549266,"lng":38.4674463}'
WHERE id = '16c62e77-ebbe-46f9-ac95-2a3784f4b47b'::uuid;

UPDATE public.destinations
SET region = 'Amhara', location = '{"lat":10.3511111,"lng":39.7959722}'
WHERE id = '171119ef-dd22-425f-93bc-654ef09a656a'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Hayq', location = '{"lat":11.3131688,"lng":39.676983}'
WHERE id = '175f8db8-fab1-4154-8709-8b21e6b308e7'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Sheik Hussein', location = '{"lat":7.7463399,"lng":40.7036365}'
WHERE id = '1802b841-f5a4-49fe-9c32-efbd4b5e966e'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Keyafer', location = '{"lat":5.5224108,"lng":36.735446}'
WHERE id = '184162e1-10f4-47c4-8df2-43e9baef7374'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Arbore', location = '{"lat":4.9932363,"lng":36.8500074}'
WHERE id = '1861714b-d99d-45db-9295-7a295c30b79f'::uuid;

UPDATE public.destinations
SET region = 'Sidama', city = 'Hawassa', location = '{"lat":7.0235129,"lng":38.4684384}'
WHERE id = '18e7ff60-d9b4-4951-b88f-f1881b20abad'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Lideta', location = '{"lat":9.0203258,"lng":38.7530817}'
WHERE id = '1976295f-ecce-48f7-bbc3-cc4f1b53fef3'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Halah Gheralta', location = '{"lat":13.7478418,"lng":39.2536119}'
WHERE id = '1a0fe466-2e4e-4af5-8db4-43be8bea6df0'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos', location = '{"lat":9.0098207,"lng":38.7461551}'
WHERE id = '1a209072-6ad4-4054-a3d1-7a60411b1120'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Dimeka', location = '{"lat":5.1744266,"lng":36.5484885}'
WHERE id = '1a38eefe-828e-469c-ae8b-5bbe525db738'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Debre Markos', location = '{"lat":10.3376947,"lng":37.7304366}'
WHERE id = '1a3d3411-dd15-4ebd-87ad-be817055defb'::uuid;

UPDATE public.destinations
SET region = 'Afar', location = '{"lat":9.5,"lng":39.95}'
WHERE id = '1a3def45-0960-4282-bebd-627a7cb980c4'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Gore', location = '{"lat":8.1525979,"lng":35.5371154}'
WHERE id = '1a96e60a-57ff-432a-8daf-6e94fe955bc4'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Ankober', location = '{"lat":9.5911547,"lng":39.7338213}'
WHERE id = '1b0cc407-865c-4661-94dd-c1fcd6c13494'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', location = '{"lat":5.25,"lng":37.5}'
WHERE id = '1b0dae3c-22ba-4e5d-ba89-22160801cca4'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Metehara', location = '{"lat":8.8975378,"lng":39.917039}'
WHERE id = '1bd34702-eb28-425c-b0e5-4fadf009287a'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole', location = '{"lat":8.9944093,"lng":38.7953528}'
WHERE id = '1bf2d847-791f-4a70-be57-01108f2f4871'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Dorze', location = '{"lat":6.1948568,"lng":37.5743447}'
WHERE id = '1c3acc4f-bf27-4343-953d-1d0001863ed7'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Dinsho', location = '{"lat":7.108213,"lng":39.780153}'
WHERE id = '1c4be61c-293b-40b7-90c5-85d159009ee5'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Lalibela', location = '{"lat":12.0360639,"lng":39.0456845}'
WHERE id = '1c917664-8092-4e3f-ba11-abce35e97266'::uuid;

UPDATE public.destinations
SET region = 'Sidama', city = 'Wondo Genet', location = '{"lat":7.0854757,"lng":38.6141113}'
WHERE id = '1d8c6efd-f46e-47dd-beaa-68f0ecb56f51'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Arba Minch', location = '{"lat":6.0215142,"lng":37.5539809}'
WHERE id = '1dcd5529-5ebf-47e1-b6f2-cb400f078caf'::uuid;

UPDATE public.destinations
SET region = 'Somali', city = 'Jijiga', location = '{"lat":9.3675475,"lng":42.793438}'
WHERE id = '1e0f8cff-e37b-4576-bfe4-7504166dd876'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Jinka', location = '{"lat":5.786181,"lng":36.5654425}'
WHERE id = '1e580650-e9ae-4a13-ad77-bcf61acde245'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole', location = '{"lat":8.9970566,"lng":38.7866129}'
WHERE id = '1e5fb8fb-9aa3-485b-ac54-a57255d5aac4'::uuid;

UPDATE public.destinations
SET region = 'Amhara', location = '{"lat":10.3511111,"lng":39.7959722}'
WHERE id = '1e95d4ee-0a3f-4595-98b3-9e7949a572cf'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole', location = '{"lat":8.9919047,"lng":38.7828311}'
WHERE id = '1ea861e7-cb1f-424d-ae1e-a3f646a04d6d'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Jibat', location = '{"lat":8.7435984,"lng":37.4727901}'
WHERE id = '1efae8e3-da7d-4023-9252-4429553933c0'::uuid;

UPDATE public.destinations
SET region = 'Amhara', location = '{"lat":10.13333,"lng":39.25}'
WHERE id = '1f001180-7b6a-4c63-80ea-2d8f6aa0fdfb'::uuid;

UPDATE public.destinations
SET region = 'Dire Dawa', city = 'Dire Dawa', location = '{"lat":9.5821663,"lng":41.8582532}'
WHERE id = '1fa93518-ef46-47ee-b8cb-80974632fa72'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Hayq', location = '{"lat":11.3388177,"lng":39.6974908}'
WHERE id = '1fe95f3d-b517-485c-8606-2c76364232a7'::uuid;

UPDATE public.destinations
SET region = 'South West Ethiopia Peoples', city = 'Aman', location = '{"lat":6.9568642,"lng":35.5544431}'
WHERE id = '204e1584-f5ab-442a-95e0-d6c1928546a6'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Lalibela', location = '{"lat":12.0313144,"lng":39.0452066}'
WHERE id = '2129a44b-cf85-453a-b73d-325d060210e1'::uuid;

UPDATE public.destinations
SET region = 'South West Ethiopia Peoples', city = 'Mizan Aman', location = '{"lat":6.9952914,"lng":35.5868945}'
WHERE id = '2162a321-4397-4796-b2c5-884443ba2282'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Bahir Dar Special Zone', location = '{"lat":11.5990209,"lng":37.3848859}'
WHERE id = '219e56e6-83b1-40b4-9542-f6e99e81a063'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Arsi Negelle', location = '{"lat":7.5919956,"lng":38.6913141}'
WHERE id = '21a09171-dbeb-4615-8ffd-0140311ed755'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Turmi', location = '{"lat":4.96835,"lng":36.487794}'
WHERE id = '21bd35c9-3b3d-4cb7-b92e-6947621f5d16'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Tiya', location = '{"lat":8.437331,"lng":38.609296}'
WHERE id = '2231f7f1-2a31-402c-85ba-10c48224cbc7'::uuid;

COMMIT;
