-- Generated by scripts/enrich_destinations_google.py
BEGIN;

UPDATE public.destinations
SET region = 'Oromia', city = 'Ambo', location = '{"lat":9.077867699999999,"lng":38.588705700000006}'
WHERE id = '000b9cf0-b53f-4546-8840-ba364d586682'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Gondar', location = '{"lat":12.609496000000002,"lng":37.470178}'
WHERE id = '0051e3e0-cdf6-4292-8b3f-55e0cf27bec7'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Asela', location = '{"lat":7.969162799999999,"lng":39.131521}'
WHERE id = '00e4f04e-be64-4f35-8e8f-41d59df6a948'::uuid;

COMMIT;
