-- Generated by scripts/enrich_destinations.py
-- Review destinations_enrichment_report.csv before applying.
BEGIN;

UPDATE public.destinations
SET region = 'Amhara', city = 'Gorgora', location = '{"lat":12.2382669,"lng":37.2971393}'
WHERE id = '00294e3d-1208-4208-a015-996c71cf9738'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Gulale', location = '{"lat":9.076097,"lng":38.7555656}'
WHERE id = '0051e3e0-cdf6-4292-8b3f-55e0cf27bec7'::uuid;

UPDATE public.destinations
SET region = 'Afar', location = '{"lat":13.6030321,"lng":40.6634086}'
WHERE id = '00620588-4ca4-48fa-90d5-3eba0e18392b'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Asella', location = '{"lat":7.95,"lng":39.13333}'
WHERE id = '00e4f04e-be64-4f35-8e8f-41d59df6a948'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Jinka', location = '{"lat":5.786181,"lng":36.5654425}'
WHERE id = '0113fde5-2ea6-4aeb-965d-64901480d8c0'::uuid;

UPDATE public.destinations
SET region = 'Benishangul-Gumuz', city = 'Assosa', location = '{"lat":10.0646352,"lng":34.5437024}'
WHERE id = '0172040d-afdc-49d2-a38e-f7c51cb36544'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Yeka', location = '{"lat":9.0371282,"lng":38.8398518}'
WHERE id = '01a955e4-eb2e-4586-9b0d-5ab3c563c175'::uuid;

UPDATE public.destinations
SET region = 'Amhara', location = '{"lat":10.3511111,"lng":39.7959722}'
WHERE id = '022c139e-027b-4c2b-b90f-103bdcf0f824'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bishoftu', location = '{"lat":8.750004,"lng":38.981734}'
WHERE id = '02327ceb-e29b-4d7e-8904-dd4c8f1c7944'::uuid;

UPDATE public.destinations
SET region = 'Sidama', city = 'Wondo Genet', location = '{"lat":7.0854757,"lng":38.6141113}'
WHERE id = '0255ec62-2fd1-40be-ac57-209276df35e9'::uuid;

UPDATE public.destinations
SET region = 'Sidama', city = 'Hawassa', location = '{"lat":7.1031122,"lng":38.5720312}'
WHERE id = '02890b20-0688-473d-98ed-09a1e4d3a042'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Dus', location = '{"lat":5.2803237,"lng":36.1938132}'
WHERE id = '02c8223e-334d-47e5-b354-7fca28aada4f'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', location = '{"lat":5.33333,"lng":37.55}'
WHERE id = '032ca2c4-2e8c-4a0f-9b3e-0df565405328'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ababa', location = '{"lat":9.0358362,"lng":38.7524118}'
WHERE id = '0383471e-05bb-422a-872c-430f3ecf90b0'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ababa', location = '{"lat":9.0358119,"lng":38.7524315}'
WHERE id = '039c265c-7824-4623-8e6a-455de2877896'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Gonder', location = '{"lat":12.610368,"lng":37.466766}'
WHERE id = '03a350a1-6dbb-4dcb-a64a-20c725d254b9'::uuid;

UPDATE public.destinations
SET region = 'South West Ethiopia Peoples', location = '{"lat":6.9042595,"lng":36.7301591}'
WHERE id = '03b49d09-289b-46f3-a0a6-911ce7e8b65c'::uuid;

UPDATE public.destinations
SET region = 'Oromia', location = '{"lat":8.5423252,"lng":38.8553578}'
WHERE id = '03fdc7fc-8467-46cf-a763-6e088fde3e14'::uuid;

UPDATE public.destinations
SET region = 'South West Ethiopia Peoples', city = 'Aman', location = '{"lat":6.9568642,"lng":35.5544431}'
WHERE id = '03fee98a-a4f1-406e-ac0b-2db9aa5a2915'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Debre Libanos', location = '{"lat":9.7295697,"lng":38.8167682}'
WHERE id = '04bb43b1-4136-46a9-923e-e6eb3baaa15d'::uuid;

UPDATE public.destinations
SET region = 'Central Ethiopia Regional State', location = '{"lat":7.5,"lng":37.75}'
WHERE id = '04c8c45f-4738-457f-bf20-218105ff3170'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Chencha', location = '{"lat":6.251095,"lng":37.572946}'
WHERE id = '04ea15b4-829e-4e66-9db0-208eb90ce212'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Gulale', location = '{"lat":9.0466103,"lng":38.7687405}'
WHERE id = '051f97af-5ce3-4bb0-853a-7c6ae6c5903b'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Wajira Hudo', location = '{"lat":7.167028,"lng":38.2930673}'
WHERE id = '0561e3f5-fc79-4bc0-a204-848d49c202f8'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bishoftu', location = '{"lat":8.7789777,"lng":39.0004021}'
WHERE id = '0562a30c-63b6-4c1a-9d52-8cc443b9d1f1'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Axum', location = '{"lat":14.1220982,"lng":38.7321749}'
WHERE id = '0576571c-aa6c-4d55-9f83-39ad11d50442'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole', location = '{"lat":9.0062112,"lng":38.8018601}'
WHERE id = '0601c42b-9a91-41fe-a460-4708f4d35127'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos', location = '{"lat":8.9820782,"lng":38.7584682}'
WHERE id = '0621462d-39b6-421d-93c2-36425fc9ba8c'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos', location = '{"lat":9.010443,"lng":38.7651132}'
WHERE id = '06546a02-bb0a-491b-8fa5-4c3ecb590753'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Jinka', location = '{"lat":5.786181,"lng":36.5654425}'
WHERE id = '065fbdd8-f6fe-4fd6-ade7-38b70500f4f3'::uuid;

UPDATE public.destinations
SET region = 'Amhara', location = '{"lat":13.2179939,"lng":38.3867335}'
WHERE id = '06929243-25f5-4b7f-818e-6770c4fd6500'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos', location = '{"lat":9.0211333,"lng":38.7622597}'
WHERE id = '069a3989-4cef-4a1f-9d1b-4adee39e6660'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos', location = '{"lat":9.0145765,"lng":38.7662199}'
WHERE id = '06e8bf00-f0ca-4393-b9a2-c04eb25fb2bc'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Asella', location = '{"lat":7.9150565,"lng":39.2620904}'
WHERE id = '06f3b178-5219-4a8e-b9b5-be91e7219175'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Wolleka', location = '{"lat":12.6420059,"lng":37.4766478}'
WHERE id = '06f6cccf-3b0c-4514-aac1-11d5c4531468'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole', location = '{"lat":9.0060961,"lng":38.8111966}'
WHERE id = '0719dd1e-6986-49b7-b092-400e2548dfc5'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Adama', location = '{"lat":8.5544108,"lng":39.2610051}'
WHERE id = '07384a8f-5e47-43e5-af76-0ed738a4f7f6'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Sodere', location = '{"lat":8.4034494,"lng":39.3869748}'
WHERE id = '073a802a-e42d-4440-89ba-36dffc6bc0f1'::uuid;

UPDATE public.destinations
SET region = 'Afar', location = '{"lat":12.66667,"lng":40.33333}'
WHERE id = '07732b82-a311-40cc-b641-f0118bb25bce'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Bahir Dar Special Zone', location = '{"lat":11.5949808,"lng":37.3861701}'
WHERE id = '079c543b-0632-403a-a752-7f7b63cd0037'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ababa', location = '{"lat":9.0308012,"lng":38.7664911}'
WHERE id = '07e3c3e0-9588-41e5-a2b6-5865142da6e2'::uuid;

UPDATE public.destinations
SET region = 'Somali', location = '{"lat":7.5160462,"lng":46.2875075}'
WHERE id = '07e446b5-5b4a-4f84-bf73-d43ac8c07f2a'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Wajira Hudo', location = '{"lat":7.167028,"lng":38.2930673}'
WHERE id = '08169283-0ecd-4fee-be90-3e80c16fb6f2'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Woldia', location = '{"lat":11.8342096,"lng":39.6056115}'
WHERE id = '081c2f68-7301-4e19-abf1-472b6b05f4b5'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Wolaita Sodo', location = '{"lat":6.8577533,"lng":37.7578499}'
WHERE id = '084c39db-ea06-4008-9c00-26f7361f4330'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos', location = '{"lat":9.0187247,"lng":38.7650277}'
WHERE id = '0873ce73-8dbd-4d59-a980-c8e5973b4de3'::uuid;

UPDATE public.destinations
SET region = 'Afar', location = '{"lat":14.2424728,"lng":40.2996919}'
WHERE id = '08e88666-1276-403b-972c-a82a3cedd23e'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos', location = '{"lat":9.0023504,"lng":38.7695919}'
WHERE id = '0904c198-522d-4eae-909c-1a03548e3123'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Lalibela', location = '{"lat":12.0360639,"lng":39.0456845}'
WHERE id = '09c323bd-9d34-4fda-ac2f-15bce647102c'::uuid;

UPDATE public.destinations
SET region = 'Oromia', location = '{"lat":5.7146161,"lng":38.8871168}'
WHERE id = '09cf80ad-8f11-4213-860c-c391cac7c1e4'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Wolaita Sodo', location = '{"lat":6.8577533,"lng":37.7578499}'
WHERE id = '09e458fc-9121-48c5-ab82-0a2d127ef57a'::uuid;

UPDATE public.destinations
SET region = 'Dire Dawa', city = 'Dire Dawa', location = '{"lat":9.5913368,"lng":41.8566126}'
WHERE id = '0a100234-8028-4018-86a7-c3803711309e'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Kindo Koysha', location = '{"lat":6.933691,"lng":37.5892615}'
WHERE id = '0a20e07d-73dd-4284-ae5b-b631cc2cc559'::uuid;

UPDATE public.destinations
SET region = 'Amhara', location = '{"lat":11.91667,"lng":37.26667}'
WHERE id = '0a2a2811-9f5b-4f9a-8074-5e180fd06d45'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ketema', location = '{"lat":9.0431757,"lng":38.723931}'
WHERE id = '0a56edc3-e173-4766-863d-d602923659eb'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Woldia', location = '{"lat":11.8342096,"lng":39.6056115}'
WHERE id = '0a71af5a-b80e-43bd-91dd-060ce654e2b5'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole', location = '{"lat":9.0099757,"lng":38.8520481}'
WHERE id = '0a85ecd4-5c50-4860-b012-f6780d7ed2d3'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Debebahir', location = '{"lat":13.1979701,"lng":37.8963243}'
WHERE id = '0b2fc774-3a9b-4d36-8179-10da157097ac'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole', location = '{"lat":9.0022589,"lng":38.7960223}'
WHERE id = '0b323a29-7996-4f3d-b524-51210f902bdd'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Gulale', location = '{"lat":9.0466103,"lng":38.7687405}'
WHERE id = '0b7eda7d-dfb8-456d-b691-d6ce2890ed58'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Hashenge', location = '{"lat":12.5793136,"lng":39.5015961}'
WHERE id = '0b82fd83-fb1a-48cb-b8f4-141efbd9cac2'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Gura', location = '{"lat":7.6162029,"lng":36.5840984}'
WHERE id = '0bb81add-f212-4fa1-a84c-03ac54cb7b4e'::uuid;

UPDATE public.destinations
SET region = 'Oromia', location = '{"lat":4.0144302,"lng":38.5471355}'
WHERE id = '0beb83f4-243e-4161-8657-8f7ce8b4d268'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Waliso', location = '{"lat":8.5525105,"lng":37.9756098}'
WHERE id = '0bfc7ee8-ddd1-4b35-baa9-543a2a227862'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Moyale', location = '{"lat":3.5241898,"lng":39.0512683}'
WHERE id = '0bfd7934-abde-4fff-bd12-4a56358498a0'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Tekeze', location = '{"lat":11.8756797,"lng":38.9503039}'
WHERE id = '0c0a0214-76e4-480e-8291-7d97965501da'::uuid;

UPDATE public.destinations
SET region = 'Oromia', location = '{"lat":8.93278,"lng":41.80361}'
WHERE id = '0c0f9ce0-6896-4e41-a1fa-d5e3c229b28a'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bule Hora', location = '{"lat":5.6399545,"lng":38.2393711}'
WHERE id = '0c1a1191-572e-4565-b33c-18646387bc44'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole', location = '{"lat":9.0134031,"lng":38.7797654}'
WHERE id = '0c86b942-94ae-49d7-aee3-20c43cc50fe5'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bale', location = '{"lat":7.7308591,"lng":39.9998827}'
WHERE id = '0cc86c22-d3a7-48d9-ac1a-1478f842b8ff'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Wajira Hudo', location = '{"lat":7.167028,"lng":38.2930673}'
WHERE id = '0d291d6c-0210-408b-87a8-fbc919f72dc5'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Tekeze', location = '{"lat":11.8756797,"lng":38.9503039}'
WHERE id = '0db2f2ba-292b-4bfd-a534-f3bbcf855467'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Shufune', location = '{"lat":9.1047428,"lng":38.7097525}'
WHERE id = '0deb4635-ec6e-41d1-95cf-f0b0d2389259'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos', location = '{"lat":9.010443,"lng":38.7651132}'
WHERE id = '0e063698-9ba5-4022-b19f-818523281e33'::uuid;

UPDATE public.destinations
SET location = '{"lat":9.9749582,"lng":40.3904199}'
WHERE id = '0e43bad9-7f39-4795-be9d-01fd987acf85'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bishoftu', location = '{"lat":8.750004,"lng":38.981734}'
WHERE id = '0e4d4519-15ac-4164-95ff-67610eea618a'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Finicha''a', location = '{"lat":9.5578092,"lng":37.3662213}'
WHERE id = '0e620435-6085-42a3-83a5-850fef257e71'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Arba Minch', location = '{"lat":6.0215142,"lng":37.5539809}'
WHERE id = '0e95b8df-daa1-4410-a730-189befba6f99'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Degan', location = '{"lat":11.18333,"lng":39.9}'
WHERE id = '0f2b4014-1411-4d39-9d1f-ab7c9840a894'::uuid;

UPDATE public.destinations
SET region = 'Tigray', location = '{"lat":14.25,"lng":38.91667}'
WHERE id = '0f3ec61a-c1a4-4baf-bfdc-6913b4805a5c'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos', location = '{"lat":9.0102293,"lng":38.7606309}'
WHERE id = '0f49f40b-5d9b-48c8-900f-c01e75ff02c0'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Lalibela', location = '{"lat":12.0360639,"lng":39.0456845}'
WHERE id = '0f779742-b201-49c7-858f-d1eadb6516b3'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ababa', location = '{"lat":9.0358119,"lng":38.7524315}'
WHERE id = '0f7c84bd-4645-4e2b-b0c8-c603b9a940b1'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kolfe Keranio', location = '{"lat":8.9811975,"lng":38.6852742}'
WHERE id = '0fa2359e-59e0-4cb3-867c-b289e8e9a009'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Ankober', location = '{"lat":9.5911547,"lng":39.7338213}'
WHERE id = '0fb928af-dda8-4f10-8883-ac29911ded6d'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Lalibela', location = '{"lat":12.0360639,"lng":39.0456845}'
WHERE id = '0ff366be-2732-444c-bad4-160e65b47fb1'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Jinka', location = '{"lat":5.786181,"lng":36.5654425}'
WHERE id = '10428c4d-037c-4235-a04c-81eeedfcbb52'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Sululta', location = '{"lat":9.1080861,"lng":38.8193556}'
WHERE id = '1083c39b-85cc-457d-9a68-518fe138f7be'::uuid;

UPDATE public.destinations
SET region = 'Afar', location = '{"lat":9.5,"lng":39.95}'
WHERE id = '10995a8c-f549-4261-9251-3c7e872b92b8'::uuid;

COMMIT;
