-- Generated by scripts/enrich_destinations.py
-- Review destinations_enrichment_report.csv before applying.
BEGIN;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Yeka', location = '{"lat":9.0205677,"lng":38.8002333}'
WHERE id = '2d2bfb20-6c88-413f-8fb4-95bb1e6f6e73'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Enferaz', location = '{"lat":12.2344189,"lng":37.6350175}'
WHERE id = '2e7db422-9fbc-4614-ad3a-f0dc3ba34130'::uuid;

COMMIT;
