-- Generated by scripts/enrich_destinations.py
-- Review destinations_enrichment_report.csv before applying.
BEGIN;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos', location = '{"lat":9.0102054,"lng":38.7629294}'
WHERE id = '59792e0c-f972-415d-837d-85233b8743b9'::uuid;

UPDATE public.destinations
SET region = 'Sidama', city = 'Hawassa', location = '{"lat":7.040469,"lng":38.4945612}'
WHERE id = '5a72b83b-fa8c-43fa-9f07-7300ee34b739'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ababa', location = '{"lat":9.0260054,"lng":38.7507566}'
WHERE id = '5b0361dc-661a-4ae1-a57e-e93a5acd26f6'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos', location = '{"lat":9.0185621,"lng":38.7562463}'
WHERE id = '6239e48b-37ce-42eb-8bae-5ce1207783b3'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos', location = '{"lat":9.0133925,"lng":38.756404}'
WHERE id = '62783716-55b7-4691-bf65-0167086218a7'::uuid;

COMMIT;
