-- Generated by scripts/enrich_destinations.py
-- Review destinations_enrichment_report.csv before applying.
BEGIN;

UPDATE public.destinations
SET region = 'South West Ethiopia Peoples', location = '{"lat":6.9042595,"lng":36.7301591}'
WHERE id = '03b49d09-289b-46f3-a0a6-911ce7e8b65c'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos', location = '{"lat":9.0023504,"lng":38.7695919}'
WHERE id = '0904c198-522d-4eae-909c-1a03548e3123'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Debebahir', location = '{"lat":13.1979701,"lng":37.8963243}'
WHERE id = '0b2fc774-3a9b-4d36-8179-10da157097ac'::uuid;

COMMIT;
