-- Generated by scripts/enrich_destinations.py
-- Review destinations_enrichment_report.csv before applying.
BEGIN;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Kirkos', location = '{"lat":9.0161832,"lng":38.7677471}'
WHERE id = '788942e1-12f4-4423-b7ed-a620138313fa'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Arada', location = '{"lat":9.0239378,"lng":38.7665055}'
WHERE id = '78e3c8c4-de3f-4539-83ba-d6fd93b64197'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Kindo Koysha', location = '{"lat":6.933691,"lng":37.5892615}'
WHERE id = '791f2010-c9f7-46cf-b9e2-831136c7e22a'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Romanat', location = '{"lat":13.5899444,"lng":39.4255413}'
WHERE id = '79586961-69c8-4c9f-8449-cfc4b08ed115'::uuid;

UPDATE public.destinations
SET region = 'Amhara', location = '{"lat":13.2458802,"lng":38.0999456}'
WHERE id = '7978eafa-3e91-4915-ab4e-415ca2e10beb'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Ankober', location = '{"lat":9.5911547,"lng":39.7338213}'
WHERE id = '7a15aa66-fed8-4dd5-8328-0ad463fcb4be'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole', location = '{"lat":9.0003059,"lng":38.7817192}'
WHERE id = '7a4fa0f6-bb6a-4080-b62d-0ba765f074d7'::uuid;

UPDATE public.destinations
SET region = 'Gambela', city = 'Gambela', location = '{"lat":8.2503656,"lng":34.5877344}'
WHERE id = '7abea604-751f-41e1-bb7f-f5c1f35dfe25'::uuid;

UPDATE public.destinations
SET region = 'Afar', city = 'Melabday', location = '{"lat":13.9745086,"lng":40.0685197}'
WHERE id = '7b4e7cef-beaf-4208-81b3-dbc6d1c90297'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', location = '{"lat":5.835358,"lng":37.568742}'
WHERE id = '7bacf781-a26b-46a8-81e1-b12eeb816990'::uuid;

UPDATE public.destinations
SET region = 'Dire Dawa', city = 'Dire Dawa', location = '{"lat":9.592233,"lng":41.8674731}'
WHERE id = '7c15eb70-294d-471e-90eb-bc32d5e1e764'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Sof Omar', location = '{"lat":6.9013463,"lng":40.8438263}'
WHERE id = '7cbc0d54-1e40-4fe3-81c9-01fc6d81b29a'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Gonder', location = '{"lat":12.6174164,"lng":37.4575171}'
WHERE id = '7cc14bb7-fbe0-4ee9-a700-0492dfcb447d'::uuid;

UPDATE public.destinations
SET region = 'Amhara', location = '{"lat":13.2458802,"lng":38.0999456}'
WHERE id = '7d01281b-5acf-4850-90d2-74d00c1829cc'::uuid;

UPDATE public.destinations
SET region = 'Gambela', city = 'Gambela', location = '{"lat":8.2503656,"lng":34.5877344}'
WHERE id = '7d92ca06-8c62-48d7-85cf-d6ffba4d9fe7'::uuid;

UPDATE public.destinations
SET region = 'Central Ethiopia Regional State', city = 'Welkite', location = '{"lat":8.2925634,"lng":37.781154}'
WHERE id = '7e33cae2-4050-4b22-bdad-9bdb255ddd1e'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Alamata', location = '{"lat":12.4175995,"lng":39.5603233}'
WHERE id = '7eab8587-b580-4d89-a9c5-b3b0a7d3ef3c'::uuid;

UPDATE public.destinations
SET region = 'Oromia', location = '{"lat":8.78333,"lng":38.71667}'
WHERE id = '7f03a0a7-5543-4810-af24-c9738cd35f15'::uuid;

UPDATE public.destinations
SET region = 'Amhara', location = '{"lat":12.3230117,"lng":35.5544937}'
WHERE id = '7f7941de-606d-41f2-9784-a581d6b3a775'::uuid;

UPDATE public.destinations
SET region = 'Oromia', location = '{"lat":7.1745689,"lng":39.4298925}'
WHERE id = '8009a153-ae22-4577-b206-fd7f5242770c'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Ankober', location = '{"lat":9.5911547,"lng":39.7338213}'
WHERE id = '804aa093-37d1-4ecf-b976-537214dcdbe1'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Debre Birhan', location = '{"lat":9.6283285,"lng":39.4969562}'
WHERE id = '814a6aa4-8d5d-4564-ada7-29a0a304f31d'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Gonder', location = '{"lat":12.6226064,"lng":37.4458824}'
WHERE id = '81999c9f-98b5-4082-a3ac-8f3a5d8ef41b'::uuid;

UPDATE public.destinations
SET region = 'Somali', city = 'Jijiga', location = '{"lat":9.3508526,"lng":42.8003788}'
WHERE id = '81e305b4-cce7-4240-8715-89fd09e9cda4'::uuid;

UPDATE public.destinations
SET region = 'Amhara', location = '{"lat":13.2458802,"lng":38.0999456}'
WHERE id = '82aba8b1-2db2-4e2d-a571-714d5afee55b'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Bahir Dar Special Zone', location = '{"lat":11.6030239,"lng":37.3797987}'
WHERE id = '82eae310-3d7c-49aa-83fb-28d265edc902'::uuid;

UPDATE public.destinations
SET region = 'Tigray', city = 'Yeha', location = '{"lat":14.2859622,"lng":39.0179108}'
WHERE id = '833154f4-0f60-41b7-b495-50c9d226cb8c'::uuid;

UPDATE public.destinations
SET region = 'Afar', location = '{"lat":14.2424728,"lng":40.2996919}'
WHERE id = '835093ea-45b9-4aa7-b2db-64933e21749b'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Bishoftu', location = '{"lat":8.7789777,"lng":39.0004021}'
WHERE id = '835a62a6-07f4-49ca-a561-9e50de625daa'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole', location = '{"lat":9.0002179,"lng":38.7833921}'
WHERE id = '8364c9d2-7a3b-40e7-84fa-58272fe4d30e'::uuid;

UPDATE public.destinations
SET region = 'Somali', city = 'Jijiga', location = '{"lat":9.3508526,"lng":42.8003788}'
WHERE id = '83950463-0db0-4149-941a-e8b61955fd62'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Ankober', location = '{"lat":9.5911547,"lng":39.7338213}'
WHERE id = '83c5e55d-dfd5-4c0e-a896-38a9558ce548'::uuid;

UPDATE public.destinations
SET region = 'Afar', location = '{"lat":11.1711957,"lng":41.7873451}'
WHERE id = '83e79b66-f2d6-4aef-bc7b-78f8090042da'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Yirga Cheffe', location = '{"lat":6.1529383,"lng":38.2023167}'
WHERE id = '83faa7a2-d590-4250-ac24-c7ba27b7abe1'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Lideta', location = '{"lat":9.0195322,"lng":38.748111}'
WHERE id = '8451ed49-dc4f-45f1-b76d-89bc6b96ac98'::uuid;

UPDATE public.destinations
SET region = 'Sidama', city = 'Irgalem', location = '{"lat":6.7473747,"lng":38.40767}'
WHERE id = '845fbe3e-83ff-40d7-9095-34b3478634ed'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', city = 'Yirga Cheffe', location = '{"lat":6.1529383,"lng":38.2023167}'
WHERE id = '85d2b02d-2abc-4042-9899-c30686233d5a'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Asella', location = '{"lat":7.95,"lng":39.13333}'
WHERE id = '85db4b7d-bd91-4392-95ed-cc625f8e610e'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Injibara', location = '{"lat":10.9592268,"lng":36.9340697}'
WHERE id = '867907b1-ded6-4dcd-9f3a-8d8b5246cc54'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Gonder', location = '{"lat":12.6082643,"lng":37.4698895}'
WHERE id = '86da00d3-4067-4eea-93a6-c63358a077d8'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', location = '{"lat":5.25,"lng":37.5}'
WHERE id = '875b32ea-050c-4fd2-b883-749a03f6646d'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Yabēlo', location = '{"lat":4.8888074,"lng":38.109828}'
WHERE id = '877c1012-20c9-411c-80c3-34e069c5fc40'::uuid;

UPDATE public.destinations
SET region = 'Gambela', city = 'Gambela', location = '{"lat":8.2503656,"lng":34.5877344}'
WHERE id = '87a9de05-f18c-484d-919b-5e43a6013d18'::uuid;

UPDATE public.destinations
SET region = 'South Ethiopia Regional State', location = '{"lat":6.4105535,"lng":37.2124317}'
WHERE id = '87f36375-f6b3-4789-b379-de10e85bdc11'::uuid;

UPDATE public.destinations
SET region = 'Amhara', location = '{"lat":10.7117887,"lng":37.8435035}'
WHERE id = '87f84f43-33a6-42f8-8896-c33235bd2bb1'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Debre Tabor', location = '{"lat":11.856591,"lng":38.008309}'
WHERE id = '88219826-9557-4b37-8021-366ff09d0fd2'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Sire Robe', location = '{"lat":8.3911374,"lng":39.0860496}'
WHERE id = '886f3a62-4647-40b8-b451-0bb914393cfa'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole', location = '{"lat":9.0060961,"lng":38.8111966}'
WHERE id = '88793f58-7a9c-4b9f-bbcc-9be429c79782'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Addis Ketema', location = '{"lat":9.0367127,"lng":38.7275668}'
WHERE id = '89af16e0-ae04-431a-a31c-9b4ee6f2d7ec'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Debre Markos', location = '{"lat":10.3358665,"lng":37.7285604}'
WHERE id = '89e57cc5-f90c-4f0f-b936-779e5472277b'::uuid;

UPDATE public.destinations
SET region = 'Amhara', location = '{"lat":10.3511111,"lng":39.7959722}'
WHERE id = '8a2c9876-3d1d-4329-80cc-19e3e34cf107'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Enferaz', location = '{"lat":12.2344189,"lng":37.6350175}'
WHERE id = '8ae1271e-a65b-4684-ab42-c626ce27cfbd'::uuid;

UPDATE public.destinations
SET region = 'Dire Dawa', city = 'Dire Dawa', location = '{"lat":9.5913368,"lng":41.8566126}'
WHERE id = '8bb0a047-c759-415a-b29f-a7cb180ca0fc'::uuid;

UPDATE public.destinations
SET region = 'Addis Ababa', city = 'Bole', location = '{"lat":8.9934018,"lng":38.7941228}'
WHERE id = '8d30a35e-22e9-47a3-aea6-d724a3f1238c'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Gore', location = '{"lat":8.1525979,"lng":35.5371154}'
WHERE id = '8db4ea13-f1d7-49db-b9f2-fa182aeda975'::uuid;

UPDATE public.destinations
SET region = 'Afar', location = '{"lat":13.2972405,"lng":40.7809115}'
WHERE id = '8dd89383-1d93-4358-9f05-75d34b5e5adc'::uuid;

UPDATE public.destinations
SET region = 'Amhara', city = 'Debre Birhan', location = '{"lat":9.6752117,"lng":39.5324899}'
WHERE id = '8e2ad15c-42ba-4c98-b014-1acd387e8d68'::uuid;

UPDATE public.destinations
SET region = 'Oromia', city = 'Yabēlo', location = '{"lat":4.8888074,"lng":38.109828}'
WHERE id = '8eb7ca14-baca-476a-a5c5-1e9f1efe708c'::uuid;

COMMIT;
